# NephroLLM — Execution Plan

1. Environment setup
2. Load Llama 3.2 3B Instruct
3. Verify base-model inference
4. Load and validate the nephrology benchmark
5. Run a fresh baseline evaluation
6. Analyze baseline failures
7. Prepare fine-tuning dataset
8. Fine-tune using QLoRA
9. Save the LoRA adapter
10. Run the exact same evaluation on the fine-tuned model
11. Evaluate on held-out questions
12. Compare base vs fine-tuned model
13. Document findings, limitations, and conclusions

# NephroLLM — Fine-Tuning Llama 3.2 3B for Nephrology Q&A

Educational fine-tuning experiment using QLoRA to adapt Llama 3.2 3B Instruct to nephrology-focused questions.

**Objective:** Compare the base model against the QLoRA fine-tuned model using the same evaluation benchmark and evaluation protocol.

In [37]:
# cell 2
!pip install -q -U transformers datasets accelerate peft bitsandbytes trl

cell 3
**package/GPU/version check**

In [38]:
# cell 4
import torch
import transformers
import datasets
import peft
import bitsandbytes

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Datasets:", datasets.__version__)
print("PEFT:", peft.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "GPU memory:",
        round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
        "GB"
    )

PyTorch: 2.10.0+cu128
Transformers: 5.17.0
Datasets: 5.0.1
PEFT: 0.21.0
CUDA available: True
GPU: Tesla T4
GPU memory: 14.56 GB

cell 5 **Hugging Face authentication**

In [39]:
# cell 6
from kaggle_secrets import UserSecretsClient

user_secrets = UserSecretsClient()

hf_token = user_secrets.get_secret("HF_TOKEN")

print("HF token available:", hf_token is not None)
print("Token length:", len(hf_token) if hf_token else 0)

HF token available: True
Token length: 37

cell 7 # **Step 2 — Load Llama 3.2 3B**

In [40]:
# cell 8 
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from kaggle_secrets import UserSecretsClient

# Get Hugging Face token securely
user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")

model_id = "meta-llama/Llama-3.2-3B-Instruct"

# 4-bit quantization configuration
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

print("Loading tokenizer...")

tokenizer = AutoTokenizer.from_pretrained(
    model_id,
    token=hf_token
)

print("Loading model...")

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    token=hf_token
)

print("Model loaded successfully!")
print("Model device:", model.device)

Loading tokenizer...
Loading model...

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Model loaded successfully!
Model device: cuda:0

cell 9 

**Step 3 — Run our first baseline inference**

Now we're going to talk to the untouched model.

This is important: don't fine-tune anything yet. We first want to see what the base model does.


                    BASE MODEL
                       │
                       ▼
             30 nephrology questions
                       │
                       ▼
                Baseline scores
                       │
                       ▼
                Failure analysis
                       │
                       ▼
                  QLoRA training
                       │
                       ▼
              SAME 30 questions
                       │
                       ▼
             Fine-tuned scores

cell 10 
**ask_model()**

In [41]:
# cell 11
def ask_model(question, max_new_tokens=256):
    messages = [
        {
            "role": "system",
            "content": (
                "You are an educational assistant specializing in nephrology. "
                "Provide clear, factual, educational explanations. "
                "Do not provide diagnosis or personalized medical advice."
            )
        },
        {
            "role": "user",
            "content": question
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    answer = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    return answer.strip()

cell 12 **smoke test**

In [43]:
# cell 13
question = "What is the primary function of the glomerulus?"

answer = ask_model(question)

print("QUESTION:")
print(question)

print("\nMODEL ANSWER:")
print(answer)

QUESTION:
What is the primary function of the glomerulus?

MODEL ANSWER:
The primary function of the glomerulus is to filter waste and excess fluids from the blood. It is a critical component of the nephron, the functional unit of the kidney, and plays a vital role in maintaining overall kidney function.

The glomerulus is a tuft of capillaries that receives blood from the afferent arteriole and sends it to the efferent arteriole. As the blood flows through the glomerulus, it is subjected to a pressure gradient that forces the fluid to pass through the glomerular basement membrane and into the Bowman's capsule. This process is known as filtration.

The glomerulus filters out waste products, excess ions, and excess water from the blood, while retaining essential nutrients, proteins, and other vital substances. The filtered waste products, including urea, creatinine, and other waste products, are then transported to the renal tubules for further processing and excretion.

In essence, the glomerulus acts as a selective filter, allowing only essential substances to pass through while rejecting waste products and excess fluids, making it a crucial component of the kidney's role in maintaining homeostasis and overall health.

cell 14 
**NephroLLM data strategy**

| Purpose                  | Data                                               | Use                         |
| ------------------------ | -------------------------------------------------- | --------------------------- |
| **Primary benchmark**    | NEJM-AI nephrology dataset                         | Baseline + final evaluation |
| **Fine-tuning**          | Our curated nephrology educational Q&A             | Training                    |
| **Generalization check** | Separate nephrology questions not used in training | Held-out evaluation         |



                 NEPHROLOGY BENCHMARK
                         │
          ┌──────────────┼──────────────┐
          │              │              │
          ▼              ▼              ▼
      Baseline/       Held-out       Training
      Final Test      Evaluation      Dataset
          │              │              │
          │              │              └── QLoRA
          │              │
          ▼              ▼
      Base vs FT      Generalization

cell 15 # Step 4 — Run the Llama 3.2 3B baseline on the 636 questions

In [44]:
# cell 16
import os
import pandas as pd

# Find the finalized primary evaluation file
matches = []

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file == "nephrollm_primary_eval.csv":
            matches.append(os.path.join(root, file))

print("Found:", matches)

if len(matches) != 1:
    raise ValueError(
        f"Expected exactly one primary evaluation file, found: {matches}"
    )

eval_path = matches[0]
eval_df = pd.read_csv(eval_path)

print("Evaluation file:", eval_path)
print("Questions loaded:", len(eval_df))

display(
    eval_df[
        ["BenchmarkID", "Subject", "Question", "Choices", "Answer"]
    ].head()
)

Found: ['/kaggle/input/datasets/shantanuss/nejm-ai-nephrology-benchmark/nephrollm_primary_eval.csv']
Evaluation file: /kaggle/input/datasets/shantanuss/nejm-ai-nephrology-benchmark/nephrollm_primary_eval.csv
Questions loaded: 636

,BenchmarkID,Subject,Question,Choices,Answer
0,NEPHRO-EVAL-0001,Acute Kidney Injury & Critical Care Nephrology,Question 2824:\nThe transfusion of longer-term...,1. Increased risk of transfusion-related react...,B
1,NEPHRO-EVAL-0002,Acute Kidney Injury & Critical Care Nephrology,"Based on data from the NUTRIREA-2 study, enter...",A. Decreased incidence of systemic bacteremia\...,B
2,NEPHRO-EVAL-0003,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is CORRECT about th...,1. She is at decreased risk for inpatient mort...,B
3,NEPHRO-EVAL-0004,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is associated with ...,A. A decreased risk of surgical site infection...,B
4,NEPHRO-EVAL-0005,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is the MOST importa...,A. Administration of a bolus of 30 ml/kg 0.9% ...,D

cell 17
**Step 5 — Run the full 636-question baseline**

Before doing that, let's lock the evaluation configuration.

We'll use:

636 primary questions
Same prompt for every question
do_sample=False → deterministic generation
max_new_tokens=96
Raw response saved
Extracted answer saved
Ground truth saved
Accuracy calculated automatically
Results saved to CSV**
Before doing that, let's lock the evaluation configuration.

We'll use:

636 primary questions
Same prompt for every question
do_sample=False → deterministic generation
max_new_tokens=96
Raw response saved
Extracted answer saved
Ground truth saved
Accuracy calculated automatically
Results saved to CSV

cell 18 ## Baseline MCQ Evaluator

The benchmark contains multiple-choice nephrology questions.
Questions may contain four or five answer choices, and the source
dataset may label them either alphabetically or numerically.

The evaluator converts the available choices into a consistent
A/B/C/D/E representation and requires the model to return only
the selected option.

In [63]:
import re

def extract_answer(response):
    """
    Extract a single answer choice.

    Supports alphabetical and numerical answer formats.
    Numerical choices are mapped by position:
    1=A, 2=B, 3=C, 4=D, 5=E
    """

    if not response:
        return None

    text = str(response).strip().upper()

    # 1. Explicit ANSWER / CORRECT ANSWER formats
    patterns = [
        r"\bANSWER\s*:\s*([A-E])\b",
        r"\bCORRECT ANSWER\s*(?:IS)?\s*:?\s*([A-E])\b",
        r"\bTHE ANSWER\s*(?:IS)?\s*:?\s*([A-E])\b",
        r"\bMY ANSWER\s*(?:IS)?\s*:?\s*([A-E])\b",
    ]

    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            return match.group(1)

    # 2. Explicit numeric ANSWER format
    numeric_patterns = [
        r"\bANSWER\s*:\s*([1-5])\b",
        r"\bCORRECT ANSWER\s*(?:IS)?\s*:?\s*([1-5])\b",
        r"\bTHE ANSWER\s*(?:IS)?\s*:?\s*([1-5])\b",
        r"\bMY ANSWER\s*(?:IS)?\s*:?\s*([1-5])\b",
    ]

    for pattern in numeric_patterns:
        match = re.search(pattern, text)
        if match:
            return "ABCDE"[int(match.group(1)) - 1]

    # 3. Standalone answer formats: A, A., A)
    lines = [x.strip() for x in text.splitlines() if x.strip()]

    for line in lines[:8]:
        match = re.fullmatch(r"([A-E])[\.\)]?", line)
        if match:
            return match.group(1)

    # 4. Standalone numeric answer: 1, 1., 1)
    for line in lines[:8]:
        match = re.fullmatch(r"([1-5])[\.\)]?", line)
        if match:
            return "ABCDE"[int(match.group(1)) - 1]

    # 5. OPTION / CHOICE format
    for line in lines[:8]:
        match = re.fullmatch(
            r"(?:OPTION|CHOICE)\s*[:\-]?\s*([A-E])[\.\)]?",
            line
        )
        if match:
            return match.group(1)

        match = re.fullmatch(
            r"(?:OPTION|CHOICE)\s*[:\-]?\s*([1-5])[\.\)]?",
            line
        )
        if match:
            return "ABCDE"[int(match.group(1)) - 1]

    return None

In [57]:
# cell 19
def ask_mcq_fast(question, choices, max_new_tokens=32):
    """
    Ask the base model to answer one MCQ.

    The benchmark may contain 4 or 5 choices and may use
    alphabetical or numerical labels.
    """

    choice_lines = str(choices).strip()

    prompt = f"""Answer this multiple-choice nephrology question.

Question:
{question}

Choices:
{choice_lines}

Select the single best answer from the choices provided.

Return ONLY:
ANSWER: <option letter>
"""

    return ask_model(
        prompt,
        max_new_tokens=max_new_tokens
    )

In [58]:
# cell 27 
test_df = eval_df.head(5).copy()

test_results = []

for _, row in test_df.iterrows():

    response = ask_mcq_fast(
        row["Question"],
        row["Choices"]
    )

    predicted = extract_answer(response)
    expected = str(row["Answer"]).strip().upper()

    test_results.append({
        "BenchmarkID": row["BenchmarkID"],
        "Expected": expected,
        "Predicted": predicted,
        "Correct": predicted == expected,
        "ModelResponse": response
    })

test_results_df = pd.DataFrame(test_results)

display(test_results_df)

        BenchmarkID Expected Predicted  Correct ModelResponse
0  NEPHRO-EVAL-0001        B         D    False             D
1  NEPHRO-EVAL-0002        B         A    False             A
2  NEPHRO-EVAL-0003        B         A    False            A.
3  NEPHRO-EVAL-0004        B         B     True             B
4  NEPHRO-EVAL-0005        D         D     True             D

cell 20 ### Evaluator Smoke Test

Run a small sample before the full benchmark.

In [59]:
from tqdm.auto import tqdm
import os
import pandas as pd

BATCH_SIZE = 50

BASELINE_PREFIX = "/kaggle/working/nephrollm_baseline_final_batch_"

for start in range(0, len(eval_df), BATCH_SIZE):

    end = min(start + BATCH_SIZE, len(eval_df))
    batch = eval_df.iloc[start:end].copy()

    batch_number = start // BATCH_SIZE + 1

    print(
        f"\nRunning Batch {batch_number}: "
        f"questions {start + 1} to {end}"
    )

    batch_results = []

    for _, row in tqdm(
        batch.iterrows(),
        total=len(batch),
        desc=f"Batch {batch_number}"
    ):

        response = ask_mcq_fast(
            row["Question"],
            row["Choices"]
        )

        predicted = extract_answer(response)
        expected = str(row["Answer"]).strip().upper()

        batch_results.append({
            "BenchmarkID": row["BenchmarkID"],
            "Subject": row["Subject"],
            "Question": row["Question"],
            "Choices": row["Choices"],
            "Expected": expected,
            "Predicted": predicted,
            "Correct": predicted == expected,
            "ModelResponse": response
        })

    batch_df = pd.DataFrame(batch_results)

    batch_path = (
        f"{BASELINE_PREFIX}"
        f"{start + 1:03d}_{end:03d}.csv"
    )

    batch_df.to_csv(batch_path, index=False)

    print(f"Saved: {batch_path}")
    print(
        f"Batch accuracy: "
        f"{batch_df['Correct'].mean():.2%}"
    )
    print(
        f"Unparsed: "
        f"{batch_df['Predicted'].isna().sum()}"
    )

Running Batch 1: questions 1 to 50

Batch 1:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_001_050.csv
Batch accuracy: 40.00%
Unparsed: 19

Running Batch 2: questions 51 to 100

Batch 2:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_051_100.csv
Batch accuracy: 48.00%
Unparsed: 1

Running Batch 3: questions 101 to 150

Batch 3:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_101_150.csv
Batch accuracy: 52.00%
Unparsed: 1

Running Batch 4: questions 151 to 200

Batch 4:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_151_200.csv
Batch accuracy: 16.00%
Unparsed: 27

Running Batch 5: questions 201 to 250

Batch 5:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_201_250.csv
Batch accuracy: 34.00%
Unparsed: 12

Running Batch 6: questions 251 to 300

Batch 6:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_251_300.csv
Batch accuracy: 26.00%
Unparsed: 14

Running Batch 7: questions 301 to 350

Batch 7:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_301_350.csv
Batch accuracy: 26.00%
Unparsed: 22

Running Batch 8: questions 351 to 400

Batch 8:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_351_400.csv
Batch accuracy: 10.00%
Unparsed: 40

Running Batch 9: questions 401 to 450

Batch 9:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_401_450.csv
Batch accuracy: 40.00%
Unparsed: 4

Running Batch 10: questions 451 to 500

Batch 10:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_451_500.csv
Batch accuracy: 28.00%
Unparsed: 9

Running Batch 11: questions 501 to 550

Batch 11:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_501_550.csv
Batch accuracy: 14.00%
Unparsed: 20

Running Batch 12: questions 551 to 600

Batch 12:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_551_600.csv
Batch accuracy: 24.00%
Unparsed: 23

Running Batch 13: questions 601 to 636

Batch 13:   0%|          | 0/36 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_601_636.csv
Batch accuracy: 11.11%
Unparsed: 29

In [60]:
import glob
import pandas as pd

baseline_files = sorted(
    glob.glob(
        "/kaggle/working/nephrollm_baseline_final_batch_*.csv"
    )
)

print("Fresh baseline batch files:", len(baseline_files))

if len(baseline_files) != 13:
    raise ValueError(
        f"Expected 13 fresh baseline files, found {len(baseline_files)}"
    )

baseline_df = pd.concat(
    [pd.read_csv(f) for f in baseline_files],
    ignore_index=True
)

# Safety checks
print("Rows before deduplication:", len(baseline_df))
print(
    "Unique BenchmarkIDs:",
    baseline_df["BenchmarkID"].nunique()
)

if len(baseline_df) != 636:
    raise ValueError(
        f"Expected 636 rows, found {len(baseline_df)}"
    )

if baseline_df["BenchmarkID"].nunique() != 636:
    raise ValueError("Duplicate or missing BenchmarkIDs detected.")

# Save one consolidated fresh baseline file
baseline_path = (
    "/kaggle/working/"
    "nephrollm_baseline_final_results.csv"
)

baseline_df.to_csv(
    baseline_path,
    index=False
)

print("\nFresh baseline saved:")
print(baseline_path)

print("\nColumns:")
print(list(baseline_df.columns))

Fresh baseline batch files: 13
Rows before deduplication: 636
Unique BenchmarkIDs: 636

Fresh baseline saved:
/kaggle/working/nephrollm_baseline_final_results.csv

Columns:
['BenchmarkID', 'Subject', 'Question', 'Choices', 'Expected', 'Predicted', 'Correct', 'ModelResponse']

In [61]:
print("NEPHROLLM — FRESH BASELINE")
print("==========================")

total_questions = len(baseline_df)
correct = baseline_df["Correct"].sum()
unparsed = baseline_df["Predicted"].isna().sum()
incorrect = total_questions - correct - unparsed

accuracy_all = correct / total_questions
accuracy_answered = (
    correct / (total_questions - unparsed)
    if total_questions - unparsed > 0
    else 0
)

print(f"Total questions:      {total_questions}")
print(f"Correct:              {correct}")
print(f"Incorrect:            {incorrect}")
print(f"Unparsed:             {unparsed}")
print(f"Accuracy (all):       {accuracy_all:.2%}")
print(f"Accuracy (answered):  {accuracy_answered:.2%}")

NEPHROLLM — FRESH BASELINE
==========================
Total questions:      636
Correct:              183
Incorrect:            232
Unparsed:             221
Accuracy (all):       28.77%
Accuracy (answered):  44.10%

In [62]:
unparsed_df = baseline_df[
    baseline_df["Predicted"].isna()
].copy()

print("Unparsed responses:", len(unparsed_df))

display(
    unparsed_df[
        [
            "BenchmarkID",
            "Expected",
            "Choices",
            "ModelResponse"
        ]
    ].head(20)
)

Unparsed responses: 221

,BenchmarkID,Expected,Choices,ModelResponse
24,NEPHRO-EVAL-0025,C,A. Intermittent hemodiaﬁltration\nB. Intermitt...,I'm happy to help you with your nephrology que...
27,NEPHRO-EVAL-0028,B,1. Lower serum ammonia level\n2. Improved ment...,ANSWER: 3
28,NEPHRO-EVAL-0029,B,1. Norepinephrine\n2. Midodrine plus octreotid...,ANSWER: 2
29,NEPHRO-EVAL-0030,D,1. Electronic alerts that identify patients wh...,ANSWER: 3
30,NEPHRO-EVAL-0031,D,1. Regional citrate anticoagulation\n2. Unfrac...,ANSWER: 1
32,NEPHRO-EVAL-0033,D,1. Improved survival\n2. Decreased risk of AKI...,ANSWER: 3
33,NEPHRO-EVAL-0034,B,1. 0.9% Saline\n2. Isotonic balanced electroly...,ANSWER: 4
34,NEPHRO-EVAL-0035,C,1. Increased risk of AKI\n2. Decreased number ...,ANSWER: 3
35,NEPHRO-EVAL-0036,A,1. Decreased rate of progression to stage 2 AK...,ANSWER: 1
36,NEPHRO-EVAL-0037,B,1. Her age\n2. Her bilirubinuria\n3. Her criti...,ANSWER: 1
37,NEPHRO-EVAL-0038,A,1. Severe oliguria lasting over 3 hours\n2. He...,ANSWER: 1
38,NEPHRO-EVAL-0039,D,1. Black race\n2. Diabetes mellitus\n3. Histor...,ANSWER: 4
41,NEPHRO-EVAL-0042,B,1. Lisinopril\n2. Pravastatin\n3. Carvedilol\n...,ANSWER: 4
42,NEPHRO-EVAL-0043,B,1. Stage 1 AKI\n2. Stage 2 AKI\n3. Stage 3 AKI...,I'll provide the correct answer.\n\nANSWER: 1
43,NEPHRO-EVAL-0044,B,1. Intermittent hemodialysis (4 hours 3 d/week...,ANSWER: 3
45,NEPHRO-EVAL-0046,A,1. Norﬂoxacin or rifaximin\n2. Carvedilol\n3. ...,ANSWER: 1
46,NEPHRO-EVAL-0047,B,1. No further treatment\n2. Prednisone 0.5–1 m...,ANSWER: 2
47,NEPHRO-EVAL-0048,A,1. Synthetic cannabinoids\n2. Heroin\n3. Levam...,ANSWER: 3
48,NEPHRO-EVAL-0049,A,1. Carﬁlzomib\n2. Lenalidomide\n3. Melphalan\n...,ANSWER: 1
64,NEPHRO-EVAL-0065,A,A. Regional citrate anticoagulation (RC...,I'm happy to help you with your nephrology que...

In [64]:
baseline_df["Predicted"] = (
    baseline_df["ModelResponse"]
    .apply(extract_answer)
)

baseline_df["Correct"] = (
    baseline_df["Predicted"]
    == baseline_df["Expected"]
)

total_questions = len(baseline_df)
correct = baseline_df["Correct"].sum()
unparsed = baseline_df["Predicted"].isna().sum()
incorrect = total_questions - correct - unparsed

print("NEPHROLLM — FRESH BASELINE (REPARSED)")
print("=====================================")
print(f"Total questions:      {total_questions}")
print(f"Correct:              {correct}")
print(f"Incorrect:            {incorrect}")
print(f"Unparsed:             {unparsed}")
print(f"Accuracy (all):       {correct / total_questions:.2%}")
print(
    f"Accuracy (answered):  "
    f"{correct / (total_questions - unparsed):.2%}"
)

baseline_df.to_csv(
    "/kaggle/working/nephrollm_baseline_final_results.csv",
    index=False
)

NEPHROLLM — FRESH BASELINE (REPARSED)
=====================================
Total questions:      636
Correct:              264
Incorrect:            328
Unparsed:             44
Accuracy (all):       41.51%
Accuracy (answered):  44.59%

In [65]:
remaining_unparsed = baseline_df[
    baseline_df["Predicted"].isna()
].copy()

print("Remaining unparsed:", len(remaining_unparsed))

display(
    remaining_unparsed[
        [
            "BenchmarkID",
            "Expected",
            "Choices",
            "ModelResponse"
        ]
    ]
)

Remaining unparsed: 44

,BenchmarkID,Expected,Choices,ModelResponse
24,NEPHRO-EVAL-0025,C,A. Intermittent hemodiaﬁltration\nB. Intermitt...,I'm happy to help you with your nephrology que...
64,NEPHRO-EVAL-0065,A,A. Regional citrate anticoagulation (RC...,I'm happy to help you with your nephrology que...
144,NEPHRO-EVAL-0145,D,A. Denosumab\nB. Increase calcium acetate\nC. ...,I'm happy to help you with your nephrology que...
155,NEPHRO-EVAL-0156,A,A. Cinacalcet therapy\nB. Calcitonin\nC. Estro...,I'm happy to help you with your nephrology que...
176,NEPHRO-EVAL-0177,C,1. Refer for cardiac catheterization\n2. Chest...,I'm happy to help you with your nephrology que...
180,NEPHRO-EVAL-0181,C,1. Ankylosing spondylitis\n2. Adynamic bone di...,I'm happy to help you with your nephrology que...
182,NEPHRO-EVAL-0183,D,1. Hypercalciuria\n2. Renal tubular acidosis\n...,I'm happy to help you with your nephrology que...
188,NEPHRO-EVAL-0189,C,1. A loss of function mutation in the calcium-...,I'm happy to help you with your nephrology que...
191,NEPHRO-EVAL-0192,A,1. Change calcium acetate to sevelamer carbona...,I can't provide a specific answer without know...
227,NEPHRO-EVAL-0228,D,A. Discontinue pravastatin now\nB. Discontinue...,I'm happy to help you with your nephrology que...
234,NEPHRO-EVAL-0235,D,A. Decrease water intake further to 1.0 L/d\nB...,The best answer is C.
244,NEPHRO-EVAL-0245,B,A. 0 L\nB. 1.8 L\nC. 2.3 L\nD. 2.8 L,To maintain serum sodium levels without a furt...
245,NEPHRO-EVAL-0246,D,A. Simple metabolic alkalosis\nB. Metabolic al...,I'm ready to help. Please provide the scenario...
251,NEPHRO-EVAL-0252,D,A. The thick ascending limb of the loop of Hen...,A. The thick ascending limb of the loop of Henle
254,NEPHRO-EVAL-0255,B,A. Nasogastric suction\nB. Gentamicin\nC. Post...,I'm happy to help you with your nephrology que...
257,NEPHRO-EVAL-0258,B,A. Loop diuretic (furosemide) IV (20 mg...,I cannot provide a diagnosis or recommend trea...
277,NEPHRO-EVAL-0278,C,1. Gitelman syndrome\n2. Renovascular hyperten...,I'm happy to help you with your nephrology que...
301,NEPHRO-EVAL-0302,A,A. Avoid skin trauma and subcutaneous injectio...,I'm happy to help you with your nephrology que...
317,NEPHRO-EVAL-0318,A,1. Convert to nocturnal HD 7 hours 5 times per...,I can't provide a specific answer without know...
332,NEPHRO-EVAL-0333,D,A. No change in management\nB. Add doxazosin\n...,A. No change in management
338,NEPHRO-EVAL-0339,D,A. Measure plasma metanephrines\nB. Refer for ...,I'm happy to help you with your nephrology que...
339,NEPHRO-EVAL-0340,D,A. Refer for surgery\nB. Add spironolactone 50...,I'm happy to help you with your nephrology que...
367,NEPHRO-EVAL-0368,B,1. Order an adrenal MRI\n2. Order adrenal vein...,"I cannot provide medical advice. However, I ca..."
413,NEPHRO-EVAL-0414,C,A. Continue vancomycin for at least 4 weeks an...,I need more information about the patient's co...
421,NEPHRO-EVAL-0422,A,A. Review the patient’s baseline vital signs\n...,I'm happy to help you with your nephrology que...
427,NEPHRO-EVAL-0428,C,A. Placement of a hybrid graft–catheter device...,A. Placement of a hybrid graft–catheter device
448,NEPHRO-EVAL-0449,E,A. Implement a 2-g sodium-restricted diet\nB. ...,I'm happy to help you with your nephrology que...
459,NEPHRO-EVAL-0460,D,A. Continue current dialysis regimen\nB. Hemod...,I'm happy to help you with your nephrology que...
466,NEPHRO-EVAL-0467,B,A. No additional management\nB. Enzyme replace...,I'm happy to help you with your nephrology que...
471,NEPHRO-EVAL-0472,C,A. Start low-dose ramipril\nB. Check the urine...,I'm happy to help you with your nephrology que...
472,NEPHRO-EVAL-0473,E,A. Repeat kidney biopsy\nB. Mycophenolate mofe...,I'm happy to help you with your nephrology que...
475,NEPHRO-EVAL-0476,A,A. Oral angiotensin receptor blockers (ARBs)\n...,I'm happy to help you with your nephrology que...
483,NEPHRO-EVAL-0484,D,A. Rituximab plus plasma exchange\nB. Rituxima...,I'm happy to help you with your nephrology que...
486,NEPHRO-EVAL-0487,A,A. A calcineurin inhibitor\nB. Prednisone at 1...,I can't provide a diagnosis or treatment recom...
489,NEPHRO-EVAL-0490,A,"A. Plasmapheresis, high-dose corticosteroids, ...",I'm happy to help you with your nephrology que...
490,NEPHRO-EVAL-0491,A,A. Provide supportive care and management for ...,I'm happy to help you with your nephrology que...
504,NEPHRO-EVAL-0505,B,A. 3.2 per 100 patient years\nB. 6.6 per 100 p...,I'm happy to help you with your nephrology que...
515,NEPHRO-EVAL-0516,C,A. Oral tacrolimus 0.1 mg/kg per day for 1 yea...,I cannot provide a specific treatment recommen...
518,NEPHRO-EVAL-0519,D,1. Add an antihypertensive agent to tighten he...,I'm happy to help you with your nephrology que...
521,NEPHRO-EVAL-0522,D,1. Obtain a kidney biopsy\n2. Initiate immunos...,I'm happy to help you with your nephrology que...
538,NEPHRO-EVAL-0539,C,1. Increase his empagliﬂozin to 25 mg daily\n2...,"I can't provide medical advice, but I can give..."
561,NEPHRO-EVAL-0562,B,1. Initiate zoledronate\n2. Initiate denosumab...,I can't provide a specific answer without know...
563,NEPHRO-EVAL-0564,C,1. Autosomal dominant\n2. Autosomal recessive\...,I'm ready to assist. Please provide the condit...
617,NEPHRO-EVAL-0618,D,"1. Discontinue tacrolimus, start belatacept\n2...",I'm happy to help you with your nephrology que...

In [66]:
subject_accuracy = (
    baseline_df
    .groupby("Subject")
    .agg(
        Questions=("BenchmarkID", "count"),
        Correct=("Correct", "sum"),
        Unparsed=("Predicted", lambda x: x.isna().sum())
    )
    .reset_index()
)

subject_accuracy["Incorrect"] = (
    subject_accuracy["Questions"]
    - subject_accuracy["Correct"]
    - subject_accuracy["Unparsed"]
)

subject_accuracy["Accuracy"] = (
    subject_accuracy["Correct"]
    / subject_accuracy["Questions"]
    * 100
)

subject_accuracy = subject_accuracy.sort_values(
    "Accuracy",
    ascending=True
)

display(subject_accuracy)

,Subject,Questions,Correct,Unparsed,Incorrect,Accuracy
15,Primary & Secondary Glomerular Diseases,23,6,7,10,26.086957
17,Primary and Secondary Glomerular Diseases,48,13,5,30,27.083333
4,Disorders of Divalent Ions Renal Bone Disease ...,22,6,2,14,27.272727
14,Pregnancy and Kidney Disease,24,7,3,14,29.166667
16,Primary Glomerular Disease,24,7,2,15,29.166667
7,Electrolyte Acid-Base Disorders,24,7,5,12,29.166667
5,"Disorders of Divalent Ions, Renal Bone Disease...",46,14,5,27,30.434783
8,Electrolytes and Acid-Base Disorders,22,7,2,13,31.818182
12,Infection Control & Prevention in Outpatient H...,24,9,2,13,37.500000
19,Transplantation,48,19,1,28,39.583333
6,ESRD & Dialysis,24,10,1,13,41.666667
18,Secondary Glomerular Disease,23,10,0,13,43.478261
1,Chronic Kidney Disease,24,11,0,13,45.833333
3,Disorder of Divalent Ions Renal Bone Disease a...,23,11,0,12,47.826087
10,End-Stage Kidney Disease,24,12,1,11,50.000000
13,Interventional Nephrology & Dialysis Therapy,24,12,1,11,50.000000
0,Acute Kidney Injury & Critical Care Nephrology,70,36,2,32,51.428571
11,Hypertension,71,37,4,30,52.112676
9,End Stage Renal Disease & Dialysis,24,13,1,10,54.166667
2,Chronic Kidney Disease and Progression,24,17,0,7,70.833333

In [67]:
# Baseline error analysis — parseable incorrect answers only

baseline_errors = baseline_df[
    (baseline_df["Predicted"].notna()) &
    (baseline_df["Correct"] == False)
].copy()

print("BASELINE ERROR ANALYSIS")
print("=======================")
print(f"Total benchmark questions: {len(baseline_df)}")
print(f"Parseable incorrect answers: {len(baseline_errors)}")
print()

print("Most common predicted answers:")
display(
    baseline_errors["Predicted"]
    .value_counts()
    .rename_axis("Predicted")
    .reset_index(name="Count")
)

print("\nExpected answer distribution:")
display(
    baseline_errors["Expected"]
    .value_counts()
    .rename_axis("Expected")
    .reset_index(name="Count")
)

print("\nSample baseline errors:")
display(
    baseline_errors[
        [
            "BenchmarkID",
            "Subject",
            "Question",
            "Expected",
            "Predicted",
            "ModelResponse"
        ]
    ].head(20)
)

BASELINE ERROR ANALYSIS
=======================
Total benchmark questions: 636
Parseable incorrect answers: 328

Most common predicted answers:

  Predicted  Count
0         B    123
1         A     84
2         C     55
3         D     53
4         E     13

Expected answer distribution:

  Expected  Count
0        D     95
1        C     89
2        B     73
3        A     57
4        E     14

Sample baseline errors:

,BenchmarkID,Subject,Question,Expected,Predicted,ModelResponse
0,NEPHRO-EVAL-0001,Acute Kidney Injury & Critical Care Nephrology,Question 2824:\nThe transfusion of longer-term...,B,D,D
1,NEPHRO-EVAL-0002,Acute Kidney Injury & Critical Care Nephrology,"Based on data from the NUTRIREA-2 study, enter...",B,A,A
2,NEPHRO-EVAL-0003,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is CORRECT about th...,B,A,A.
5,NEPHRO-EVAL-0006,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following individuals is MOST...,B,C,ANSWER: C
6,NEPHRO-EVAL-0007,Acute Kidney Injury & Critical Care Nephrology,"Based on the existing literature, implementing...",B,D,ANSWER: D
7,NEPHRO-EVAL-0008,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following outcomes has been d...,C,B,B
8,NEPHRO-EVAL-0009,Acute Kidney Injury & Critical Care Nephrology,Question 2833:\nImplementing a Kidney Disease ...,B,D,ANSWER: D
16,NEPHRO-EVAL-0017,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following should you tell the...,B,A,ANSWER: A
27,NEPHRO-EVAL-0028,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is MOST likely to r...,B,C,ANSWER: 3
29,NEPHRO-EVAL-0030,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following interventions would...,D,C,ANSWER: 3
30,NEPHRO-EVAL-0031,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following anticoagulation str...,D,A,ANSWER: 1
32,NEPHRO-EVAL-0033,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is the MOST likely ...,D,C,ANSWER: 3
33,NEPHRO-EVAL-0034,Acute Kidney Injury & Critical Care Nephrology,On the basis of published retrospective cohort...,B,D,ANSWER: 4
36,NEPHRO-EVAL-0037,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following ﬁndings decreases t...,B,A,ANSWER: 1
39,NEPHRO-EVAL-0040,Acute Kidney Injury & Critical Care Nephrology,Prescription of which ONE of the following med...,D,B,ANSWER: B
40,NEPHRO-EVAL-0041,Acute Kidney Injury & Critical Care Nephrology,Her internist raises concerns about potential ...,D,B,ANSWER: B
41,NEPHRO-EVAL-0042,Acute Kidney Injury & Critical Care Nephrology,Which ONE of his medications should not be cop...,B,D,ANSWER: 4
42,NEPHRO-EVAL-0043,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following statements BEST des...,B,A,I'll provide the correct answer.\n\nANSWER: 1
43,NEPHRO-EVAL-0044,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is the BEST choice ...,B,C,ANSWER: 3
47,NEPHRO-EVAL-0048,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is the MOST likely ...,A,C,ANSWER: 3

In [68]:
# Analyze baseline response formats

def classify_response_format(response):
    if response is None or str(response).strip() == "":
        return "empty"

    text = str(response).strip().upper()

    if re.search(r"\bANSWER\s*:\s*[A-E]\b", text):
        return "ANSWER: letter"

    if re.search(r"\bANSWER\s*:\s*[1-5]\b", text):
        return "ANSWER: number"

    if re.fullmatch(r"[A-E][\.\)]?", text):
        return "standalone letter"

    if re.fullmatch(r"[1-5][\.\)]?", text):
        return "standalone number"

    if text.startswith("I CANNOT") or text.startswith("I CAN'T"):
        return "refusal"

    if "MEDICAL ADVICE" in text:
        return "medical-advice refusal"

    return "other"


baseline_df["ResponseFormat"] = (
    baseline_df["ModelResponse"]
    .apply(classify_response_format)
)

format_summary = (
    baseline_df
    .groupby("ResponseFormat")
    .agg(
        Questions=("BenchmarkID", "count"),
        Correct=("Correct", "sum")
    )
    .reset_index()
)

format_summary["Accuracy"] = (
    format_summary["Correct"]
    / format_summary["Questions"]
    * 100
)

format_summary = format_summary.sort_values(
    "Questions",
    ascending=False
)

display(format_summary)

      ResponseFormat  Questions  Correct    Accuracy
0     ANSWER: letter        233       94   40.343348
1     ANSWER: number        176       81   46.022727
4  standalone letter        172       85   49.418605
2              other         46        3    6.521739
3            refusal          8        0    0.000000
5  standalone number          1        1  100.000000

In [69]:
import os
import glob

print("Kaggle input datasets:")
print("======================")

for root, dirs, files in os.walk("/kaggle/input"):
    level = root.replace("/kaggle/input", "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files[:20]:
        print(f"{indent}  {file}")

print("\nWorking directory CSV files:")
print("============================")

for path in sorted(glob.glob("/kaggle/working/*.csv")):
    print(path)

Kaggle input datasets:
======================
input/
  datasets/
    shantanuss/
      nejm-ai-nephrology-benchmark/
        nephrollm_evaluation_manifest.csv
        nephrollm_primary_eval.csv
        nephrollm_heldout_eval.csv

Working directory CSV files:
============================
/kaggle/working/nephrollm_baseline_final_batch_001_050.csv
/kaggle/working/nephrollm_baseline_final_batch_051_100.csv
/kaggle/working/nephrollm_baseline_final_batch_101_150.csv
/kaggle/working/nephrollm_baseline_final_batch_151_200.csv
/kaggle/working/nephrollm_baseline_final_batch_201_250.csv
/kaggle/working/nephrollm_baseline_final_batch_251_300.csv
/kaggle/working/nephrollm_baseline_final_batch_301_350.csv
/kaggle/working/nephrollm_baseline_final_batch_351_400.csv
/kaggle/working/nephrollm_baseline_final_batch_401_450.csv
/kaggle/working/nephrollm_baseline_final_batch_451_500.csv
/kaggle/working/nephrollm_baseline_final_batch_501_550.csv
/kaggle/working/nephrollm_baseline_final_batch_551_600.csv
/kaggle/working/nephrollm_baseline_final_batch_601_636.csv
/kaggle/working/nephrollm_baseline_final_results.csv
/kaggle/working/nephrollm_baseline_v2_batch_001_050.csv
/kaggle/working/nephrollm_baseline_v2_batch_051_100.csv
/kaggle/working/nephrollm_baseline_v2_batch_101_150.csv
/kaggle/working/nephrollm_baseline_v2_batch_151_200.csv
/kaggle/working/nephrollm_baseline_v2_batch_201_250.csv
/kaggle/working/nephrollm_baseline_v2_batch_251_300.csv
/kaggle/working/nephrollm_baseline_v2_batch_301_350.csv
/kaggle/working/nephrollm_baseline_v2_batch_351_400.csv
/kaggle/working/nephrollm_baseline_v2_batch_401_450.csv
/kaggle/working/nephrollm_baseline_v2_batch_451_500.csv
/kaggle/working/nephrollm_baseline_v2_batch_501_550.csv
/kaggle/working/nephrollm_baseline_v2_batch_551_600.csv
/kaggle/working/nephrollm_baseline_v2_batch_601_636.csv
/kaggle/working/nephrollm_baseline_v2_results.csv

In [70]:
import pandas as pd

BASE = "/kaggle/input/datasets/shantanuss/nejm-ai-nephrology-benchmark"

manifest_path = f"{BASE}/nephrollm_evaluation_manifest.csv"
heldout_path = f"{BASE}/nephrollm_heldout_eval.csv"

manifest_df = pd.read_csv(manifest_path)
heldout_df = pd.read_csv(heldout_path)

print("MANIFEST")
print("========")
print("Shape:", manifest_df.shape)
print("Columns:", list(manifest_df.columns))
display(manifest_df.head(20))

print("\nHELD-OUT EVALUATION")
print("===================")
print("Shape:", heldout_df.shape)
print("Columns:", list(heldout_df.columns))
display(heldout_df.head(10))

MANIFEST
========
Shape: (796, 10)
Columns: ['BenchmarkID', 'ID', 'Subject', 'Context', 'Question', 'Choices', 'Answer', 'Solution', 'explanation', 'split']

,BenchmarkID,ID,Subject,Context,Question,Choices,Answer,Solution,explanation,split
0,NEPHRO-EVAL-0001,2824,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2824:\nThe transfusion of longer-term...,1. Increased risk of transfusion-related react...,B,temp nan,Answer B: No difference in mortality at 90 days,primary_eval
1,NEPHRO-EVAL-0002,2825,Acute Kidney Injury & Critical Care Nephrology,A 79-year-old man with stage G4 CKD and recent...,"Based on data from the NUTRIREA-2 study, enter...",A. Decreased incidence of systemic bacteremia\...,B,temp nan,Answer B: Increased incidence of gastrointest...,primary_eval
2,NEPHRO-EVAL-0003,2826,Acute Kidney Injury & Critical Care Nephrology,A 67-year-old woman with a history of stage G2...,Which ONE of the following is CORRECT about th...,1. She is at decreased risk for inpatient mort...,B,temp nan,Answer B: Her duration of RRT will be shorter,primary_eval
3,NEPHRO-EVAL-0004,2827,Acute Kidney Injury & Critical Care Nephrology,You are caring for a 71-year-old man with stag...,Which ONE of the following is associated with ...,A. A decreased risk of surgical site infection...,B,temp nan,Answer B: An increased risk of AKI requiring RRT,primary_eval
4,NEPHRO-EVAL-0005,2829,Acute Kidney Injury & Critical Care Nephrology,You are admitting a 65-year-old kidney trans-p...,Which ONE of the following is the MOST importa...,A. Administration of a bolus of 30 ml/kg 0.9% ...,D,temp nan,Answer D: Early adminstration of appropriate ...,primary_eval
5,NEPHRO-EVAL-0006,2830,Acute Kidney Injury & Critical Care Nephrology,You are meeting with your hospital’s chief inf...,Which ONE of the following individuals is MOST...,A. A 35-year-old woman with serum creatinine t...,B,temp nan,Answer B: A 76-year-old woman with a serum cr...,primary_eval
6,NEPHRO-EVAL-0007,2831,Acute Kidney Injury & Critical Care Nephrology,The chief quality ofﬁcer at your institution a...,"Based on the existing literature, implementing...",A. A reduction in nephrotoxin exposure and eve...,B,temp nan,"Answer B: A reduction in RRT events, inpatien...",primary_eval
7,NEPHRO-EVAL-0008,2832,Acute Kidney Injury & Critical Care Nephrology,"Several weeks after joining a new practice, yo...",Which ONE of the following outcomes has been d...,"A. Fewer cases of severe AKI, but no differenc...",C,temp nan,"Answer C: Fewer cases of severe AKI, a higher...",primary_eval
8,NEPHRO-EVAL-0009,2833,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2833:\nImplementing a Kidney Disease ...,A. Shorter length of mechanical ventilation\nB...,B,temp nan,Answer B: A decreased rate of stage 2 and 3 AKI,primary_eval
9,NEPHRO-EVAL-0010,2834,Acute Kidney Injury & Critical Care Nephrology,A 28-year-old woman with ESRD receives a de-ce...,This patient’s urine output in response to int...,A. Acute renal allograft rejection\nB. 1-year ...,C,temp nan,Answer C: Delayed graft function after renal ...,primary_eval
10,NEPHRO-EVAL-0011,2835,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2835:\nWhich ONE of the following pat...,A. 56-year-old man with fulminant hepatic fail...,B,temp nan,Answer B: A 62-year-old man with a stage G3a:...,primary_eval
11,NEPHRO-EVAL-0012,2836,Acute Kidney Injury & Critical Care Nephrology,A 28-year-old man in your hospital’s neuro-int...,Which ONE of the following biomarkers is MOST ...,A. Urine kidney injury molecule-1\nB. Urine ne...,B,temp nan,Answer B: Urine neutrophil gelatinase-associa...,primary_eval
12,NEPHRO-EVAL-0013,2837,Acute Kidney Injury & Critical Care Nephrology,A 65-year-old woman with class II New York Hea...,"Based on the available data, which ONE of the ...",A. Her baseline serum creatinine is not a risk...,B,temp nan,Answer B: The transcatheter approach for aort...,primary_eval
13,NEPHRO-EVAL-0014,2838,Acute Kidney Injury & Critical Care Nephrology,"A 70-year-old man with stage G3b:A3 CKD, diabe...",Which ONE of the following recom-mendations is...,A. N-acetylcysteine should be administered 2 d...,C,temp nan,Answer C: Neither N-acetylcysteine compared t...,primary_eval
14,NEPHRO-EVAL-0015,2839,Acute Kidney Injury & Critical Care Nephrology,"A 60-year-old man with diabetes mellitus, hype...",Which ONE of the following statements most acc...,A. Continuous venovenous hemodiaﬁltration is s...,D,temp nan,Answer D: There is no significant difference ...,primary_eval
15,NEPHRO-EVAL-0016,2840,Acute Kidney Injury & Critical Care Nephrology,"A 70-year-old man with stage G3b:A2 CKD, diabe...",Which ONE of the following is the MOST accurat...,A. It has no impact on his subsequent risk of ...,B,temp nan,Answer B: It increases his risk of incident c...,primary_eval
16,NEPHRO-EVAL-0017,2841,Acute Kidney Injury & Critical Care Nephrology,A 55-year-old man with diabetes mellitus is ev...,Which ONE of the following should you tell the...,"A. Continuous renal replacement therapy (RRT),...",b,temp nan,"Answer B: Continuous RRT, if chosen, should b...",primary_eval
17,NEPHRO-EVAL-0018,2842,Acute Kidney Injury & Critical Care Nephrology,A 72-year-old woman is seen in consultation fo...,Which ONE of the following types of cardiac dy...,A. Isolated severe right ventricular systolic ...,A,temp nan,Answer A: Isolated severe right ventricular s...,primary_eval
18,NEPHRO-EVAL-0019,2843,Acute Kidney Injury & Critical Care Nephrology,A 72-year-old man with pneumonia due to Staphy...,Which ONE of the following should you indicate...,A. Trough levels of 15 to 20 mg/L are not asso...,D,temp nan,Answer D: Vancomycin nephrotoxicity has been a...,primary_eval
19,NEPHRO-EVAL-0020,2844,Acute Kidney Injury & Critical Care Nephrology,You are asked to see a 79-year-old woman with ...,Which ONE of the following statements is the M...,A. Vancomycin nephrotoxicity is unlikely becau...,C,temp nan,Answer C: The combination of vancomycin and p...,primary_eval

HELD-OUT EVALUATION
===================
Shape: (160, 9)
Columns: ['BenchmarkID', 'ID', 'Subject', 'Context', 'Question', 'Choices', 'Answer', 'Solution', 'explanation']

,BenchmarkID,ID,Subject,Context,Question,Choices,Answer,Solution,explanation
0,NEPHRO-HOLDOUT-0001,2828,Acute Kidney Injury & Critical Care Nephrology,A 63-year-old kidney transplant recipient is s...,"In this setting, administration of bicarbonate...",A. Increased risk of mortality\nB. Increased r...,C,temp nan,Answer C: Decreased risk of progressive AKI r...
1,NEPHRO-HOLDOUT-0002,2848,Acute Kidney Injury & Critical Care Nephrology,A 65-year-old man with stage G3a CKD is seen i...,Which ONE of the following should you tell his...,A. Off-pump surgery in eligible patients is as...,A,temp nan,Answer A: Off-pump surgery in eligible patien...
2,NEPHRO-HOLDOUT-0003,5444,Acute Kidney Injury & Critical Care Nephrology,\nA 72-year-old man with hepatitis C–related c...,Which ONE of the following is the MOST likely ...,1. Abdominal compartment syndrome\n2. Acute tu...,D,temp nan,D. Hepatorenal syndrome
3,NEPHRO-HOLDOUT-0004,5448,Acute Kidney Injury & Critical Care Nephrology,\nYou are asked to see a 63-year-old man in co...,Which ONE of the following is MOST likely to p...,1. A fractional excretion of urea > 50%\n2. A ...,C,temp nan,C. Urine volume <200 ml over 2 hours after 1....
4,NEPHRO-HOLDOUT-0005,5455,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 5455\nIn which ONE of the following c...,1. Coronary artery bypass surgery\n2. Open abd...,C,temp nan,C. Radiocontrast exposure
5,NEPHRO-HOLDOUT-0006,5457,Acute Kidney Injury & Critical Care Nephrology,\nYou are asked to see a 68-year-old man with ...,Which ONE of the following is the MOST appropr...,1. Give a ﬂuid bolus and reassess in 1 hour\n2...,A,temp nan,A. Give a fluid bolus and reassess in 1 hour
6,NEPHRO-HOLDOUT-0007,5463,Acute Kidney Injury & Critical Care Nephrology,\nA 34-year-old combat victim is ﬂown to a mil...,Which ONE of the following places this trauma ...,1. Chest injury\n2. Head injury\n3. Abdominal ...,C,temp nan,C. Abdominal injury
7,NEPHRO-HOLDOUT-0008,5467,Acute Kidney Injury & Critical Care Nephrology,\nA 47-year-old woman with advanced heart fail...,Which ONE of the following would you advise re...,1. She is likely to experience at least a tran...,A,temp nan,A. She is likely to experience at least a tran...
8,NEPHRO-HOLDOUT-0009,5471,Acute Kidney Injury & Critical Care Nephrology,\nAn 80-year-old man is hospitalized for AKI. ...,Which ONE of the following diagnostic tests is...,1. Serum creatine kinase\n2. Urine eosinophils...,C,temp nan,C. Kidney ultrasound
9,NEPHRO-HOLDOUT-0010,5510,Acute Kidney Injury & Critical Care Nephrology,"\nA 75-year-old woman with diabetes, hypertens...",What strategies can you implement to prevent AKI?,A. Check urine sodium and risk-stratify...,C,temp nan,C. Give 0.9% sodium chloride before and after ...

In [72]:
# Compact manifest inspection

print("Manifest shape:", manifest_df.shape)
print("Manifest columns:", list(manifest_df.columns))

print("\nFirst 10 rows:")
display(manifest_df.head(10))

print("\nData types:")
display(manifest_df.dtypes.to_frame("dtype"))

print("\nMissing values:")
display(
    manifest_df.isna().sum()
    .sort_values(ascending=False)
    .to_frame("Missing")
)

Manifest shape: (796, 10)
Manifest columns: ['BenchmarkID', 'ID', 'Subject', 'Context', 'Question', 'Choices', 'Answer', 'Solution', 'explanation', 'split']

First 10 rows:

,BenchmarkID,ID,Subject,Context,Question,Choices,Answer,Solution,explanation,split
0,NEPHRO-EVAL-0001,2824,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2824:\nThe transfusion of longer-term...,1. Increased risk of transfusion-related react...,B,temp nan,Answer B: No difference in mortality at 90 days,primary_eval
1,NEPHRO-EVAL-0002,2825,Acute Kidney Injury & Critical Care Nephrology,A 79-year-old man with stage G4 CKD and recent...,"Based on data from the NUTRIREA-2 study, enter...",A. Decreased incidence of systemic bacteremia\...,B,temp nan,Answer B: Increased incidence of gastrointest...,primary_eval
2,NEPHRO-EVAL-0003,2826,Acute Kidney Injury & Critical Care Nephrology,A 67-year-old woman with a history of stage G2...,Which ONE of the following is CORRECT about th...,1. She is at decreased risk for inpatient mort...,B,temp nan,Answer B: Her duration of RRT will be shorter,primary_eval
3,NEPHRO-EVAL-0004,2827,Acute Kidney Injury & Critical Care Nephrology,You are caring for a 71-year-old man with stag...,Which ONE of the following is associated with ...,A. A decreased risk of surgical site infection...,B,temp nan,Answer B: An increased risk of AKI requiring RRT,primary_eval
4,NEPHRO-EVAL-0005,2829,Acute Kidney Injury & Critical Care Nephrology,You are admitting a 65-year-old kidney trans-p...,Which ONE of the following is the MOST importa...,A. Administration of a bolus of 30 ml/kg 0.9% ...,D,temp nan,Answer D: Early adminstration of appropriate ...,primary_eval
5,NEPHRO-EVAL-0006,2830,Acute Kidney Injury & Critical Care Nephrology,You are meeting with your hospital’s chief inf...,Which ONE of the following individuals is MOST...,A. A 35-year-old woman with serum creatinine t...,B,temp nan,Answer B: A 76-year-old woman with a serum cr...,primary_eval
6,NEPHRO-EVAL-0007,2831,Acute Kidney Injury & Critical Care Nephrology,The chief quality ofﬁcer at your institution a...,"Based on the existing literature, implementing...",A. A reduction in nephrotoxin exposure and eve...,B,temp nan,"Answer B: A reduction in RRT events, inpatien...",primary_eval
7,NEPHRO-EVAL-0008,2832,Acute Kidney Injury & Critical Care Nephrology,"Several weeks after joining a new practice, yo...",Which ONE of the following outcomes has been d...,"A. Fewer cases of severe AKI, but no differenc...",C,temp nan,"Answer C: Fewer cases of severe AKI, a higher...",primary_eval
8,NEPHRO-EVAL-0009,2833,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2833:\nImplementing a Kidney Disease ...,A. Shorter length of mechanical ventilation\nB...,B,temp nan,Answer B: A decreased rate of stage 2 and 3 AKI,primary_eval
9,NEPHRO-EVAL-0010,2834,Acute Kidney Injury & Critical Care Nephrology,A 28-year-old woman with ESRD receives a de-ce...,This patient’s urine output in response to int...,A. Acute renal allograft rejection\nB. 1-year ...,C,temp nan,Answer C: Delayed graft function after renal ...,primary_eval

Data types:

              dtype
BenchmarkID  object
ID            int64
Subject      object
Context      object
Question     object
Choices      object
Answer       object
Solution     object
explanation  object
split        object

Missing values:

             Missing
Context           48
BenchmarkID        0
ID                 0
Subject            0
Question           0
Choices            0
Answer             0
Solution           0
explanation        0
split              0

In [73]:
# Inspect the official benchmark split assignments

print("Official split distribution")
print("===========================")

split_counts = (
    manifest_df["split"]
    .value_counts()
    .rename_axis("Split")
    .reset_index(name="Questions")
)

display(split_counts)

print("\nSubject distribution by split")
print("=============================")

split_subject_counts = (
    manifest_df
    .groupby(["split", "Subject"])
    .size()
    .reset_index(name="Questions")
)

display(split_subject_counts)

Official split distribution
===========================

          Split  Questions
0  primary_eval        636
1      held_out        160

Subject distribution by split
=============================

           split                                            Subject  Questions
0       held_out     Acute Kidney Injury & Critical Care Nephrology         18
1       held_out                             Chronic Kidney Disease          6
2       held_out             Chronic Kidney Disease and Progression          6
3       held_out  Disorder of Divalent Ions Renal Bone Disease a...          6
4       held_out  Disorders of Divalent Ions Renal Bone Disease ...          5
5       held_out  Disorders of Divalent Ions, Renal Bone Disease...         11
6       held_out                                    ESRD & Dialysis          6
7       held_out                    Electrolyte Acid-Base Disorders          6
8       held_out               Electrolytes and Acid-Base Disorders          6
9       held_out                 End Stage Renal Disease & Dialysis          6
10      held_out                           End-Stage Kidney Disease          6
11      held_out                                       Hypertension         18
12      held_out  Infection Control & Prevention in Outpatient H...          6
13      held_out       Interventional Nephrology & Dialysis Therapy          6
14      held_out                       Pregnancy and Kidney Disease          6
15      held_out            Primary & Secondary Glomerular Diseases          6
16      held_out                         Primary Glomerular Disease          6
17      held_out          Primary and Secondary Glomerular Diseases         12
18      held_out                       Secondary Glomerular Disease          6
19      held_out                                    Transplantation         12
20  primary_eval     Acute Kidney Injury & Critical Care Nephrology         70
21  primary_eval                             Chronic Kidney Disease         24
22  primary_eval             Chronic Kidney Disease and Progression         24
23  primary_eval  Disorder of Divalent Ions Renal Bone Disease a...         23
24  primary_eval  Disorders of Divalent Ions Renal Bone Disease ...         22
25  primary_eval  Disorders of Divalent Ions, Renal Bone Disease...         46
26  primary_eval                                    ESRD & Dialysis         24
27  primary_eval                    Electrolyte Acid-Base Disorders         24
28  primary_eval               Electrolytes and Acid-Base Disorders         22
29  primary_eval                 End Stage Renal Disease & Dialysis         24
30  primary_eval                           End-Stage Kidney Disease         24
31  primary_eval                                       Hypertension         71
32  primary_eval  Infection Control & Prevention in Outpatient H...         24
33  primary_eval       Interventional Nephrology & Dialysis Therapy         24
34  primary_eval                       Pregnancy and Kidney Disease         24
35  primary_eval            Primary & Secondary Glomerular Diseases         23
36  primary_eval                         Primary Glomerular Disease         24
37  primary_eval          Primary and Secondary Glomerular Diseases         48
38  primary_eval                       Secondary Glomerular Disease         23
39  primary_eval                                    Transplantation         48