# NephroLLM — Execution Plan

1. Environment setup
2. Load Llama 3.2 3B Instruct
3. Define & Verify the base-model Inference
4. Load and validate the nephrology benchmark
5. Run a fresh baseline evaluation
6. Analyze baseline failures
7. Prepare fine-tuning dataset
8. Fine-tune using QLoRA
9. Save the LoRA adapter
10. Run the exact same evaluation on the fine-tuned model
11. Evaluate on held-out questions
12. Compare base vs fine-tuned model
13. Document findings, limitations, and conclusions

# NephroLLM — Fine-Tuning Llama 3.2 3B for Nephrology Q&A

Educational fine-tuning experiment using QLoRA to adapt Llama 3.2 3B Instruct to nephrology-focused questions.

**Objective:** Compare the base model against the QLoRA fine-tuned model using the same evaluation benchmark and evaluation protocol.

# 1. Environment Setup - Install Required Libraries

This cell installs the libraries required for model loading, inference, dataset handling, quantization, and parameter-efficient fine-tuning.

We use:

- **Transformers** - load and run Llama 3.2 3B Instruct
- **Datasets** - prepare and manage training/evaluation data
- **Accelerate** - support efficient model execution on the available GPU
- **PEFT** - implement LoRA/QLoRA fine-tuning
- **BitsAndBytes** - enable 4-bit quantization
- **TRL** - provide utilities for supervised fine-tuning

The goal at this stage is only to prepare the environment. No model weights are modified or fine-tuned in this cell.

# 1.1 Install required libraries

In [1]:
# cell 2
!pip install -U transformers datasets accelerate peft "bitsandbytes>=0.46.1" trl

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.17.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting datasets
  Downloading datasets-5.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting accelerate
  Downloading accelerate-1.15.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Collecting peft
  Downloading peft-0.21.0-py3-none-any.whl.metadata (15 kB)
Collecting bitsandbytes>=0.46.1
  Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting trl
  Downloading trl-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Collecting tokenizers<0.24.0,>=0.23.1 (from transformers)
  Downloading tokenizers-0.23.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Collecting safetensors>=0.8.0 (from transformers)
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.17.0-py3-none-any.whl (12.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 73.4 MB/s eta 0:00:00:00:010:01
Downloading datasets-5.0.1-py3-none-any.whl (559 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 25.7 MB/s eta 0:00:00
Downloading accelerate-1.15.0-py3-none-any.whl (394 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 15.4 MB/s eta 0:00:00
Downloading peft-0.21.0-py3-none-any.whl (832 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 832.9/832.9 kB 28.2 MB/s eta 0:00:00
Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl (43.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 42.7 MB/s eta 0:00:00:00:0100:01
Downloading trl-1.14.0-py3-none-any.whl (925 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 925.0/925.0 kB 29.7 MB/s eta 0:00:00
Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.0/516.0 kB 23.9 MB/s eta 0:00:00
Downloading tokenizers-0.23.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 78.5 MB/s eta 0:00:00:00:01
Installing collected packages: safetensors, bitsandbytes, tokenizers, datasets, accelerate, transformers, trl, peft
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.7.0
    Uninstalling safetensors-0.7.0:
      Successfully uninstalled safetensors-0.7.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: datasets
    Found existing installation: datasets 5.0.0
    Uninstalling datasets-5.0.0:
      Successfully uninstalled datasets-5.0.0
  Attempting uninstall: accelerate
    Found existing installation: accelerate 1.13.0
    Uninstalling accelerate-1.13.0:
      Successfully uninstalled accelerate-1.13.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
  Attempting uninstall: peft
    Found existing installation: peft 0.19.1
    Uninstalling peft-0.19.1:
      Successfully uninstalled peft-0.19.1
Successfully installed accelerate-1.15.0 bitsandbytes-0.50.2 datasets-5.0.1 peft-0.21.0 safetensors-0.8.0 tokenizers-0.23.2 transformers-5.17.0 trl-1.14.0

# 1.2 Verify environment and GPU
Environment and Hardware Verification

Before loading the model, we verify the versions of the main libraries and confirm that CUDA and the Kaggle GPU are available.

This is important because NephroLLM uses 4-bit quantization and will later use QLoRA for parameter-efficient fine-tuning. Both depend on compatible versions of the deep-learning and quantization libraries and access to a CUDA-enabled GPU.

We also record the available GPU memory so that the later fine-tuning configuration can be chosen with the available hardware in mind.

**Expected outcome:** CUDA should be available and a GPU should be detected.

In [4]:
import torch
import transformers
import accelerate
import bitsandbytes
import peft

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("BitsAndBytes:", bitsandbytes.__version__)
print("PEFT:", peft.__version__)

print("\nCUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch: 2.10.0+cu128
Transformers: 5.17.0
Accelerate: 1.15.0
BitsAndBytes: 0.50.2
PEFT: 0.21.0

CUDA available: True
GPU: Tesla T4

# 1.3 Authenticate with Hugging Face

Llama 3.2 3B Instruct is accessed through Hugging Face and requires an authenticated account with access to the model.

This cell retrieves the Hugging Face access token from Kaggle Secrets rather than hard-coding credentials in the notebook.

We only verify that a token is available. The token itself is never printed.

**Why this matters:** keeping credentials in Kaggle Secrets prevents sensitive authentication information from being committed to the notebook or exposed in the GitHub repository.

In [5]:
# cell 6
from kaggle_secrets import UserSecretsClient

user_secrets = UserSecretsClient()

hf_token = user_secrets.get_secret("HF_TOKEN")

print("HF token available:", hf_token is not None)
print("Token length:", len(hf_token) if hf_token else 0)

HF token available: True
Token length: 37

# 2 - Load Llama 3.2 3B Instruct

### Loading the Base Model with 4-bit Quantization

We now load the pretrained **Llama 3.2 3B Instruct** model that will serve as the starting point for the NephroLLM experiment.

The model is loaded using **4-bit NF4 quantization** with double quantization. This reduces the GPU memory required to load the 3B-parameter model and makes the later QLoRA experiment practical on the available Kaggle GPU.

At this stage, the model is still completely **untuned**. This is our base model and will be evaluated before any nephrology-specific fine-tuning.

**Configuration**

- **Base model:** `meta-llama/Llama-3.2-3B-Instruct`
- **Quantization:** 4-bit
- **Quantization type:** NF4
- **Compute dtype:** float16
- **Double quantization:** enabled
- **Device mapping:** automatic

**Why 4-bit quantization?**

QLoRA combines low-bit quantization of the base model with LoRA adapters that contain the trainable parameters. This allows us to fine-tune a large language model while using substantially less GPU memory than full-parameter fine-tuning.

**Expected outcome:** the tokenizer and quantized base model should load successfully on the available GPU.

In [6]:
from kaggle_secrets import UserSecretsClient
from huggingface_hub import login

# Retrieve Hugging Face token from Kaggle Secrets
user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")

# Authenticate with Hugging Face
login(token=hf_token, add_to_git_credential=False)

print("Hugging Face authentication successful.")
print("Token available:", bool(hf_token))

Hugging Face authentication successful.
Token available: True

In [7]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch

model_id = "meta-llama/Llama-3.2-3B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16
)

print("Loading tokenizer...")

tokenizer = AutoTokenizer.from_pretrained(
    model_id,
    token=hf_token
)

print("Loading model...")

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    token=hf_token
)

model.eval()

print("\nModel loaded successfully.")
print("Model device:", model.device)
print("Model dtype:", model.dtype)

Loading tokenizer...

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

Loading model...

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

Model loaded successfully.
Model device: cuda:0
Model dtype: torch.bfloat16

# Experimental Design

### Base Model → Fine-Tuning → Re-evaluation

The goal of NephroLLM is to measure whether nephrology-specific fine-tuning improves the model's performance on multiple-choice nephrology questions.

The experiment follows a controlled evaluation design:

1. **Base model evaluation**  
   Run the untuned Llama 3.2 3B Instruct model on the **636-question primary evaluation benchmark**.

2. **Baseline error analysis**  
   Analyze incorrect answers, non-answers, response formatting, and performance across nephrology subjects.

3. **Training data preparation**  
   Prepare a **separate nephrology training corpus** that is not part of the 636-question primary benchmark or the 160-question held-out benchmark.

4. **QLoRA fine-tuning**  
   Fine-tune the base model using parameter-efficient QLoRA rather than updating all model parameters.

5. **Post-training evaluation**  
   Run the fine-tuned model on the **exact same 636 primary questions** using the same evaluation protocol.

6. **Held-out evaluation**  
   Evaluate the fine-tuned model separately on **160 held-out nephrology questions** that were not used for training.

7. **Comparison**  
   Compare base-model and fine-tuned performance using the same scoring methodology.

### Evaluation Split

| Split | Questions | Purpose |
|---|---:|---|
| Primary evaluation | 636 | Base vs fine-tuned comparison |
| Held-out evaluation | 160 | Generalization check |
| **Total evaluation data** | **796** | Evaluation only |

**Important:** the 636 primary questions and 160 held-out questions are evaluation data. They must not be used as QLoRA training examples.

This separation is important because using evaluation questions for training would introduce data leakage and make the before/after comparison unreliable.

**Expected outcome:** establish a reproducible experimental protocol where the only intended change between the baseline and post-training evaluation is the model's fine-tuned parameters.

# 3 - Define & Verify the base Model Inference

# 3.1 Define standardized inference

Before running the benchmark, we define a reusable inference function that sends questions to the model using the Llama 3.2 Instruct chat format.

The function applies the model's chat template, generates a deterministic response, and returns only the newly generated text rather than the original prompt.

### Generation protocol

- **Sampling:** disabled (`do_sample=False`)
- **Maximum new tokens:** configurable per evaluation
- **Padding:** uses the tokenizer's EOS token
- **Inference mode:** gradients disabled with `torch.no_grad()`

Disabling sampling is important for evaluation because it makes the model's responses deterministic under the same configuration. This allows the base-model and fine-tuned evaluations to use the same generation protocol.

The function will be reused throughout the experiment rather than creating separate inference implementations for different stages.

**Expected outcome:** a single standardized inference function that can be used for smoke tests, benchmark evaluation, and post-training evaluation.

In [7]:
# cell 11
def ask_model(question, max_new_tokens=256):
    messages = [
        {
            "role": "system",
            "content": (
                "You are an educational assistant specializing in nephrology. "
                "Provide clear, factual, educational explanations. "
                "Do not provide diagnosis or personalized medical advice."
            )
        },
        {
            "role": "user",
            "content": question
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    answer = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    )

    return answer.strip()

# 3.2 Run an inference smoke test

Before running the full benchmark, we perform a small smoke test using a simple nephrology question.

The purpose of this test is **not to measure model performance**. It verifies that the complete inference pipeline is working correctly:

- the tokenizer can format the prompt,
- the model can generate a response,
- the GPU inference path is functioning,
- the generated tokens can be decoded correctly, and
- the `ask_model()` function returns usable text.

This provides a quick sanity check before starting the longer 636-question baseline evaluation.

**Expected outcome:** the model should return a coherent educational response to the test question.

In [8]:
# cell 13
question = "What is the primary function of the glomerulus?"

answer = ask_model(question)

print("QUESTION:")
print(question)

print("\nMODEL ANSWER:")
print(answer)

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

QUESTION:
What is the primary function of the glomerulus?

MODEL ANSWER:
The primary function of the glomerulus is to filter waste and excess fluids from the blood. It is a critical component of the nephron, the functional unit of the kidney, and plays a vital role in maintaining overall kidney function.

The glomerulus is a tuft of capillaries that receives blood from the afferent arteriole and sends it to the efferent arteriole. As the blood flows through the glomerulus, it is subjected to a pressure gradient that forces the fluid to pass through the glomerular basement membrane and into the Bowman's capsule. This process is known as filtration.

The glomerulus filters out waste products, excess ions, and excess water from the blood, while retaining essential nutrients, proteins, and other vital substances. The filtered waste products, including urea, creatinine, and other waste products, are then transported to the renal tubules for further processing and excretion.

In essence, the glomerulus acts as a selective filter, allowing only essential substances to pass through while rejecting waste products and excess fluids, making it a crucial component of the kidney's role in maintaining homeostasis and overall health.

# 4. Load and validate the Nephrology Benchmark

# 4.1 Experimental and data strategy


### Separating Training Data from Evaluation Data

A key requirement of this experiment is to keep the evaluation questions completely separate from the fine-tuning data.

The NephroLLM benchmark currently provides two evaluation splits:

- **Primary evaluation:** 636 questions
- **Held-out evaluation:** 160 questions

There is **no training split in this benchmark**. Therefore, these 796 questions will not be used as QLoRA training examples.

### Role of Each Dataset

| Dataset | Size | Role |
|---|---:|---|
| Primary evaluation | 636 | Base-model baseline and post-training comparison |
| Held-out evaluation | 160 | Generalization evaluation after fine-tuning |
| Separate training corpus | TBD | QLoRA fine-tuning |

The separate training corpus must contain nephrology educational material that is independent of these evaluation questions.

### Why this separation matters

If benchmark questions were included in the fine-tuning data, the model could memorize questions or answers rather than demonstrate genuine improvement in nephrology knowledge.

Keeping the evaluation data unseen during training allows us to make a cleaner before-versus-after comparison and provides a more meaningful test of generalization.

**Important:** at this stage, the evaluation benchmark is available, but the separate QLoRA training corpus still needs to be prepared.

**Expected outcome:** establish a clear data boundary before beginning fine-tuning and prevent evaluation-data leakage.

# 4.2 Load the primary evaluation benchmark

### Evaluating the Base Model on the Primary Benchmark

We now evaluate the untuned Llama 3.2 3B Instruct model on the **636-question primary nephrology benchmark**.

This establishes the quantitative baseline that will later be compared with the QLoRA fine-tuned model.

For every question, we preserve the model's raw response along with the parsed answer and ground-truth answer. This allows us to distinguish between:

- an incorrect answer,
- a response that could not be parsed,
- and a genuine non-answer or refusal.

### Evaluation protocol

The same protocol will be reused after fine-tuning:

- **Questions:** 636 primary evaluation questions
- **Model:** Llama 3.2 3B Instruct
- **Sampling:** deterministic (`do_sample=False`)
- **Maximum new tokens:** 96
- **Prompt format:** standardized multiple-choice prompt
- **Output:** raw model response + extracted answer + ground truth
- **Scoring:** exact option-level accuracy

The baseline results will serve as the reference point for measuring any change after QLoRA fine-tuning.

**Expected outcome:** a complete baseline prediction file containing one evaluation record for each of the 636 benchmark questions.

In [9]:
# cell 16
import os
import pandas as pd

# Find the finalized primary evaluation file
matches = []

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file == "nephrollm_primary_eval.csv":
            matches.append(os.path.join(root, file))

print("Found:", matches)

if len(matches) != 1:
    raise ValueError(
        f"Expected exactly one primary evaluation file, found: {matches}"
    )

eval_path = matches[0]
eval_df = pd.read_csv(eval_path)

print("Evaluation file:", eval_path)
print("Questions loaded:", len(eval_df))

display(
    eval_df[
        ["BenchmarkID", "Subject", "Question", "Choices", "Answer"]
    ].head()
)

Found: ['/kaggle/input/datasets/shantanuss/nejm-ai-nephrology-benchmark/nephrollm_primary_eval.csv']
Evaluation file: /kaggle/input/datasets/shantanuss/nejm-ai-nephrology-benchmark/nephrollm_primary_eval.csv
Questions loaded: 636

,BenchmarkID,Subject,Question,Choices,Answer
0,NEPHRO-EVAL-0001,Acute Kidney Injury & Critical Care Nephrology,Question 2824:\nThe transfusion of longer-term...,1. Increased risk of transfusion-related react...,B
1,NEPHRO-EVAL-0002,Acute Kidney Injury & Critical Care Nephrology,"Based on data from the NUTRIREA-2 study, enter...",A. Decreased incidence of systemic bacteremia\...,B
2,NEPHRO-EVAL-0003,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is CORRECT about th...,1. She is at decreased risk for inpatient mort...,B
3,NEPHRO-EVAL-0004,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is associated with ...,A. A decreased risk of surgical site infection...,B
4,NEPHRO-EVAL-0005,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is the MOST importa...,A. Administration of a bolus of 30 ml/kg 0.9% ...,D

# 5. Run a Fresh Baseline Evaluation

# 5.1 Lock the evaluation protocol
Locking the Evaluation Configuration

Before running the full baseline, we explicitly define the evaluation configuration.

This is important because the same evaluation protocol must be used later when testing the QLoRA fine-tuned model. Keeping the protocol fixed makes the before-versus-after comparison reproducible.

For each question, we will preserve:

1. The original benchmark question
2. The available answer choices
3. The model's raw response
4. The answer extracted by the evaluator
5. The ground-truth answer
6. Whether the extracted answer is correct

### Fixed evaluation settings

| Setting | Configuration |
|---|---|
| Evaluation split | Primary |
| Number of questions | 636 |
| Generation | Deterministic |
| `do_sample` | `False` |
| `max_new_tokens` | `96` |
| Scoring | Exact option match |
| Raw responses | Saved |
| Parsed answers | Saved |
| Ground truth | Saved |

The evaluator is intentionally conservative: if the model does not provide a recognizable answer choice, the response is treated as **unparsed/non-answer** rather than guessing what the model intended.

**Expected outcome:** the evaluation configuration is clearly documented before the baseline results are generated.

# 5.2 Define the MCQ answer parser

Multiple-Choice Answer Evaluator

The benchmark contains multiple-choice questions with four or five answer options. The model may express its answer in different formats, such as:

- `ANSWER: A`
- `ANSWER: 2`
- `C`
- `Option D`
- `Choice: B`

The evaluator normalizes these responses into a standard option label (`A`–`E`) before comparing them with the benchmark's ground-truth answer.

### Conservative parsing

The parser prioritizes explicit answer statements and recognizable option formats.

It does **not** attempt to infer an answer from general prose when the model does not clearly select an option.

For example, if the model produces a refusal, uncertainty statement, or explanation without a clearly identifiable answer choice, the response is recorded as **unparsed/non-answer**.

This conservative approach is intentional. Guessing the model's intended answer could artificially inflate the measured accuracy.

### Scoring

For each question:

```text
Predicted option == Ground-truth option
            ↓
        Correct / Incorrect

In [10]:
import re

def extract_answer(response):
    """
    Extract a single answer choice.

    Supports alphabetical and numerical answer formats.
    Numerical choices are mapped by position:
    1=A, 2=B, 3=C, 4=D, 5=E
    """

    if not response:
        return None

    text = str(response).strip().upper()

    # 1. Explicit ANSWER / CORRECT ANSWER formats
    patterns = [
        r"\bANSWER\s*:\s*([A-E])\b",
        r"\bCORRECT ANSWER\s*(?:IS)?\s*:?\s*([A-E])\b",
        r"\bTHE ANSWER\s*(?:IS)?\s*:?\s*([A-E])\b",
        r"\bMY ANSWER\s*(?:IS)?\s*:?\s*([A-E])\b",
    ]

    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            return match.group(1)

    # 2. Explicit numeric ANSWER format
    numeric_patterns = [
        r"\bANSWER\s*:\s*([1-5])\b",
        r"\bCORRECT ANSWER\s*(?:IS)?\s*:?\s*([1-5])\b",
        r"\bTHE ANSWER\s*(?:IS)?\s*:?\s*([1-5])\b",
        r"\bMY ANSWER\s*(?:IS)?\s*:?\s*([1-5])\b",
    ]

    for pattern in numeric_patterns:
        match = re.search(pattern, text)
        if match:
            return "ABCDE"[int(match.group(1)) - 1]

    # 3. Standalone answer formats: A, A., A)
    lines = [x.strip() for x in text.splitlines() if x.strip()]

    for line in lines[:8]:
        match = re.fullmatch(r"([A-E])[\.\)]?", line)
        if match:
            return match.group(1)

    # 4. Standalone numeric answer: 1, 1., 1)
    for line in lines[:8]:
        match = re.fullmatch(r"([1-5])[\.\)]?", line)
        if match:
            return "ABCDE"[int(match.group(1)) - 1]

    # 5. OPTION / CHOICE format
    for line in lines[:8]:
        match = re.fullmatch(
            r"(?:OPTION|CHOICE)\s*[:\-]?\s*([A-E])[\.\)]?",
            line
        )
        if match:
            return match.group(1)

        match = re.fullmatch(
            r"(?:OPTION|CHOICE)\s*[:\-]?\s*([1-5])[\.\)]?",
            line
        )
        if match:
            return "ABCDE"[int(match.group(1)) - 1]

    return None

# 5.3 Define the standardized MCQ prompt

We now define the prompt used to evaluate each benchmark question.

The model is explicitly instructed to select **one answer from the provided choices** and return it in a standardized format:

```text
ANSWER: <option letter>

In [11]:
# cell 19
def ask_mcq_fast(question, choices, max_new_tokens=32):
    """
    Ask the base model to answer one MCQ.

    The benchmark may contain 4 or 5 choices and may use
    alphabetical or numerical labels.
    """

    choice_lines = str(choices).strip()

    prompt = f"""Answer this multiple-choice nephrology question.

Question:
{question}

Choices:
{choice_lines}

Select the single best answer from the choices provided.

Return ONLY:
ANSWER: <option letter>
"""

    return ask_model(
        prompt,
        max_new_tokens=max_new_tokens
    )

# 5.4 Run a small evaluation sanity check

In [12]:
# cell 27 
test_df = eval_df.head(5).copy()

test_results = []

for _, row in test_df.iterrows():

    response = ask_mcq_fast(
        row["Question"],
        row["Choices"]
    )

    predicted = extract_answer(response)
    expected = str(row["Answer"]).strip().upper()

    test_results.append({
        "BenchmarkID": row["BenchmarkID"],
        "Expected": expected,
        "Predicted": predicted,
        "Correct": predicted == expected,
        "ModelResponse": response
    })

test_results_df = pd.DataFrame(test_results)

display(test_results_df)

        BenchmarkID Expected Predicted  Correct ModelResponse
0  NEPHRO-EVAL-0001        B         D    False             D
1  NEPHRO-EVAL-0002        B         A    False             A
2  NEPHRO-EVAL-0003        B         A    False            A.
3  NEPHRO-EVAL-0004        B         B     True             B
4  NEPHRO-EVAL-0005        D         D     True             D

# 5.5 Run the full 636-question baseline

### Running the 636-Question Benchmark

The evaluation protocol is now locked, so we can run the complete primary benchmark against the untuned base model.

The benchmark contains **636 questions**. Because generation can be time-consuming on the available GPU, the evaluation is executed in batches and each batch is saved separately.

For every question, we retain the model's raw response and the information required for later scoring and error analysis.

### Why save batches?

Saving intermediate results provides two benefits:

1. **Fault tolerance:** if a long evaluation run is interrupted, completed batches do not need to be regenerated.
2. **Reproducibility:** each batch produces a persistent prediction file that can be independently inspected and aggregated.

After all batches are complete, the individual files are combined into one final baseline result set containing all 636 questions.

**Important:** this run is the base-model baseline. No QLoRA training has been performed yet.

**Expected outcome:** 636 baseline predictions are generated and stored for subsequent scoring and analysis.

In [13]:
from tqdm.auto import tqdm
import os
import pandas as pd

BATCH_SIZE = 50

BASELINE_PREFIX = "/kaggle/working/nephrollm_baseline_final_batch_"

for start in range(0, len(eval_df), BATCH_SIZE):

    end = min(start + BATCH_SIZE, len(eval_df))
    batch = eval_df.iloc[start:end].copy()

    batch_number = start // BATCH_SIZE + 1

    print(
        f"\nRunning Batch {batch_number}: "
        f"questions {start + 1} to {end}"
    )

    batch_results = []

    for _, row in tqdm(
        batch.iterrows(),
        total=len(batch),
        desc=f"Batch {batch_number}"
    ):

        response = ask_mcq_fast(
            row["Question"],
            row["Choices"]
        )

        predicted = extract_answer(response)
        expected = str(row["Answer"]).strip().upper()

        batch_results.append({
            "BenchmarkID": row["BenchmarkID"],
            "Subject": row["Subject"],
            "Question": row["Question"],
            "Choices": row["Choices"],
            "Expected": expected,
            "Predicted": predicted,
            "Correct": predicted == expected,
            "ModelResponse": response
        })

    batch_df = pd.DataFrame(batch_results)

    batch_path = (
        f"{BASELINE_PREFIX}"
        f"{start + 1:03d}_{end:03d}.csv"
    )

    batch_df.to_csv(batch_path, index=False)

    print(f"Saved: {batch_path}")
    print(
        f"Batch accuracy: "
        f"{batch_df['Correct'].mean():.2%}"
    )
    print(
        f"Unparsed: "
        f"{batch_df['Predicted'].isna().sum()}"
    )

Running Batch 1: questions 1 to 50

Batch 1:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_001_050.csv
Batch accuracy: 56.00%
Unparsed: 1

Running Batch 2: questions 51 to 100

Batch 2:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_051_100.csv
Batch accuracy: 48.00%
Unparsed: 1

Running Batch 3: questions 101 to 150

Batch 3:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_101_150.csv
Batch accuracy: 52.00%
Unparsed: 1

Running Batch 4: questions 151 to 200

Batch 4:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_151_200.csv
Batch accuracy: 28.00%
Unparsed: 6

Running Batch 5: questions 201 to 250

Batch 5:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_201_250.csv
Batch accuracy: 40.00%
Unparsed: 3

Running Batch 6: questions 251 to 300

Batch 6:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_251_300.csv
Batch accuracy: 38.00%
Unparsed: 4

Running Batch 7: questions 301 to 350

Batch 7:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_301_350.csv
Batch accuracy: 44.00%
Unparsed: 5

Running Batch 8: questions 351 to 400

Batch 8:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_351_400.csv
Batch accuracy: 60.00%
Unparsed: 1

Running Batch 9: questions 401 to 450

Batch 9:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_401_450.csv
Batch accuracy: 40.00%
Unparsed: 4

Running Batch 10: questions 451 to 500

Batch 10:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_451_500.csv
Batch accuracy: 28.00%
Unparsed: 9

Running Batch 11: questions 501 to 550

Batch 11:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_501_550.csv
Batch accuracy: 28.00%
Unparsed: 5

Running Batch 12: questions 551 to 600

Batch 12:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_551_600.csv
Batch accuracy: 44.00%
Unparsed: 2

Running Batch 13: questions 601 to 636

Batch 13:   0%|          | 0/36 [00:00<?, ?it/s]

Saved: /kaggle/working/nephrollm_baseline_final_batch_601_636.csv
Batch accuracy: 33.33%
Unparsed: 1

# 5.6 Aggregate baseline predictions

The 636-question baseline was executed in multiple batches. We now combine those batch outputs into a single evaluation dataset.

Before calculating the final score, we verify that:

- all expected batch files are present,
- the combined result contains 636 rows,
- each benchmark question appears only once, and
- the final result can be saved as a single reproducible CSV.

This step converts the raw batch predictions into the canonical baseline result file that will be used for all subsequent analysis.

**Expected outcome:** one consolidated baseline file containing exactly **636 unique benchmark questions**.

In [14]:
import glob
import pandas as pd

baseline_files = sorted(
    glob.glob(
        "/kaggle/working/nephrollm_baseline_final_batch_*.csv"
    )
)

print("Fresh baseline batch files:", len(baseline_files))

if len(baseline_files) != 13:
    raise ValueError(
        f"Expected 13 fresh baseline files, found {len(baseline_files)}"
    )

baseline_df = pd.concat(
    [pd.read_csv(f) for f in baseline_files],
    ignore_index=True
)

# Safety checks
print("Rows before deduplication:", len(baseline_df))
print(
    "Unique BenchmarkIDs:",
    baseline_df["BenchmarkID"].nunique()
)

if len(baseline_df) != 636:
    raise ValueError(
        f"Expected 636 rows, found {len(baseline_df)}"
    )

if baseline_df["BenchmarkID"].nunique() != 636:
    raise ValueError("Duplicate or missing BenchmarkIDs detected.")

# Save one consolidated fresh baseline file
baseline_path = (
    "/kaggle/working/"
    "nephrollm_baseline_final_results.csv"
)

baseline_df.to_csv(
    baseline_path,
    index=False
)

print("\nFresh baseline saved:")
print(baseline_path)

print("\nColumns:")
print(list(baseline_df.columns))

Fresh baseline batch files: 13
Rows before deduplication: 636
Unique BenchmarkIDs: 636

Fresh baseline saved:
/kaggle/working/nephrollm_baseline_final_results.csv

Columns:
['BenchmarkID', 'Subject', 'Question', 'Choices', 'Expected', 'Predicted', 'Correct', 'ModelResponse']

# 6. Analyze Baseline Failures
### Measuring Base-Model Performance

With all 636 predictions consolidated, we now calculate the baseline performance of the untuned Llama 3.2 3B Instruct model.

We report two complementary metrics:

- **Accuracy (all questions):** correct answers divided by all 636 benchmark questions.
- **Accuracy (answered-only):** correct answers divided by questions for which the evaluator successfully extracted a valid answer choice.

We also report the number of **unparsed/non-answer responses** separately. This is important because a model can fail either by selecting the wrong option or by failing to provide a usable answer.

### Fresh baseline result

| Metric | Result |
|---|---:|
| Questions evaluated | ** ** |
| Correct | ** ** |
| Incorrect | ** ** |
| Unparsed / non-answer | ** ** |
| Accuracy — all questions | ** ** |
| Accuracy — answered only | ** ** |

The **41.51%** figure is the primary baseline metric because it treats a non-answer as a failure on the benchmark item rather than excluding it from evaluation.

The answered-only figure is reported as a secondary diagnostic metric to show performance among responses where the evaluator could identify a selected option.

These baseline results will become the reference point for the post-QLoRA evaluation.

**Important:** these are the results from the fresh 636-question baseline run and the finalized conservative answer parser. No fine-tuning has been performed yet.

# 6.1 Calculate the initial baseline results

In [15]:
print("NEPHROLLM — FRESH BASELINE")
print("==========================")

total_questions = len(baseline_df)
correct = baseline_df["Correct"].sum()
unparsed = baseline_df["Predicted"].isna().sum()
incorrect = total_questions - correct - unparsed

accuracy_all = correct / total_questions
accuracy_answered = (
    correct / (total_questions - unparsed)
    if total_questions - unparsed > 0
    else 0
)

print(f"Total questions:      {total_questions}")
print(f"Correct:              {correct}")
print(f"Incorrect:            {incorrect}")
print(f"Unparsed:             {unparsed}")
print(f"Accuracy (all):       {accuracy_all:.2%}")
print(f"Accuracy (answered):  {accuracy_answered:.2%}")

NEPHROLLM — FRESH BASELINE
==========================
Total questions:      636
Correct:              265
Incorrect:            328
Unparsed:             43
Accuracy (all):       41.67%
Accuracy (answered):  44.69%

# 6.2 Inspect unparsed responses

After applying the finalized answer parser, we inspect the responses that still cannot be mapped reliably to an answer choice.

The purpose of this step is to validate that the remaining parsing failures are genuine **non-answers or ambiguous responses**, rather than valid answer formats that the parser has missed.

We display a sample of the unparsed responses together with their expected answers and available choices. This allows us to manually inspect the model's actual output before treating these responses as failures in the final baseline score.

The unparsed responses are **not reinterpreted or guessed** during this inspection. If the model does not clearly select an answer option, the response remains unparsed.

**Expected outcome:** confirm that the remaining unparsed responses represent genuine non-answers or ambiguous outputs and that the conservative parser should remain unchanged.

In [16]:
unparsed_df = baseline_df[
    baseline_df["Predicted"].isna()
].copy()

print("Unparsed responses:", len(unparsed_df))

display(
    unparsed_df[
        [
            "BenchmarkID",
            "Expected",
            "Choices",
            "ModelResponse"
        ]
    ].head(20)
)

Unparsed responses: 43

,BenchmarkID,Expected,Choices,ModelResponse
24,NEPHRO-EVAL-0025,C,A. Intermittent hemodiaﬁltration\nB. Intermitt...,I'm happy to help you with your nephrology que...
64,NEPHRO-EVAL-0065,A,A. Regional citrate anticoagulation (RC...,I'm happy to help you with your nephrology que...
144,NEPHRO-EVAL-0145,D,A. Denosumab\nB. Increase calcium acetate\nC. ...,I'm happy to help you with your nephrology que...
155,NEPHRO-EVAL-0156,A,A. Cinacalcet therapy\nB. Calcitonin\nC. Estro...,I'm happy to help you with your nephrology que...
176,NEPHRO-EVAL-0177,C,1. Refer for cardiac catheterization\n2. Chest...,I'm happy to help you with your nephrology que...
180,NEPHRO-EVAL-0181,C,1. Ankylosing spondylitis\n2. Adynamic bone di...,I'm happy to help you with your nephrology que...
182,NEPHRO-EVAL-0183,D,1. Hypercalciuria\n2. Renal tubular acidosis\n...,I'm happy to help you with your nephrology que...
188,NEPHRO-EVAL-0189,C,1. A loss of function mutation in the calcium-...,I'm happy to help you with your nephrology que...
191,NEPHRO-EVAL-0192,A,1. Change calcium acetate to sevelamer carbona...,I can't provide a specific answer without know...
227,NEPHRO-EVAL-0228,D,A. Discontinue pravastatin now\nB. Discontinue...,I'm happy to help you with your nephrology que...
244,NEPHRO-EVAL-0245,B,A. 0 L\nB. 1.8 L\nC. 2.3 L\nD. 2.8 L,To maintain serum sodium levels without a furt...
245,NEPHRO-EVAL-0246,D,A. Simple metabolic alkalosis\nB. Metabolic al...,I'm ready to help. Please provide the scenario...
251,NEPHRO-EVAL-0252,D,A. The thick ascending limb of the loop of Hen...,A. The thick ascending limb of the loop of Henle
254,NEPHRO-EVAL-0255,B,A. Nasogastric suction\nB. Gentamicin\nC. Post...,I'm happy to help you with your nephrology que...
257,NEPHRO-EVAL-0258,B,A. Loop diuretic (furosemide) IV (20 mg...,I cannot provide a diagnosis or recommend trea...
277,NEPHRO-EVAL-0278,C,1. Gitelman syndrome\n2. Renovascular hyperten...,I'm happy to help you with your nephrology que...
301,NEPHRO-EVAL-0302,A,A. Avoid skin trauma and subcutaneous injectio...,I'm happy to help you with your nephrology que...
317,NEPHRO-EVAL-0318,A,1. Convert to nocturnal HD 7 hours 5 times per...,I can't provide a specific answer without know...
332,NEPHRO-EVAL-0333,D,A. No change in management\nB. Add doxazosin\n...,A. No change in management
338,NEPHRO-EVAL-0339,D,A. Measure plasma metanephrines\nB. Refer for ...,I'm happy to help you with your nephrology que...

# Re-scoring the Complete Baseline

We now apply the finalized answer parser to all stored model responses and recompute the baseline metrics.

The scoring logic separates three outcomes:

- **Correct:** the parsed model answer matches the benchmark answer.
- **Incorrect:** the model selected an identifiable option, but it does not match the benchmark answer.
- **Unparsed:** the response does not contain a reliably identifiable answer choice.

Two accuracy measures are calculated:

- **Accuracy (all):** correct answers divided by all 636 questions.
- **Accuracy (answered):** correct answers divided by questions with a successfully parsed answer.

The re-scored results are saved to:

`nephrollm_baseline_final_results.csv`

This is a deterministic post-processing step. **No model inference is performed here**, so the underlying model responses remain exactly the same as those generated during the original baseline run.

**Expected outcome:** the finalized baseline metrics are produced using the locked conservative parser and the complete set of 636 stored responses.

In [17]:
baseline_df["Predicted"] = (
    baseline_df["ModelResponse"]
    .apply(extract_answer)
)

baseline_df["Correct"] = (
    baseline_df["Predicted"]
    == baseline_df["Expected"]
)

total_questions = len(baseline_df)
correct = baseline_df["Correct"].sum()
unparsed = baseline_df["Predicted"].isna().sum()
incorrect = total_questions - correct - unparsed

print("NEPHROLLM — FRESH BASELINE (REPARSED)")
print("=====================================")
print(f"Total questions:      {total_questions}")
print(f"Correct:              {correct}")
print(f"Incorrect:            {incorrect}")
print(f"Unparsed:             {unparsed}")
print(f"Accuracy (all):       {correct / total_questions:.2%}")
print(
    f"Accuracy (answered):  "
    f"{correct / (total_questions - unparsed):.2%}"
)

baseline_df.to_csv(
    "/kaggle/working/nephrollm_baseline_final_results.csv",
    index=False
)

NEPHROLLM — FRESH BASELINE (REPARSED)
=====================================
Total questions:      636
Correct:              265
Incorrect:            328
Unparsed:             43
Accuracy (all):       41.67%
Accuracy (answered):  44.69%

# Final Inspection of Unparsed Responses

After re-scoring the complete baseline with the finalized parser, we perform one final inspection of the responses that remain unparsed.

This confirms that the parser is not systematically missing a valid answer format that should be counted.

For each remaining unparsed response, we retain:

- `BenchmarkID`
- expected answer
- available choices
- raw model response

The responses are kept as unparsed when the model does not provide a sufficiently clear option selection. We do not manually assign an answer during scoring.

This preserves a conservative and reproducible evaluation protocol.

**Expected outcome:** the remaining unparsed responses are confirmed as genuine non-answers or ambiguous outputs, supporting the use of the finalized baseline score.

In [18]:
remaining_unparsed = baseline_df[
    baseline_df["Predicted"].isna()
].copy()

print("Remaining unparsed:", len(remaining_unparsed))

display(
    remaining_unparsed[
        [
            "BenchmarkID",
            "Expected",
            "Choices",
            "ModelResponse"
        ]
    ]
)

Remaining unparsed: 43

,BenchmarkID,Expected,Choices,ModelResponse
24,NEPHRO-EVAL-0025,C,A. Intermittent hemodiaﬁltration\nB. Intermitt...,I'm happy to help you with your nephrology que...
64,NEPHRO-EVAL-0065,A,A. Regional citrate anticoagulation (RC...,I'm happy to help you with your nephrology que...
144,NEPHRO-EVAL-0145,D,A. Denosumab\nB. Increase calcium acetate\nC. ...,I'm happy to help you with your nephrology que...
155,NEPHRO-EVAL-0156,A,A. Cinacalcet therapy\nB. Calcitonin\nC. Estro...,I'm happy to help you with your nephrology que...
176,NEPHRO-EVAL-0177,C,1. Refer for cardiac catheterization\n2. Chest...,I'm happy to help you with your nephrology que...
180,NEPHRO-EVAL-0181,C,1. Ankylosing spondylitis\n2. Adynamic bone di...,I'm happy to help you with your nephrology que...
182,NEPHRO-EVAL-0183,D,1. Hypercalciuria\n2. Renal tubular acidosis\n...,I'm happy to help you with your nephrology que...
188,NEPHRO-EVAL-0189,C,1. A loss of function mutation in the calcium-...,I'm happy to help you with your nephrology que...
191,NEPHRO-EVAL-0192,A,1. Change calcium acetate to sevelamer carbona...,I can't provide a specific answer without know...
227,NEPHRO-EVAL-0228,D,A. Discontinue pravastatin now\nB. Discontinue...,I'm happy to help you with your nephrology que...
244,NEPHRO-EVAL-0245,B,A. 0 L\nB. 1.8 L\nC. 2.3 L\nD. 2.8 L,To maintain serum sodium levels without a furt...
245,NEPHRO-EVAL-0246,D,A. Simple metabolic alkalosis\nB. Metabolic al...,I'm ready to help. Please provide the scenario...
251,NEPHRO-EVAL-0252,D,A. The thick ascending limb of the loop of Hen...,A. The thick ascending limb of the loop of Henle
254,NEPHRO-EVAL-0255,B,A. Nasogastric suction\nB. Gentamicin\nC. Post...,I'm happy to help you with your nephrology que...
257,NEPHRO-EVAL-0258,B,A. Loop diuretic (furosemide) IV (20 mg...,I cannot provide a diagnosis or recommend trea...
277,NEPHRO-EVAL-0278,C,1. Gitelman syndrome\n2. Renovascular hyperten...,I'm happy to help you with your nephrology que...
301,NEPHRO-EVAL-0302,A,A. Avoid skin trauma and subcutaneous injectio...,I'm happy to help you with your nephrology que...
317,NEPHRO-EVAL-0318,A,1. Convert to nocturnal HD 7 hours 5 times per...,I can't provide a specific answer without know...
332,NEPHRO-EVAL-0333,D,A. No change in management\nB. Add doxazosin\n...,A. No change in management
338,NEPHRO-EVAL-0339,D,A. Measure plasma metanephrines\nB. Refer for ...,I'm happy to help you with your nephrology que...
339,NEPHRO-EVAL-0340,D,A. Refer for surgery\nB. Add spironolactone 50...,I'm happy to help you with your nephrology que...
367,NEPHRO-EVAL-0368,B,1. Order an adrenal MRI\n2. Order adrenal vein...,"I cannot provide medical advice. However, I ca..."
413,NEPHRO-EVAL-0414,C,A. Continue vancomycin for at least 4 weeks an...,I need more information about the patient's co...
421,NEPHRO-EVAL-0422,A,A. Review the patient’s baseline vital signs\n...,I can't provide a specific answer without know...
427,NEPHRO-EVAL-0428,C,A. Placement of a hybrid graft–catheter device...,A. Placement of a hybrid graft–catheter device
448,NEPHRO-EVAL-0449,E,A. Implement a 2-g sodium-restricted diet\nB. ...,I'm happy to help you with your nephrology que...
459,NEPHRO-EVAL-0460,D,A. Continue current dialysis regimen\nB. Hemod...,I'm happy to help you with your nephrology que...
466,NEPHRO-EVAL-0467,B,A. No additional management\nB. Enzyme replace...,I'm happy to help you with your nephrology que...
471,NEPHRO-EVAL-0472,C,A. Start low-dose ramipril\nB. Check the urine...,I'm happy to help you with your nephrology que...
472,NEPHRO-EVAL-0473,E,A. Repeat kidney biopsy\nB. Mycophenolate mofe...,I'm happy to help you with your nephrology que...
475,NEPHRO-EVAL-0476,A,A. Oral angiotensin receptor blockers (ARBs)\n...,I'm happy to help you with your nephrology que...
483,NEPHRO-EVAL-0484,D,A. Rituximab plus plasma exchange\nB. Rituxima...,I'm happy to help you with your nephrology que...
486,NEPHRO-EVAL-0487,A,A. A calcineurin inhibitor\nB. Prednisone at 1...,I can't provide a diagnosis or treatment recom...
489,NEPHRO-EVAL-0490,A,"A. Plasmapheresis, high-dose corticosteroids, ...",I'm happy to help you with your nephrology que...
490,NEPHRO-EVAL-0491,A,A. Provide supportive care and management for ...,I'm happy to help you with your nephrology que...
504,NEPHRO-EVAL-0505,B,A. 3.2 per 100 patient years\nB. 6.6 per 100 p...,I'm happy to help you with your nephrology que...
515,NEPHRO-EVAL-0516,C,A. Oral tacrolimus 0.1 mg/kg per day for 1 yea...,I cannot provide a specific treatment recommen...
518,NEPHRO-EVAL-0519,D,1. Add an antihypertensive agent to tighten he...,I'm happy to help you with your nephrology que...
521,NEPHRO-EVAL-0522,D,1. Obtain a kidney biopsy\n2. Initiate immunos...,I'm happy to help you with your nephrology que...
538,NEPHRO-EVAL-0539,C,1. Increase his empagliﬂozin to 25 mg daily\n2...,"I can't provide medical advice, but I can give..."
561,NEPHRO-EVAL-0562,B,1. Initiate zoledronate\n2. Initiate denosumab...,I can't provide a specific answer without know...
563,NEPHRO-EVAL-0564,C,1. Autosomal dominant\n2. Autosomal recessive\...,I'm ready to assist. Please provide the condit...
617,NEPHRO-EVAL-0618,D,"1. Discontinue tacrolimus, start belatacept\n2...",I'm happy to help you with your nephrology que...

# 6.5 Analyze performance by subject

### Performance Across Nephrology Subjects

Overall accuracy provides a useful headline metric, but it does not show whether the model performs consistently across different areas of nephrology.

We therefore break the 636-question baseline down by the benchmark's **Subject** field.

For each subject, we examine:

- number of questions,
- number of correct answers,
- number of unparsed responses, and
- accuracy.

This helps identify areas where the base model performs relatively differently and provides a more informative starting point for evaluating the effect of nephrology-specific fine-tuning.

### Important interpretation note

Subject-level results should be interpreted alongside the number of questions in each category. Smaller subject groups can produce larger percentage changes from only a few questions.

The subject labels are retained exactly as provided by the benchmark rather than manually merging or renaming categories.

**Expected outcome:** a subject-level baseline performance table showing where the base model succeeds and where errors are concentrated.

In [19]:
subject_accuracy = (
    baseline_df
    .groupby("Subject")
    .agg(
        Questions=("BenchmarkID", "count"),
        Correct=("Correct", "sum"),
        Unparsed=("Predicted", lambda x: x.isna().sum())
    )
    .reset_index()
)

subject_accuracy["Incorrect"] = (
    subject_accuracy["Questions"]
    - subject_accuracy["Correct"]
    - subject_accuracy["Unparsed"]
)

subject_accuracy["Accuracy"] = (
    subject_accuracy["Correct"]
    / subject_accuracy["Questions"]
    * 100
)

subject_accuracy = subject_accuracy.sort_values(
    "Accuracy",
    ascending=True
)

display(subject_accuracy)

,Subject,Questions,Correct,Unparsed,Incorrect,Accuracy
15,Primary & Secondary Glomerular Diseases,23,6,7,10,26.086957
4,Disorders of Divalent Ions Renal Bone Disease ...,22,6,2,14,27.272727
5,"Disorders of Divalent Ions, Renal Bone Disease...",46,13,5,28,28.260870
14,Pregnancy and Kidney Disease,24,7,3,14,29.166667
17,Primary and Secondary Glomerular Diseases,48,14,5,29,29.166667
16,Primary Glomerular Disease,24,7,2,15,29.166667
8,Electrolytes and Acid-Base Disorders,22,7,2,13,31.818182
7,Electrolyte Acid-Base Disorders,24,8,4,12,33.333333
12,Infection Control & Prevention in Outpatient H...,24,9,2,13,37.500000
19,Transplantation,48,19,1,28,39.583333
6,ESRD & Dialysis,24,10,1,13,41.666667
18,Secondary Glomerular Disease,23,10,0,13,43.478261
1,Chronic Kidney Disease,24,11,0,13,45.833333
3,Disorder of Divalent Ions Renal Bone Disease a...,23,11,0,12,47.826087
10,End-Stage Kidney Disease,24,12,1,11,50.000000
13,Interventional Nephrology & Dialysis Therapy,24,12,1,11,50.000000
0,Acute Kidney Injury & Critical Care Nephrology,70,36,2,32,51.428571
11,Hypertension,71,37,4,30,52.112676
9,End Stage Renal Disease & Dialysis,24,13,1,10,54.166667
2,Chronic Kidney Disease and Progression,24,17,0,7,70.833333

# 6.6 Analyze incorrect answer selections

In [20]:
# Baseline error analysis — parseable incorrect answers only

baseline_errors = baseline_df[
    (baseline_df["Predicted"].notna()) &
    (baseline_df["Correct"] == False)
].copy()

print("BASELINE ERROR ANALYSIS")
print("=======================")
print(f"Total benchmark questions: {len(baseline_df)}")
print(f"Parseable incorrect answers: {len(baseline_errors)}")
print()

print("Most common predicted answers:")
display(
    baseline_errors["Predicted"]
    .value_counts()
    .rename_axis("Predicted")
    .reset_index(name="Count")
)

print("\nExpected answer distribution:")
display(
    baseline_errors["Expected"]
    .value_counts()
    .rename_axis("Expected")
    .reset_index(name="Count")
)

print("\nSample baseline errors:")
display(
    baseline_errors[
        [
            "BenchmarkID",
            "Subject",
            "Question",
            "Expected",
            "Predicted",
            "ModelResponse"
        ]
    ].head(20)
)

BASELINE ERROR ANALYSIS
=======================
Total benchmark questions: 636
Parseable incorrect answers: 328

Most common predicted answers:

  Predicted  Count
0         B    122
1         A     86
2         D     54
3         C     52
4         E     14

Expected answer distribution:

  Expected  Count
0        D     96
1        C     87
2        B     74
3        A     57
4        E     14

Sample baseline errors:

,BenchmarkID,Subject,Question,Expected,Predicted,ModelResponse
0,NEPHRO-EVAL-0001,Acute Kidney Injury & Critical Care Nephrology,Question 2824:\nThe transfusion of longer-term...,B,D,D
1,NEPHRO-EVAL-0002,Acute Kidney Injury & Critical Care Nephrology,"Based on data from the NUTRIREA-2 study, enter...",B,A,A
2,NEPHRO-EVAL-0003,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is CORRECT about th...,B,A,A.
5,NEPHRO-EVAL-0006,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following individuals is MOST...,B,A,ANSWER: A
6,NEPHRO-EVAL-0007,Acute Kidney Injury & Critical Care Nephrology,"Based on the existing literature, implementing...",B,D,ANSWER: D
7,NEPHRO-EVAL-0008,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following outcomes has been d...,C,B,B
8,NEPHRO-EVAL-0009,Acute Kidney Injury & Critical Care Nephrology,Question 2833:\nImplementing a Kidney Disease ...,B,D,ANSWER: D
16,NEPHRO-EVAL-0017,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following should you tell the...,B,A,ANSWER: A
27,NEPHRO-EVAL-0028,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is MOST likely to r...,B,C,ANSWER: 3
29,NEPHRO-EVAL-0030,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following interventions would...,D,C,ANSWER: 3
30,NEPHRO-EVAL-0031,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following anticoagulation str...,D,A,ANSWER: 1
32,NEPHRO-EVAL-0033,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is the MOST likely ...,D,C,ANSWER: 3
33,NEPHRO-EVAL-0034,Acute Kidney Injury & Critical Care Nephrology,On the basis of published retrospective cohort...,B,D,ANSWER: 4
36,NEPHRO-EVAL-0037,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following ﬁndings decreases t...,B,A,ANSWER: 1
39,NEPHRO-EVAL-0040,Acute Kidney Injury & Critical Care Nephrology,Prescription of which ONE of the following med...,D,B,ANSWER: B
40,NEPHRO-EVAL-0041,Acute Kidney Injury & Critical Care Nephrology,Her internist raises concerns about potential ...,D,B,ANSWER: B
41,NEPHRO-EVAL-0042,Acute Kidney Injury & Critical Care Nephrology,Which ONE of his medications should not be cop...,B,D,ANSWER: 4
42,NEPHRO-EVAL-0043,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following statements BEST des...,B,A,I'll provide the correct answer.\n\nANSWER: 1
43,NEPHRO-EVAL-0044,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is the BEST choice ...,B,D,ANSWER: 4
47,NEPHRO-EVAL-0048,Acute Kidney Injury & Critical Care Nephrology,Which ONE of the following is the MOST likely ...,A,C,ANSWER: 3

# 6.7 Analyze response formats

In [21]:
# Analyze baseline response formats

def classify_response_format(response):
    if response is None or str(response).strip() == "":
        return "empty"

    text = str(response).strip().upper()

    if re.search(r"\bANSWER\s*:\s*[A-E]\b", text):
        return "ANSWER: letter"

    if re.search(r"\bANSWER\s*:\s*[1-5]\b", text):
        return "ANSWER: number"

    if re.fullmatch(r"[A-E][\.\)]?", text):
        return "standalone letter"

    if re.fullmatch(r"[1-5][\.\)]?", text):
        return "standalone number"

    if text.startswith("I CANNOT") or text.startswith("I CAN'T"):
        return "refusal"

    if "MEDICAL ADVICE" in text:
        return "medical-advice refusal"

    return "other"


baseline_df["ResponseFormat"] = (
    baseline_df["ModelResponse"]
    .apply(classify_response_format)
)

format_summary = (
    baseline_df
    .groupby("ResponseFormat")
    .agg(
        Questions=("BenchmarkID", "count"),
        Correct=("Correct", "sum")
    )
    .reset_index()
)

format_summary["Accuracy"] = (
    format_summary["Correct"]
    / format_summary["Questions"]
    * 100
)

format_summary = format_summary.sort_values(
    "Questions",
    ascending=False
)

display(format_summary)

      ResponseFormat  Questions  Correct    Accuracy
0     ANSWER: letter        237      100   42.194093
1     ANSWER: number        181       81   44.751381
4  standalone letter        167       81   48.502994
2              other         41        2    4.878049
3            refusal          9        0    0.000000
5  standalone number          1        1  100.000000

# 6.8 Audit generated baseline artifacts

In [22]:
import os
import glob

print("Kaggle input datasets:")
print("======================")

for root, dirs, files in os.walk("/kaggle/input"):
    level = root.replace("/kaggle/input", "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files[:20]:
        print(f"{indent}  {file}")

print("\nWorking directory CSV files:")
print("============================")

for path in sorted(glob.glob("/kaggle/working/*.csv")):
    print(path)

Kaggle input datasets:
======================
input/
  datasets/
    shantanuss/
      nejm-ai-nephrology-benchmark/
        nephrollm_evaluation_manifest.csv
        nephrollm_primary_eval.csv
        nephrollm_heldout_eval.csv

Working directory CSV files:
============================
/kaggle/working/nephrollm_baseline_final_batch_001_050.csv
/kaggle/working/nephrollm_baseline_final_batch_051_100.csv
/kaggle/working/nephrollm_baseline_final_batch_101_150.csv
/kaggle/working/nephrollm_baseline_final_batch_151_200.csv
/kaggle/working/nephrollm_baseline_final_batch_201_250.csv
/kaggle/working/nephrollm_baseline_final_batch_251_300.csv
/kaggle/working/nephrollm_baseline_final_batch_301_350.csv
/kaggle/working/nephrollm_baseline_final_batch_351_400.csv
/kaggle/working/nephrollm_baseline_final_batch_401_450.csv
/kaggle/working/nephrollm_baseline_final_batch_451_500.csv
/kaggle/working/nephrollm_baseline_final_batch_501_550.csv
/kaggle/working/nephrollm_baseline_final_batch_551_600.csv
/kaggle/working/nephrollm_baseline_final_batch_601_636.csv
/kaggle/working/nephrollm_baseline_final_results.csv

# 4.3 Load the benchmark manifest and held-out dataset

### Loading the Evaluation Manifest and Held-Out Split

We now load the benchmark manifest and the separate held-out evaluation dataset.

The **manifest** provides the official dataset structure and split assignments, while the **held-out dataset** contains the 160 questions reserved for the final generalization evaluation.

At this stage, we are only inspecting the data. No held-out questions are used for model training.

We verify:

- dataset dimensions,
- available columns,
- sample records, and
- the structure of the held-out evaluation data.

### Why this matters

The held-out split must remain separate from the QLoRA training corpus. Keeping it untouched allows us to evaluate whether the fine-tuned model can generalize to nephrology questions that were not used during training.

The held-out questions will be evaluated **after fine-tuning**, using the same answer-extraction and scoring methodology used for the primary evaluation.

**Expected outcome:** the manifest and held-out evaluation dataset load successfully, with the held-out split containing **160 questions**.

In [23]:
import pandas as pd

BASE = "/kaggle/input/datasets/shantanuss/nejm-ai-nephrology-benchmark"

manifest_path = f"{BASE}/nephrollm_evaluation_manifest.csv"
heldout_path = f"{BASE}/nephrollm_heldout_eval.csv"

manifest_df = pd.read_csv(manifest_path)
heldout_df = pd.read_csv(heldout_path)

print("MANIFEST")
print("========")
print("Shape:", manifest_df.shape)
print("Columns:", list(manifest_df.columns))
display(manifest_df.head(20))

print("\nHELD-OUT EVALUATION")
print("===================")
print("Shape:", heldout_df.shape)
print("Columns:", list(heldout_df.columns))
display(heldout_df.head(10))

MANIFEST
========
Shape: (796, 10)
Columns: ['BenchmarkID', 'ID', 'Subject', 'Context', 'Question', 'Choices', 'Answer', 'Solution', 'explanation', 'split']

,BenchmarkID,ID,Subject,Context,Question,Choices,Answer,Solution,explanation,split
0,NEPHRO-EVAL-0001,2824,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2824:\nThe transfusion of longer-term...,1. Increased risk of transfusion-related react...,B,temp nan,Answer B: No difference in mortality at 90 days,primary_eval
1,NEPHRO-EVAL-0002,2825,Acute Kidney Injury & Critical Care Nephrology,A 79-year-old man with stage G4 CKD and recent...,"Based on data from the NUTRIREA-2 study, enter...",A. Decreased incidence of systemic bacteremia\...,B,temp nan,Answer B: Increased incidence of gastrointest...,primary_eval
2,NEPHRO-EVAL-0003,2826,Acute Kidney Injury & Critical Care Nephrology,A 67-year-old woman with a history of stage G2...,Which ONE of the following is CORRECT about th...,1. She is at decreased risk for inpatient mort...,B,temp nan,Answer B: Her duration of RRT will be shorter,primary_eval
3,NEPHRO-EVAL-0004,2827,Acute Kidney Injury & Critical Care Nephrology,You are caring for a 71-year-old man with stag...,Which ONE of the following is associated with ...,A. A decreased risk of surgical site infection...,B,temp nan,Answer B: An increased risk of AKI requiring RRT,primary_eval
4,NEPHRO-EVAL-0005,2829,Acute Kidney Injury & Critical Care Nephrology,You are admitting a 65-year-old kidney trans-p...,Which ONE of the following is the MOST importa...,A. Administration of a bolus of 30 ml/kg 0.9% ...,D,temp nan,Answer D: Early adminstration of appropriate ...,primary_eval
5,NEPHRO-EVAL-0006,2830,Acute Kidney Injury & Critical Care Nephrology,You are meeting with your hospital’s chief inf...,Which ONE of the following individuals is MOST...,A. A 35-year-old woman with serum creatinine t...,B,temp nan,Answer B: A 76-year-old woman with a serum cr...,primary_eval
6,NEPHRO-EVAL-0007,2831,Acute Kidney Injury & Critical Care Nephrology,The chief quality ofﬁcer at your institution a...,"Based on the existing literature, implementing...",A. A reduction in nephrotoxin exposure and eve...,B,temp nan,"Answer B: A reduction in RRT events, inpatien...",primary_eval
7,NEPHRO-EVAL-0008,2832,Acute Kidney Injury & Critical Care Nephrology,"Several weeks after joining a new practice, yo...",Which ONE of the following outcomes has been d...,"A. Fewer cases of severe AKI, but no differenc...",C,temp nan,"Answer C: Fewer cases of severe AKI, a higher...",primary_eval
8,NEPHRO-EVAL-0009,2833,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2833:\nImplementing a Kidney Disease ...,A. Shorter length of mechanical ventilation\nB...,B,temp nan,Answer B: A decreased rate of stage 2 and 3 AKI,primary_eval
9,NEPHRO-EVAL-0010,2834,Acute Kidney Injury & Critical Care Nephrology,A 28-year-old woman with ESRD receives a de-ce...,This patient’s urine output in response to int...,A. Acute renal allograft rejection\nB. 1-year ...,C,temp nan,Answer C: Delayed graft function after renal ...,primary_eval
10,NEPHRO-EVAL-0011,2835,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2835:\nWhich ONE of the following pat...,A. 56-year-old man with fulminant hepatic fail...,B,temp nan,Answer B: A 62-year-old man with a stage G3a:...,primary_eval
11,NEPHRO-EVAL-0012,2836,Acute Kidney Injury & Critical Care Nephrology,A 28-year-old man in your hospital’s neuro-int...,Which ONE of the following biomarkers is MOST ...,A. Urine kidney injury molecule-1\nB. Urine ne...,B,temp nan,Answer B: Urine neutrophil gelatinase-associa...,primary_eval
12,NEPHRO-EVAL-0013,2837,Acute Kidney Injury & Critical Care Nephrology,A 65-year-old woman with class II New York Hea...,"Based on the available data, which ONE of the ...",A. Her baseline serum creatinine is not a risk...,B,temp nan,Answer B: The transcatheter approach for aort...,primary_eval
13,NEPHRO-EVAL-0014,2838,Acute Kidney Injury & Critical Care Nephrology,"A 70-year-old man with stage G3b:A3 CKD, diabe...",Which ONE of the following recom-mendations is...,A. N-acetylcysteine should be administered 2 d...,C,temp nan,Answer C: Neither N-acetylcysteine compared t...,primary_eval
14,NEPHRO-EVAL-0015,2839,Acute Kidney Injury & Critical Care Nephrology,"A 60-year-old man with diabetes mellitus, hype...",Which ONE of the following statements most acc...,A. Continuous venovenous hemodiaﬁltration is s...,D,temp nan,Answer D: There is no significant difference ...,primary_eval
15,NEPHRO-EVAL-0016,2840,Acute Kidney Injury & Critical Care Nephrology,"A 70-year-old man with stage G3b:A2 CKD, diabe...",Which ONE of the following is the MOST accurat...,A. It has no impact on his subsequent risk of ...,B,temp nan,Answer B: It increases his risk of incident c...,primary_eval
16,NEPHRO-EVAL-0017,2841,Acute Kidney Injury & Critical Care Nephrology,A 55-year-old man with diabetes mellitus is ev...,Which ONE of the following should you tell the...,"A. Continuous renal replacement therapy (RRT),...",b,temp nan,"Answer B: Continuous RRT, if chosen, should b...",primary_eval
17,NEPHRO-EVAL-0018,2842,Acute Kidney Injury & Critical Care Nephrology,A 72-year-old woman is seen in consultation fo...,Which ONE of the following types of cardiac dy...,A. Isolated severe right ventricular systolic ...,A,temp nan,Answer A: Isolated severe right ventricular s...,primary_eval
18,NEPHRO-EVAL-0019,2843,Acute Kidney Injury & Critical Care Nephrology,A 72-year-old man with pneumonia due to Staphy...,Which ONE of the following should you indicate...,A. Trough levels of 15 to 20 mg/L are not asso...,D,temp nan,Answer D: Vancomycin nephrotoxicity has been a...,primary_eval
19,NEPHRO-EVAL-0020,2844,Acute Kidney Injury & Critical Care Nephrology,You are asked to see a 79-year-old woman with ...,Which ONE of the following statements is the M...,A. Vancomycin nephrotoxicity is unlikely becau...,C,temp nan,Answer C: The combination of vancomycin and p...,primary_eval

HELD-OUT EVALUATION
===================
Shape: (160, 9)
Columns: ['BenchmarkID', 'ID', 'Subject', 'Context', 'Question', 'Choices', 'Answer', 'Solution', 'explanation']

,BenchmarkID,ID,Subject,Context,Question,Choices,Answer,Solution,explanation
0,NEPHRO-HOLDOUT-0001,2828,Acute Kidney Injury & Critical Care Nephrology,A 63-year-old kidney transplant recipient is s...,"In this setting, administration of bicarbonate...",A. Increased risk of mortality\nB. Increased r...,C,temp nan,Answer C: Decreased risk of progressive AKI r...
1,NEPHRO-HOLDOUT-0002,2848,Acute Kidney Injury & Critical Care Nephrology,A 65-year-old man with stage G3a CKD is seen i...,Which ONE of the following should you tell his...,A. Off-pump surgery in eligible patients is as...,A,temp nan,Answer A: Off-pump surgery in eligible patien...
2,NEPHRO-HOLDOUT-0003,5444,Acute Kidney Injury & Critical Care Nephrology,\nA 72-year-old man with hepatitis C–related c...,Which ONE of the following is the MOST likely ...,1. Abdominal compartment syndrome\n2. Acute tu...,D,temp nan,D. Hepatorenal syndrome
3,NEPHRO-HOLDOUT-0004,5448,Acute Kidney Injury & Critical Care Nephrology,\nYou are asked to see a 63-year-old man in co...,Which ONE of the following is MOST likely to p...,1. A fractional excretion of urea > 50%\n2. A ...,C,temp nan,C. Urine volume <200 ml over 2 hours after 1....
4,NEPHRO-HOLDOUT-0005,5455,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 5455\nIn which ONE of the following c...,1. Coronary artery bypass surgery\n2. Open abd...,C,temp nan,C. Radiocontrast exposure
5,NEPHRO-HOLDOUT-0006,5457,Acute Kidney Injury & Critical Care Nephrology,\nYou are asked to see a 68-year-old man with ...,Which ONE of the following is the MOST appropr...,1. Give a ﬂuid bolus and reassess in 1 hour\n2...,A,temp nan,A. Give a fluid bolus and reassess in 1 hour
6,NEPHRO-HOLDOUT-0007,5463,Acute Kidney Injury & Critical Care Nephrology,\nA 34-year-old combat victim is ﬂown to a mil...,Which ONE of the following places this trauma ...,1. Chest injury\n2. Head injury\n3. Abdominal ...,C,temp nan,C. Abdominal injury
7,NEPHRO-HOLDOUT-0008,5467,Acute Kidney Injury & Critical Care Nephrology,\nA 47-year-old woman with advanced heart fail...,Which ONE of the following would you advise re...,1. She is likely to experience at least a tran...,A,temp nan,A. She is likely to experience at least a tran...
8,NEPHRO-HOLDOUT-0009,5471,Acute Kidney Injury & Critical Care Nephrology,\nAn 80-year-old man is hospitalized for AKI. ...,Which ONE of the following diagnostic tests is...,1. Serum creatine kinase\n2. Urine eosinophils...,C,temp nan,C. Kidney ultrasound
9,NEPHRO-HOLDOUT-0010,5510,Acute Kidney Injury & Critical Care Nephrology,"\nA 75-year-old woman with diabetes, hypertens...",What strategies can you implement to prevent AKI?,A. Check urine sodium and risk-stratify...,C,temp nan,C. Give 0.9% sodium chloride before and after ...

# 4.4 Inspect benchmark structure and data quality

We now perform a more detailed structural check of the benchmark manifest.

The inspection covers:

- overall dataset shape,
- column names,
- sample records,
- data types, and
- missing values.

This confirms that the manifest contains the fields required for evaluation and split management, and helps identify any data-quality issues before the evaluation workflow continues.

The manifest contains **796 records across 10 columns**.

We specifically check for missing values rather than silently filling them, because the evaluation data should be preserved in its original form.

**Expected outcome:** the manifest structure and data types are consistent with the expected benchmark schema, with any missing values explicitly reported for review.

# 4.5 Validate official evaluation splits

### Confirming the Benchmark Split Assignments

Before proceeding with model evaluation and fine-tuning, we verify the official split assignments provided by the benchmark manifest.

The benchmark contains two evaluation splits:

- **`primary_eval` — 636 questions**
- **`held_out` — 160 questions**

There is no training split in the benchmark manifest.

We also inspect the subject distribution within each split to understand how the evaluation data is organized.

### Why this validation matters

The split assignments determine how the benchmark will be used throughout the experiment:

- `primary_eval` is used for the base-model baseline and the later base-vs-fine-tuned comparison.
- `held_out` is reserved for the separate generalization evaluation.
- Neither split is permitted to become part of the QLoRA training corpus.

This check establishes the data boundary before any fine-tuning begins.

**Expected outcome:** the manifest should contain exactly **636 primary-evaluation questions and 160 held-out questions**, for a total of **796 evaluation questions**.

In [24]:
# Compact manifest inspection

print("Manifest shape:", manifest_df.shape)
print("Manifest columns:", list(manifest_df.columns))

print("\nFirst 10 rows:")
display(manifest_df.head(10))

print("\nData types:")
display(manifest_df.dtypes.to_frame("dtype"))

print("\nMissing values:")
display(
    manifest_df.isna().sum()
    .sort_values(ascending=False)
    .to_frame("Missing")
)

Manifest shape: (796, 10)
Manifest columns: ['BenchmarkID', 'ID', 'Subject', 'Context', 'Question', 'Choices', 'Answer', 'Solution', 'explanation', 'split']

First 10 rows:

,BenchmarkID,ID,Subject,Context,Question,Choices,Answer,Solution,explanation,split
0,NEPHRO-EVAL-0001,2824,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2824:\nThe transfusion of longer-term...,1. Increased risk of transfusion-related react...,B,temp nan,Answer B: No difference in mortality at 90 days,primary_eval
1,NEPHRO-EVAL-0002,2825,Acute Kidney Injury & Critical Care Nephrology,A 79-year-old man with stage G4 CKD and recent...,"Based on data from the NUTRIREA-2 study, enter...",A. Decreased incidence of systemic bacteremia\...,B,temp nan,Answer B: Increased incidence of gastrointest...,primary_eval
2,NEPHRO-EVAL-0003,2826,Acute Kidney Injury & Critical Care Nephrology,A 67-year-old woman with a history of stage G2...,Which ONE of the following is CORRECT about th...,1. She is at decreased risk for inpatient mort...,B,temp nan,Answer B: Her duration of RRT will be shorter,primary_eval
3,NEPHRO-EVAL-0004,2827,Acute Kidney Injury & Critical Care Nephrology,You are caring for a 71-year-old man with stag...,Which ONE of the following is associated with ...,A. A decreased risk of surgical site infection...,B,temp nan,Answer B: An increased risk of AKI requiring RRT,primary_eval
4,NEPHRO-EVAL-0005,2829,Acute Kidney Injury & Critical Care Nephrology,You are admitting a 65-year-old kidney trans-p...,Which ONE of the following is the MOST importa...,A. Administration of a bolus of 30 ml/kg 0.9% ...,D,temp nan,Answer D: Early adminstration of appropriate ...,primary_eval
5,NEPHRO-EVAL-0006,2830,Acute Kidney Injury & Critical Care Nephrology,You are meeting with your hospital’s chief inf...,Which ONE of the following individuals is MOST...,A. A 35-year-old woman with serum creatinine t...,B,temp nan,Answer B: A 76-year-old woman with a serum cr...,primary_eval
6,NEPHRO-EVAL-0007,2831,Acute Kidney Injury & Critical Care Nephrology,The chief quality ofﬁcer at your institution a...,"Based on the existing literature, implementing...",A. A reduction in nephrotoxin exposure and eve...,B,temp nan,"Answer B: A reduction in RRT events, inpatien...",primary_eval
7,NEPHRO-EVAL-0008,2832,Acute Kidney Injury & Critical Care Nephrology,"Several weeks after joining a new practice, yo...",Which ONE of the following outcomes has been d...,"A. Fewer cases of severe AKI, but no differenc...",C,temp nan,"Answer C: Fewer cases of severe AKI, a higher...",primary_eval
8,NEPHRO-EVAL-0009,2833,Acute Kidney Injury & Critical Care Nephrology,NaN,Question 2833:\nImplementing a Kidney Disease ...,A. Shorter length of mechanical ventilation\nB...,B,temp nan,Answer B: A decreased rate of stage 2 and 3 AKI,primary_eval
9,NEPHRO-EVAL-0010,2834,Acute Kidney Injury & Critical Care Nephrology,A 28-year-old woman with ESRD receives a de-ce...,This patient’s urine output in response to int...,A. Acute renal allograft rejection\nB. 1-year ...,C,temp nan,Answer C: Delayed graft function after renal ...,primary_eval

Data types:

              dtype
BenchmarkID  object
ID            int64
Subject      object
Context      object
Question     object
Choices      object
Answer       object
Solution     object
explanation  object
split        object

Missing values:

             Missing
Context           48
BenchmarkID        0
ID                 0
Subject            0
Question           0
Choices            0
Answer             0
Solution           0
explanation        0
split              0

In [26]:
# Inspect the official benchmark split assignments

print("Official split distribution")
print("===========================")

split_counts = (
    manifest_df["split"]
    .value_counts()
    .rename_axis("Split")
    .reset_index(name="Questions")
)

display(split_counts)

print("\nSubject distribution by split")
print("=============================")

split_subject_counts = (
    manifest_df
    .groupby(["split", "Subject"])
    .size()
    .reset_index(name="Questions")
)

display(split_subject_counts)

Official split distribution
===========================

          Split  Questions
0  primary_eval        636
1      held_out        160

Subject distribution by split
=============================

           split                                            Subject  Questions
0       held_out     Acute Kidney Injury & Critical Care Nephrology         18
1       held_out                             Chronic Kidney Disease          6
2       held_out             Chronic Kidney Disease and Progression          6
3       held_out  Disorder of Divalent Ions Renal Bone Disease a...          6
4       held_out  Disorders of Divalent Ions Renal Bone Disease ...          5
5       held_out  Disorders of Divalent Ions, Renal Bone Disease...         11
6       held_out                                    ESRD & Dialysis          6
7       held_out                    Electrolyte Acid-Base Disorders          6
8       held_out               Electrolytes and Acid-Base Disorders          6
9       held_out                 End Stage Renal Disease & Dialysis          6
10      held_out                           End-Stage Kidney Disease          6
11      held_out                                       Hypertension         18
12      held_out  Infection Control & Prevention in Outpatient H...          6
13      held_out       Interventional Nephrology & Dialysis Therapy          6
14      held_out                       Pregnancy and Kidney Disease          6
15      held_out            Primary & Secondary Glomerular Diseases          6
16      held_out                         Primary Glomerular Disease          6
17      held_out          Primary and Secondary Glomerular Diseases         12
18      held_out                       Secondary Glomerular Disease          6
19      held_out                                    Transplantation         12
20  primary_eval     Acute Kidney Injury & Critical Care Nephrology         70
21  primary_eval                             Chronic Kidney Disease         24
22  primary_eval             Chronic Kidney Disease and Progression         24
23  primary_eval  Disorder of Divalent Ions Renal Bone Disease a...         23
24  primary_eval  Disorders of Divalent Ions Renal Bone Disease ...         22
25  primary_eval  Disorders of Divalent Ions, Renal Bone Disease...         46
26  primary_eval                                    ESRD & Dialysis         24
27  primary_eval                    Electrolyte Acid-Base Disorders         24
28  primary_eval               Electrolytes and Acid-Base Disorders         22
29  primary_eval                 End Stage Renal Disease & Dialysis         24
30  primary_eval                           End-Stage Kidney Disease         24
31  primary_eval                                       Hypertension         71
32  primary_eval  Infection Control & Prevention in Outpatient H...         24
33  primary_eval       Interventional Nephrology & Dialysis Therapy         24
34  primary_eval                       Pregnancy and Kidney Disease         24
35  primary_eval            Primary & Secondary Glomerular Diseases         23
36  primary_eval                         Primary Glomerular Disease         24
37  primary_eval          Primary and Secondary Glomerular Diseases         48
38  primary_eval                       Secondary Glomerular Disease         23
39  primary_eval                                    Transplantation         48

# 7. Prepare fine-tuning dataset

# 7.1 Define training-data requirements

The benchmark used in this project is reserved entirely for evaluation. It contains 636 primary-evaluation questions and 160 held-out questions, with no training split.

Therefore, the QLoRA training corpus must be a **separate nephrology educational dataset** that is not derived from the evaluation questions.

The training corpus should provide examples that are suitable for supervised instruction fine-tuning, with a clear relationship between an input and an expected educational response.

### Training-data requirements

The training corpus should:

- contain nephrology-focused educational content;
- be independent of the 636 primary evaluation questions;
- be independent of the 160 held-out questions;
- provide sufficiently clear question/answer or instruction/response examples;
- avoid relying on patient-specific medical advice;
- be convertible into the chat/instruction format expected by Llama 3.2 3B Instruct.

### Data-leakage rule

The evaluation benchmark is treated as **read-only evaluation data**.

No question, answer, solution, or explanation from the primary or held-out evaluation sets will be intentionally included as a QLoRA training example.

This separation is necessary so that the later comparison between the base model and fine-tuned model measures performance on unseen evaluation data rather than memorization.

**Expected outcome:** establish the requirements and data boundaries for the separate QLoRA training corpus before any training data is loaded or transformed.

# 7.2 Select an independent nephrology theory corpus


The evaluation benchmark does not contain a training split, so the QLoRA training data must come from a separate source.

For NephroLLM, we will use an **independent medical theory/textbook corpus** as the knowledge source for fine-tuning rather than training directly on multiple-choice questions.

### Why a theory corpus?

The goal of fine-tuning is to improve the model's underlying nephrology knowledge and its ability to provide educational explanations.

A theory-based corpus can expose the model to:

- nephrology concepts and terminology;
- disease mechanisms;
- renal physiology and pathophysiology;
- diagnostic principles;
- treatment concepts; and
- explanatory relationships between clinical concepts.

This provides a broader knowledge signal than training exclusively on MCQs.

### Training-data strategy

The selected theory corpus will be processed through the following pipeline:

```text
Independent medical theory corpus
            ↓
Identify nephrology-relevant content
            ↓
Clean and validate the text
            ↓
Remove duplicates and unsuitable content
            ↓
Check for overlap with the NephroLLM benchmark
            ↓
Convert selected content into
instruction-response examples
            ↓
Final QLoRA training dataset

# 7.3 Load and Inspect the Theory Corpus

We now load the independent medical theory corpus selected as the knowledge source for NephroLLM fine-tuning.

The purpose of this step is to understand the raw corpus before extracting nephrology-specific content.

We will inspect:

- the dataset structure and available splits;
- the available metadata;
- the source documents or textbooks;
- the text fields;
- the approximate size of the corpus; and
- whether the corpus provides enough information to reliably identify nephrology-related content.

At this stage, we will **not** filter, transform, or generate training examples.

Understanding the raw data first allows us to design the subsequent filtering and preprocessing steps based on the actual corpus structure rather than making assumptions about its fields or organization.

### Data boundary

The theory corpus is an independent training source.

The **636 primary-evaluation questions** and **160 held-out questions** remain outside this pipeline and will not be used to construct training examples.

**Expected outcome:** confirm that the theory corpus loads successfully and understand its schema and available metadata before extracting nephrology-relevant content.

In [8]:
from datasets import load_dataset

# Load the MedRAG medical textbook corpus
theory_ds = load_dataset("MedRAG/textbooks")

# Basic dataset structure
print("Dataset:")
print(theory_ds)

# Inspect available splits
print("\nSplits:")
print(theory_ds.keys())

# Inspect schema
print("\nFeatures:")
print(theory_ds["train"].features)

# Number of records
print("\nNumber of records:")
print(len(theory_ds["train"]))

# Inspect a sample record
print("\nSample record:")
print(theory_ds["train"][0])

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

chunk/Cell_Biology_Alberts.jsonl:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chunk/Gynecology_Novak.jsonl:   0%|          | 0.00/13.3M [00:00<?, ?B/s]

chunk/Histology_Ross.jsonl:   0%|          | 0.00/7.05M [00:00<?, ?B/s]

chunk/Pathology_Robbins.jsonl:   0%|          | 0.00/8.65M [00:00<?, ?B/s]

chunk/Anatomy_Gray.jsonl:   0%|          | 0.00/5.19M [00:00<?, ?B/s]

chunk/Obstentrics_Williams.jsonl:   0%|          | 0.00/15.2M [00:00<?, ?B/s]

chunk/First_Aid_Step1.jsonl:   0%|          | 0.00/1.60M [00:00<?, ?B/s]

chunk/Neurology_Adams.jsonl:   0%|          | 0.00/19.5M [00:00<?, ?B/s]

chunk/Biochemistry_Lippincott.jsonl:   0%|          | 0.00/3.19M [00:00<?, ?B/s]

chunk/Physiology_Levy.jsonl:   0%|          | 0.00/6.97M [00:00<?, ?B/s]

chunk/Pharmacology_Katzung.jsonl:   0%|          | 0.00/11.9M [00:00<?, ?B/s]

chunk/Pathoma_Husain.jsonl:   0%|          | 0.00/983k [00:00<?, ?B/s]

chunk/InternalMed_Harrison.jsonl:   0%|          | 0.00/52.6M [00:00<?, ?B/s]

chunk/Pediatrics_Nelson.jsonl:   0%|          | 0.00/6.84M [00:00<?, ?B/s]

chunk/First_Aid_Step2.jsonl:   0%|          | 0.00/2.50M [00:00<?, ?B/s]

chunk/Immunology_Janeway.jsonl:   0%|          | 0.00/7.89M [00:00<?, ?B/s]

chunk/Psichiatry_DSM-5.jsonl:   0%|          | 0.00/6.73M [00:00<?, ?B/s]

chunk/Surgery_Schwartz.jsonl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/125847 [00:00<?, ? examples/s]

Dataset:
DatasetDict({
    train: Dataset({
        features: ['id', 'title', 'content', 'contents'],
        num_rows: 125847
    })
})

Splits:
dict_keys(['train'])

Features:
{'id': Value('string'), 'title': Value('string'), 'content': Value('string'), 'contents': Value('string')}

Number of records:
125847

Sample record:
{'id': 'Anatomy_Gray_0', 'title': 'Anatomy_Gray', 'content': 'What is anatomy? Anatomy includes those structures that can be seen grossly (without the aid of magnification) and microscopically (with the aid of magnification). Typically, when used by itself, the term anatomy tends to mean gross or macroscopic anatomy—that is, the study of structures that can be seen without using a microscopic. Microscopic anatomy, also called histology, is the study of cells and tissues using a microscope. Anatomy forms the basis for the practice of medicine. Anatomy leads the physician toward an understanding of a patient’s disease, whether he or she is carrying out a physical examination or using the most advanced imaging techniques. Anatomy is also important for dentists, chiropractors, physical therapists, and all others involved in any aspect of patient treatment that begins with an analysis of clinical signs. The ability to interpret a clinical observation correctly is therefore the endpoint of a sound anatomical understanding.', 'contents': 'Anatomy_Gray. What is anatomy? Anatomy includes those structures that can be seen grossly (without the aid of magnification) and microscopically (with the aid of magnification). Typically, when used by itself, the term anatomy tends to mean gross or macroscopic anatomy—that is, the study of structures that can be seen without using a microscopic. Microscopic anatomy, also called histology, is the study of cells and tissues using a microscope. Anatomy forms the basis for the practice of medicine. Anatomy leads the physician toward an understanding of a patient’s disease, whether he or she is carrying out a physical examination or using the most advanced imaging techniques. Anatomy is also important for dentists, chiropractors, physical therapists, and all others involved in any aspect of patient treatment that begins with an analysis of clinical signs. The ability to interpret a clinical observation correctly is therefore the endpoint of a sound anatomical understanding.'}

# 7.4 Identify Nephrology-Relevant Content

The theory corpus contains medical content across multiple subjects and clinical domains. We now identify the portions that are relevant to nephrology and renal medicine.

The goal is to construct a focused nephrology knowledge corpus rather than fine-tuning on unrelated medical material.

### Selection approach

We will use the metadata and text available in the corpus to identify relevant content.

Potential nephrology-related concepts include:

- kidney and renal physiology;
- acute kidney injury;
- chronic kidney disease;
- glomerular diseases;
- electrolyte and acid-base disorders;
- hypertension and kidney disease;
- dialysis and end-stage kidney disease;
- renal transplantation;
- nephrolithiasis;
- renal pathology; and
- other kidney-related conditions and mechanisms.

The exact filtering criteria will be determined from the actual structure and metadata of the loaded corpus.

### Important consideration

Keyword matching alone can produce both false positives and false negatives.

For example, a general medical passage may mention the kidney without being primarily about nephrology, while a relevant nephrology concept may not contain an obvious keyword.

Therefore, the initial filter will be treated as a **candidate-selection step**. The resulting records will be inspected before they become part of the final training corpus.

**Expected outcome:** identify a reproducible method for extracting candidate nephrology-related passages from the independent theory corpus.

In [9]:
import pandas as pd
import re

# Convert the training split to a DataFrame
theory_df = theory_ds["train"].to_pandas()

# Textbooks most likely to contain substantial nephrology / renal content
relevant_books = [
    "InternalMed_Harrison",
    "Physiology_Levy",
    "Pathology_Robbins",
    "Pathoma_Husain",
    "Anatomy_Gray",
    "Pharmacology_Katzung",
]

# Nephrology / renal keywords used for candidate selection
nephro_keywords = [
    "nephrology",
    "nephrolog",
    "renal",
    "kidney",
    "glomerul",
    "nephron",
    "glomerulonephritis",
    "nephritis",
    "nephrotic",
    "glomerulosclerosis",
    "acute kidney injury",
    "acute renal failure",
    "chronic kidney disease",
    "chronic renal failure",
    "dialysis",
    "hemodialysis",
    "peritoneal dialysis",
    "renal replacement",
    "kidney transplant",
    "renal transplant",
    "renal transplantation",
    "electrolyte",
    "acid-base",
    "hyperkalemia",
    "hypokalemia",
    "hyponatremia",
    "hypernatremia",
    "renal stone",
    "kidney stone",
    "nephrolithiasis",
    "polycystic kidney",
    "renal artery",
    "renal tubular",
    "tubulointerstitial",
]

# Restrict to selected medical textbooks
candidate_df = theory_df[
    theory_df["title"].isin(relevant_books)
].copy()

# Normalize text for case-insensitive matching
candidate_df["content_lower"] = (
    candidate_df["content"]
    .fillna("")
    .str.lower()
)

# Escape keywords before constructing the regex
keyword_pattern = "|".join(
    map(re.escape, nephro_keywords)
)

# Identify candidate nephrology chunks
candidate_df = candidate_df[
    candidate_df["content_lower"].str.contains(
        keyword_pattern,
        regex=True,
        na=False
    )
].copy()

# Remove temporary column
candidate_df.drop(columns=["content_lower"], inplace=True)

print("Candidate nephrology chunks:", len(candidate_df))

print("\nCandidate chunks by textbook:")
print(
    candidate_df["title"]
    .value_counts()
    .sort_index()
)

Candidate nephrology chunks: 6242

Candidate chunks by textbook:
title
Anatomy_Gray             136
InternalMed_Harrison    3694
Pathology_Robbins        600
Pathoma_Husain            95
Pharmacology_Katzung    1024
Physiology_Levy          693
Name: count, dtype: int64

Inspect Candidate Nephrology Content

In [10]:
# Inspect representative candidate chunks from each source textbook

sample_per_book = 3

for book in relevant_books:
    book_samples = candidate_df[
        candidate_df["title"] == book
    ].sample(
        n=min(sample_per_book, len(candidate_df[candidate_df["title"] == book])),
        random_state=42
    )

    print("\n" + "=" * 100)
    print(f"SOURCE: {book}")
    print("=" * 100)

    for i, row in book_samples.iterrows():
        print(f"\nID: {row['id']}")
        print(f"TEXT:\n{row['content'][:1500]}")
        print("-" * 100)

====================================================================================================
SOURCE: InternalMed_Harrison
====================================================================================================

ID: InternalMed_Harrison_3588
TEXT:
Immediate antagonism of the cardiac effects of hyperkalemia. Intravenous calcium serves to protect the heart, whereas other measures are taken to correct hyperkalemia. Calcium raises the action potential threshold and reduces excitability, without changing the resting membrane potential. By restoring the difference between resting and threshold potentials, calcium reverses the depolarization blockade due to hyperkalemia. The recommended dose is 10 mL of 10% calcium gluconate (3–4 mL of calcium chloride), infused intravenously over 2–3 min with cardiac monitoring. The effect of the infusion starts in 1–3 min and lasts 30–60 min; the dose should be repeated if there is no change in ECG findings or if they recur after initial improvement. Hypercalcemia potentiates the cardiac toxicity of digoxin; hence, intravenous calcium should be used with extreme caution in patients taking this medication; if judged necessary, 10 mL of 10% calcium gluconate can be added to 100 mL of 5% dextrose in
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_31113
TEXT:
than κ light chain (>2:1) in AL amyloidosis. The CSF protein is often increased (with normal cell count), and thus the neuropathy may be mistaken for CIDP (Chap. 460). Nerve biopsies reveal axonal degeneration and amyloid deposition in either a globular or diffuse pattern infiltrating the perineurial, epineurial, and endoneurial connected tissue and in blood vessel walls. The median survival of patients with primary amyloidosis is less than 2 years, with death usually from progressive congestive heart failure or renal failure. Chemotherapy with melphalan, prednisone, and colchicine, to reduce the concentration of monoclonal proteins, and autologous stem cell transplantation may prolong survival, but whether the neuropathy improves is controversial.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_3829
TEXT:
Because ED commonly involves a host of endothelial cell risk factors, men with ED report higher rates of overt and silent myocardial infarction. Therefore, ED in an otherwise asymptomatic male warrants consideration of other vascular disorders, including CAD. The physical examination is an essential element in the assessment of ED. Signs of hypertension as well as evidence of thyroid, hepatic, hematologic, cardiovascular, or renal diseases should be sought. An assessment should be made of the endocrine and vascular systems, the external genitalia, and the prostate gland. The penis should be palpated carefully along the corpora to detect fibrotic plaques. Reduced testicular size and loss of secondary sexual characteristics are suggestive of hypogonadism. Neurologic examination should include assessment of anal sphincter tone, investigation of the bulbocavernosus reflex, and testing for peripheral neuropathy.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Physiology_Levy
====================================================================================================

ID: Physiology_Levy_3479
TEXT:
When the vascular volume sensors have detected a change in ECFV, they send signals to the kidneys, which results in an appropriate adjustment in NaCl and water excretion. Accordingly, when the ECFV is expanded, renal NaCl and water excretion are increased. Conversely, when the ECFV is contracted, renal NaCl and water excretion are reduced. The signals involved in coupling the volume sensors to the kidneys are both neural and hormonal. These are summarized in Box 35.1 , as are their effects on renal NaCl and water excretion. , sympathetic nerve fibers innervate the afferent and efferent arterioles of the glomerulus as well as the cells of the nephron. With ECFV contraction, activation of the lowand high-pressure vascular baroreceptors results in stimulation of sympathetic nerve activity, including those fibers innervating the kidneys. This stimulation has the following effects: 1.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_4145
TEXT:
CYP11B1(expressedonlyinthezonafasciculata)andCYP11B2(expressedonlyinthezonaglomerulosa)arelocatedonchromosome8inhumans,display95%similarity,andareseparatedfromeachotherbyonlyabout50kilobases.Thisincreasesthepossibilityofunevencrossingoverduringgametogenesis,withtheformationofhybridgenes.Inonecasethepromoterregionand5′ endoftheCYP11B1 geneisfusedtothe3′ endoftheCYP11B2 gene.ThisarrangementleadstoaldosteronesynthasebeingexpressedinthezonaefasciculataandreticularisunderthecontrolofACTH.Becausealdosteroneisnolongerunderfeedbackcontrolbytherenin-angiotensinsystem(see ),aldosteronelevelsarehighandhypertensionensues.Thisformofprimaryaldosteronismiscalledglucocorticoid-remediable aldosteronism, anditisinheritedinanautosomaldominantmanner.Thisdiseasecanbeconfirmedbythepolymerasechainreactiontechniqueandbymeasurementof18-hydroxycortisoland18-oxicortisolina24-hoururinesample.Thediseaseistreatedbytheadministration of glucocorticoid, whichsuppressesACTHandthusexpressionofthehybridgene.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3271
TEXT:
Fig. 33.23 , endothelial cells play an important role in regulating the resistance of the renal afferent and efferent arterioles by producing a number of paracrine hormones, including NO, prostacyclin (PGI2), endothelin, and angiotensin II. These hormones regulate contraction or relaxation of smooth muscle cells in afferent and efferent arterioles and mesangial cells. Shear stress, acetylcholine, histamine, bradykinin, and ATP stimulate production of NO, which increases GFR and RBF. Angiotensin-converting enzyme (ACE), located on the surface of endothelial cells lining the afferent arteriole and glomerular capillaries, converts angiotensin I to angiotensin II, which decreases GFR and RBF. Angiotensin II is also produced locally by granular cells in the afferent arteriole and by proximal tubular cells. PGI2 and PGE2 release by endothelial cells is stimulated by both sympathetic nerve activity and angiotensin II, resulting in increased GFR and RBF. Finally, endothelin release from
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pathology_Robbins
====================================================================================================

ID: Pathology_Robbins_1138
TEXT:
While the epithelia of the body are derived from all three germ cell layers, malignant neoplasms of epithelial cells are called carcinomas regardless of the tissue of origin. Thus, malignant neoplasms arising in the renal tubular epithelium (mesoderm), the skin (ectoderm), and lining epithelium of the gut (endoderm) are all considered carcinomas. Furthermore, mesoderm may give rise to carcinomas (epithelial), sarcomas (mesenchymal), and hematolymphoid tumors (leukemias and lymphomas). Carcinomas are subdivided further. Carcinomas that grow in a glandular pattern are called adenocarcinomas, and those that produce squamous cells are called squamous cell carcinomas. Sometimes the tissue or organ of origin can be identified, as in the designation of renal cell adenocarcinoma, but it is not uncommon for tumors http://ebooksmedicine.net Fig. 6.1 Colonicpolyp.Thisglandulartumorisseenprojectingintothecoloniclumen.Thepolypisattachedtothemucosabyadistinctstalk.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_3491
TEXT:
Table 14.5 , 50% of patients who develop calcium stones have hypercalciuria that is not associated with hypercalcemia. Most patients in this group absorb calcium from the gut in excessive amounts (absorptive hypercalciuria) and promptly excrete it in the urine, and some have a primary renal defect of calcium reabsorption (renal hypercalciuria). The causes of the other types of renal stones are better understood. Magnesium ammonium phosphate (struvite) stones almost always occur in individuals with a persistently alkaline urine resulting from UTIs. In particular, infections with urea-splitting bacteria, such as Proteus vulgaris and staphylococci, predispose individuals to urolithiasis. Moreover, bacteria may serve as particulate nidi for the formation of any kind of stone. In avitaminosis A, desquamated cells from the metaplastic epithelium of the collecting system act as nidi.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_4702
TEXT:
In general, clinical manifestations of adrenocortical insufficiency do not appear until at least 90% of the adrenal cortex has been compromised. The initial manifestations often include progressive weakness and easy fatigability, which may be dismissed as nonspecific complaints. Gastrointestinal disturbances are common and include anorexia, nausea, vomiting, weight loss, and diarrhea. In patients with primary adrenal disease, increased levels of ACTH precursor hormone stimulate melanocytes, with resultant hyperpigmentation of the skin and mucosal surfaces. The face, axillae, nipples, areolae, and perineum are particularly common sites of hyperpigmentation. By contrast, hyperpigmentation is not seen in patients with secondary adrenocortical insufficiency because melanotropic hormone levels are not increased. Decreased mineralocorticoid (aldosterone) activity in patients with primary adrenal insufficiency results in potassium retention and sodium loss, with consequent hyperkalemia,
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pathoma_Husain
====================================================================================================

ID: Pathoma_Husain_394
TEXT:
C. Parathyroid adenoma is a benign neoplasm, usually involving one gland. 1. Most often results in asymptomatic hypercalcemia; however, may present with consequences of increased PTH and hypercalcemia such as i. Nephrolithiasis (calcium oxalate stones) ii. Nephrocalcinosis-metastatic calcification of renal tubules (Fig. 15.9), potentially leading to renal insufficiency and polyuria 111. CNS disturbances (e.g., depression and seizures) 1v. Constipation, peptic ulcer disease, and acute pancreatitis v. Osteitis fibrosa cystica-resorption of bone leading to fibrosis and cystic spaces (Fig. 15.10) 2. Laboratory findings include t serum PTH, t serum calcium, J,. serum phosphate, t urinary cAMP, and t serum alkaline phosphatase. 3. Treatment involves surgical removal of the affected gland. III. SECONDARY HYPERPARATHYROIDISM A. Excess production of PTH due to a disease process extrinsic to the parathyroid gland B. Most common cause is chronic renal failure. 1.
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_173
TEXT:
4. Weakening of vessel wall results in aneurysm (e.g., abdominal aorta). III. ARTERIOLOSCLEROSIS A. Narrowing of small arterioles; divided into hyaline and hyperplastic types B. Hyaline arteriolosclerosis is caused by proteins leaking into the vessel wall, producing vascular thickening; proteins are seen as pink hyaline on microscopy (Fig. 7.7). 1. 2. Results in reduced vessel caliber with end-organ ischemia; classically produces glomerular scarring (arteriolonephrosclerosis, Fig. 7.8) that slowly progresses to chronic renal failure C. Hyperplastic arteriolosclerosis involves thickening of vessel wall by hyperplasia of smooth muscle ('onion-skin' appearance, Fig. 7.9). 1. Consequence of malignant hypertension 2. Results in reduced vessel caliber with end-organ ischemia 3. May lead to fibrinoid necrosis of the vessel wall with hemorrhage; classically causes acute renal failure with a characteristic 'flea-bitten' appearance IV. MONCKEBERG MEDIAL CALCIFIC SCLEROSIS
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_401
TEXT:
i. Cardiovascular disease is the leading cause of death among diabetics. ii. Peripheral vascular disease in diabetics is the leading cause of non traumatic amputations. 2. NEG of small vessels (arterioles) leads to hyaline arteriolosclerosis (Fig. 15.13A). i. Involvement of renal arterioles leads to glomerulosclerosis, resulting in small, scarred kidneys with a granular surface (Fig. 15.13B). ii. Preferential involvement of efferent arterioles leads to glomerular hyperfiltration injury with microalbuminuria that eventually progresses to nephrotic syndrome; characterized by Kimmelstiel-Wilson nodules in glomeruli 3. NEG of hemoglobin produces glycated hemoglobin (HbA1c), a marker of glycemic control. B. Osmotic damage 1. Glucose freely enters into Schwann cells (which myelinate peripheral nerves), pericytes of retinal blood vessels, and the lens. 2. Aldose reductase converts glucose to sorbitol, resulting in osmotic damage. 3.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Anatomy_Gray
====================================================================================================

ID: Anatomy_Gray_819
TEXT:
Peritoneal metastasison surface of liverAortaInferior vena cavaLiverSpleenLeft kidney Fig. 4.58 Radiograph of subdiaphragmatic gas. Fig. 4.59 Greater omentum. Fig. 4.60 Lesser omentum. Liver (retracted )GallbladderStomachLesser omentumDuodenumDescending colonAscending colonOmental foramenLesser curvature of the stomachHepatogastric ligamentHepatoduodenal ligament Fig. 4.61 Peritoneal reflections, forming mesenteries, outlined on the posterior abdominal wall. Root of the transverse mesocolonRoot of the sigmoid mesocolonRoot of the mesentery Fig. 4.62 Abdominal esophagus. RightvagusnerveTracheaArch of aortaAortaThoracicesophagusAbdominal esophagusRight crus ofdiaphragmLeft vagus nerve Fig. 4.63 Arterial supply to the abdominal esophagus and stomach. Fig. 4.64 Stomach. Fig. 4.65 Radiograph, using barium, showing the stomach and duodenum. A. Double-contrast radiograph of the stomach. B. Double-contrast radiograph showing the duodenal cap.
----------------------------------------------------------------------------------------------------

ID: Anatomy_Gray_764
TEXT:
The rest of the superior pole is covered by the intraperitoneal stomach and spleen. Moving inferiorly, the retroperitoneal pancreas covers the middle part of the kidney. On its lateral side, the lower half of the kidney is covered by the left colic flexure and the beginning of the descending colon, and, on its medial side, by the parts of the intraperitoneal jejunum. Posteriorly, the right and left kidneys are related to similar structures (Fig. 4.151). Superiorly is the diaphragm and inferior to this, moving in a medial to lateral direction, are the psoas major, quadratus lumborum, and transversus abdominis muscles. The superior pole of the right kidney is anterior to rib XII, while the same region of the left kidney is anterior to ribs XI and XII. The pleural sacs and specifically the costodiaphragmatic recesses therefore extend posterior to the kidneys. Also passing posterior to the kidneys are the subcostal vessels and nerves and the iliohypogastric and ilio-inguinal nerves.
----------------------------------------------------------------------------------------------------

ID: Anatomy_Gray_779
TEXT:
The inferior phrenic arteries arise immediately inferior to the aortic hiatus of the diaphragm either directly from the abdominal aorta, as a common trunk from the abdominal aorta, or from the base of the celiac trunk (Fig. 4.164). Whatever their origin, they pass upward, provide some arterial supply to the suprarenal gland, and continue onto the inferior surface of the diaphragm. There are usually four pairs of lumbar arteries arising from the posterior surface of the abdominal aorta (Fig. 4.164). They run laterally and posteriorly over the bodies of the lumbar vertebrae, continue laterally, passing posterior to the sympathetic trunks and between the transverse processes of adjacent lumbar vertebrae, and reach the abdominal wall. From this point onward, they demonstrate a branching pattern similar to a posterior intercostal artery, which includes providing segmental branches that supply the spinal cord.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pharmacology_Katzung
====================================================================================================

ID: Pharmacology_Katzung_4389
TEXT:
In patients in whom the diagnosis of Cushing’s syndrome has been established clinically and confirmed by a finding of elevated free cortisol in the urine, suppression with large doses of dexamethasone will help to distinguish patients with Cushing’s disease from those with steroid-producing tumors of the adrenal cortex or with the ectopic ACTH syndrome. Dexamethasone is given in a dosage of 0.5 mg orally every 6 hours for 2 days, followed by 2 mg orally every 6 hours for 2 days, and the urine is then assayed for cortisol or its metabolites (Liddle’s test); or dexamethasone is given as a single dose of 8 mg at 11 pm, and the plasma cortisol is measured at 8 am the following day. In patients with Cushing’s disease, the suppressant effect of dexamethasone usually produces a 50% reduction in hormone levels. In patients in whom suppression does not occur, the ACTH level will be low in the presence of a cortisol-producing adrenal tumor and elevated in patients with an ectopic ACTH-producing
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_2680
TEXT:
Volatile anesthetics also raise the apneic threshold (Paco2 level below which apnea occurs through lack of CO2-driven respiratory stimulation) and decrease the ventilatory response to hypoxia. Clinically, the respiratory depressant effects of anesthetics are overcome by assisting (controlling) ventilation mechanically. The ventilatory depression produced by inhaled anesthetics may be counteracted by surgical stimulation; however, low, subanesthetic concentrations of volatile anesthetic present after surgery in the early recovery period can continue to depress the compensatory increase in ventilation normally caused by hypoxia. Inhaled anesthetics also depress mucociliary function in the airway. During prolonged exposure to inhaled anesthetics, mucus pooling and plugging may result in atelectasis and the development of postoperative respiratory complications, including hypoxemia and respiratory infections. D. Renal Effects
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_3960
TEXT:

In [11]:
# Stronger nephrology-specific terms for second-stage filtering

strong_nephro_keywords = [
    "glomerul",
    "nephron",
    "nephritis",
    "nephrotic",
    "nephropathy",
    "nephrolithiasis",
    "glomerulosclerosis",
    "glomerulonephritis",
    "acute kidney injury",
    "acute renal failure",
    "chronic kidney disease",
    "chronic renal failure",
    "end-stage renal",
    "end stage renal",
    "renal replacement therapy",
    "renal replacement",
    "hemodialysis",
    "haemodialysis",
    "peritoneal dialysis",
    "dialysis",
    "kidney transplant",
    "renal transplant",
    "renal transplantation",
    "renal tubular",
    "tubular acidosis",
    "tubulointerstitial",
    "renal artery",
    "renal vein",
    "renal blood flow",
    "glomerular filtration",
    "glomerular filtration rate",
    "glomerular capillary",
    "glomerular disease",
    "renal stone",
    "kidney stone",
    "renal calcul",
    "polycystic kidney",
    "renal failure",
    "renal insufficiency",
    "renal disease",
    "renal physiology",
    "renal pathology",
]

strong_pattern = "|".join(
    map(re.escape, strong_nephro_keywords)
)

# Apply the stronger filter to the existing candidate pool
candidate_df["content_lower"] = (
    candidate_df["content"]
    .fillna("")
    .str.lower()
)

nephro_df = candidate_df[
    candidate_df["content_lower"].str.contains(
        strong_pattern,
        regex=True,
        na=False
    )
].copy()

nephro_df.drop(columns=["content_lower"], inplace=True)

print("Initial candidate chunks:", len(candidate_df))
print("Stronger nephrology candidates:", len(nephro_df))

print("\nCandidates by textbook:")
print(
    nephro_df["title"]
    .value_counts()
    .sort_index()
)

Initial candidate chunks: 6242
Stronger nephrology candidates: 3148

Candidates by textbook:
title
Anatomy_Gray              42
InternalMed_Harrison    2023
Pathology_Robbins        310
Pathoma_Husain            58
Pharmacology_Katzung     431
Physiology_Levy          284
Name: count, dtype: int64

Validate the Refined Nephrology Candidates

In [12]:
# Inspect representative examples from the refined nephrology candidate set

sample_per_book = 5

for book in relevant_books:
    book_df = nephro_df[nephro_df["title"] == book]

    if len(book_df) == 0:
        continue

    samples = book_df.sample(
        n=min(sample_per_book, len(book_df)),
        random_state=42
    )

    print("\n" + "=" * 100)
    print(f"SOURCE: {book} | CANDIDATES: {len(book_df)}")
    print("=" * 100)

    for _, row in samples.iterrows():
        print(f"\nID: {row['id']}")
        print(f"TEXT:\n{row['content'][:1800]}")
        print("-" * 100)

====================================================================================================
SOURCE: InternalMed_Harrison | CANDIDATES: 2023
====================================================================================================

ID: InternalMed_Harrison_16276
TEXT:
The diminished effectiveness of eflornithine against T. b. rhodesiense appears to be due to the parasite’s ability to replace the inhibited enzyme more rapidly than T. b. gambiense. Eflornithine is less toxic but more costly than conventional therapy. It can be administered IV or PO. The dose should be reduced in renal failure. Eflornithine readily crosses the blood-brain barrier; CSF levels are highest in persons with the most severe central nervous system (CNS) involvement.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_21539
TEXT:
The urinalysis and urine sediment examination are invaluable tools, but they require clinical correlation because of generally limited sensitivity and specificity (Fig. 334-6) (Chap. 62e). In the absence of preexisting proteinuria from CKD, AKI from ischemia or nephrotoxins leads to mild proteinuria (<1 g/d). Greater proteinuria in AKI suggests damage to the glomerular ultrafiltration barrier or excretion of myeloma light chains; the latter are not detected with conventional urine dipsticks (which detect albumin) and require the sulfosalicylic acid test or immunoelectrophoresis. Atheroemboli can cause a variable degree of proteinuria. Extremely heavy proteinuria (“nephrotic range,” >3.5 g/d) can occasionally be seen in glomerulonephritis, vasculitis, or interstitial nephritis (particularly from NSAIDs). AKI can also complicate cases of minimal change disease, a cause of the nephrotic syndrome (Chap. 332e). If the dipstick is positive for hemoglobin but few red blood cells are evident
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_18294
TEXT:
Anemia is common in heart failure patients, reduces functional status and quality of life, and is associated with increased proclivity for hospital admissions and mortality. Anemia in heart failure is more common in the elderly, in those with advanced stages of HFrEF, in the presence of renal insufficiency, and in women and African Americans. The mechanisms include iron deficiency, dysregulation of iron metabolism, and occult gastrointestinal bleeding. Intravenous iron using either iron sucrose or carboxymaltose (Ferric Carboxymaltose Assessment in Patients with Iron Deficiency and Chronic Heart Failure [FAIR-HF] trial) has been shown to correct anemia and improve functional capacity. Erythropoiesis-regulating agents such as erythropoietin analogues have been studied with disappointing results. The Reduction of Events by Darbepoetin Alfa in Heart Failure (RED-HF) trial evaluated 2278 mild-to-moderate anemia patients with HFrEF and demonstrated that treatment with darbepoetin alfa did
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_13618
TEXT:
MechanisM of action Ethambutol is bacteriostatic against M. tuberculosis. Its primary mechanism of action is the inhibition of the arabinosyltransferases involved in cell wall synthesis, which probably inhibits the formation of arabinogalactan and lipoarabinomannan. The MIC of ethambutol for susceptible strains of M. tuberculosis is 0.5–2 μg/mL. PharMacology anD Dosing From a single dose of ethambutol, 75–80% is absorbed within 2–4 h of administration. Serum levels peak at 2–4 μg/mL after the standard adult daily dose of 15 mg/kg. Ethambutol is well distributed throughout the body except in the CSF; a dosage of 25 mg/kg is necessary for attainment of a CSF level half of that in serum. For intermittent therapy, the dosage is 50 mg/kg twice weekly. To prevent toxicity, the dosage must be lowered and the frequency of administration reduced for patients with renal insufficiency.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_12873
TEXT:
Other systems may be involved in a manner that resembles typhoid. About one-quarter of patients have a dry cough, usually with few changes visible on the chest x-ray, although pneumonia, empyema, intrathoracic adenopathy, or lung abscess can occur. Sputum or pleural effusion cultures are rarely positive in such cases, which respond well to standard brucellosis treatment. One-quarter of patients have hepatosplenomegaly, and 10–20% have significant lymphadenopathy; the differential diagnosis includes glandular fever–like illness such as that caused by Epstein-Barr virus, Toxoplasma, cytomegalovirus, HIV, or Mycobacterium tuberculosis. Up to 10% of men have acute epididymoorchitis, which must be distinguished from mumps and from surgical problems such as torsion. Prostatitis, inflammation of the seminal vesicles, salpingitis, and pyelonephritis all occur. There is an increased incidence of fetal loss among infected pregnant women, although teratogenicity has not been described and the
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Physiology_Levy | CANDIDATES: 284
====================================================================================================

ID: Physiology_Levy_196
TEXT:
Fig. 2.13B ), in which the transepithelial secretion of NaCl establishes a transepithelial osmotic pressure gradient that drives water secretion. In some epithelia (e.g., proximal tubule of the renal nephron), the movement of water across the epithelium via the paracellular pathway can drive the movement of additional solute. This process is termed solvent drag and reflects the fact that solutes dissolved in the water will traverse the tight junction with the water. As is the case with the establishment of transepithelial concentration and voltage gradients, the establishment of transepithelial osmotic pressure gradients requires transcellular transport of solutes by the epithelial cells. iDifferent aquaporin isoforms are often expressed in the apical and basolateral membrane. In addition, multiple isoforms may be expressed in one or more of the membrane domains. CHAPTER 2 Homeostasis: Volume and Composition of Body Fluid Compartments
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3693
TEXT:
Fig. 37.9). The new HCO3 − generated during the process of net acid excretion is added to the body, and the plasma [HCO3 −] increases. When metabolic alkalosis exists (decreased [H+]), the filtered load of HCO3 − is increased (plasma [HCO3 −] is elevated). With respiratory alkalosis (decreased PCO2), plasma [HCO3 −] is decreased and thus the filtered load is decreased. In both conditions, secretion of H+ by the nephron is inhibited. As a result, HCO3 − excretion is increased. At the same time, excretion of both titratable acid and NH4 + is decreased. Thus RNAE is decreased and HCO3 − appears in urine. Also, some HCO3 − is secreted into urine by the HCO3 −-secreting intercalated cells of the distal tubule and collecting duct. With enhanced excretion of HCO3 − , plasma [HCO3 −] decreases. •Fig. 37.9 Responseofthenephrontoacidosis.Pi,phosphate;PTH,parathyroidhormone;Rhbg&Rhcg,rhesusglycoproteins;RNAE,renalnetacidexcretion;TA,titratableacid;V,urineflowrate.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3427
TEXT:
Excretion of hypoosmotic urine is relatively easy to understand. The nephron must simply reabsorb solute from the tubular fluid and not allow water reabsorption to also occur. As just noted, and as described in greater detail later, reabsorption of solute without concomitant water reabsorption occurs in the ascending limb of Henle’s loop. Under appropriate conditions (i.e., in the absence of AVP) the distal tubule and collecting duct also dilute the tubular fluid by reabsorbing solute but not water. Excretion of hyperosmotic urine is more complex and thus more difficult to understand. This process in essence
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3524
TEXT:
Mount DB. Thick ascending limb of the loop of Henle. Clin J Am Soc Nephrol. 2014;9:1974-1986. Palmer LG, Schnermann J. Integrated control of Na transport along the nephron. Clin J Am Soc Nephrol. 2015;10:676-687. Pearce D, et al. Aldosterone regulation of transport. In: Taal MW, et al., eds. Brenner and Rector’s The Kidney. 9th ed. Philadelphia: Saunders; 2012. Pearce D, et al. Collecting duct principal cell transport processes and their regulation. Clin J Am Soc Nephrol. 2015;10:135-146. Slotki IN, Skorecki KL. Disorders of sodium balance. In: Taal MW, et al., eds. Brenner and Rector’s The Kidney. 9th ed. Philadelphia: Saunders; 2012. Staub O, Loffing J. Mineralocorticoid action in aldosterone sensitive distal nephron. In: Alpern RJ, et al., eds. Seldin and Giebisch’s The Kidney: Physiology and Pathophysiology. 5th ed. Philadelphia: Academic Press; 2013. Subramanya AR, Ellison DH. Distal convoluted tubule. Clin J Am Soc Nephrol. 2014;9:2147-2163.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3212
TEXT:
Innervation of the Kidneys Renal nerves regulate RBF, GFR, and salt and water reabsorption by the nephron. The nerve supply to the kidneys consists of sympathetic nerve fibers that originate in the celiac plexus. There is no corresponding parasympathetic innervation. Adrenergic fibers innervating the kidneys release norepinephrine and lie adjacent to the smooth muscle cells of the major branches of the renal artery (interlobar, arcuate, and interlobular arteries) as well as the afferent and efferent arterioles. In addition, sympathetic nerves innervate the renin-producing granular cells of the afferent arterioles. Renin secretion is stimulated by increased sympathetic activity. Nerve fibers also innervate the proximal tubule, loop of Henle, distal tubule, and collecting duct; activation of these nerves enhances Na+ reabsorption by these nephron segments. Assessment of Renal Function
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pathology_Robbins | CANDIDATES: 310
====================================================================================================

ID: Pathology_Robbins_4653
TEXT:
• Diabetic patients are plagued by an increased susceptibility to infections of the skin, tuberculosis, pneumonia, and pyelonephritis. Infections cause about 5% of diabetes-related deaths. In an individual with diabetic neuropathy, a trivial infection in a toe may be the first event in a long succession of complications (gangrene, bacteremia, pneumonia) that may ultimately lead to death.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_646
TEXT:
• Anti-phospholipid antibody syndrome. This syndrome (previously called the lupus anti-coagulant syndrome) has protean clinical manifestations, including recurrent thromboses, repeated miscarriages, cardiac valve vegetations, and thrombocytopenia. Depending on the vascular bed involved, the clinical presentations can include pulmonary embolism (following lower extremity venous thrombosis), pulmonary hypertension (from recurrent subclinical pulmonary emboli), stroke, bowel infarction, or renovascular hypertension. Fetal loss does not appear to be explained by thrombosis, but rather seems to stem from antibody-mediated interference with the growth and differentiation of trophoblasts, leading to a failure of placentation. Anti-phospholipid antibody syndrome is also a cause of renal microangiopathy, resulting in renal failure associated with multiple capillary and arterial thromboses (Chapter 14).
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_1441
TEXT:
Staging. The staging of solid cancers is based on the size of the primary lesion, its extent of spread to regional lymph nodes, and the presence or absence of blood-borne metastases. The major staging system currently in use is the American Joint Committee on Cancer Staging. This system uses a classification called the TNM system—T for primary tumor, N for regional lymph node involvement, and M for metastases. TNM staging varies for specific forms of cancer, but there are general principles. The primary lesion is characterized as T1 to T4 based on increasing size. T0 is used to indicate an in situ http://ebooksmedicine.net MyastheniaBronchogeniccarcinoma,thymomaImmunologic DisordersofthecentralandperipheralBreastcarcinoma,teratomaImmunologicnervoussystems Osseous, Articular, and Soft-Tissue Changes NephroticsyndromeVariouscancersTumorantigens,immunecomplexes ACTH, Adrenocorticotropichormone;IL-1, interleukin-1;TGF-α, transforminggrowthfactor-α;TNF, tumornecrosisfactor.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_1770
TEXT:
MORPHOLOGYWilmstumortypicallyisalarge,solitary,well-circumscribedmass,although10%areeitherbilateralormulticentricatthetimeofdiagnosis.Oncutsection,thetumorissoft,homogeneous,andtantogray,withoccasionalfociofhemorrhage,cysticdegeneration,andnecrosis( Fig.7.36 Onmicroscopicexamination,Wilmstumorsarecharacterizedbyrecognizableattemptstorecapitulatedifferentstagesofnephrogenesis.Theclassictriphasic combination ofblastemal,stromal,andepithelialcelltypesisobservedinmostlesions,althoughthepercentageofeachcomponentisvariable( Fig. 7.37A ).Sheetsofsmallbluecells,withfewdistinctivefeatures,characterizetheblastemal component.Epithelial“differentiation”usuallytakestheformofabortive tubules or glomeruli.Stromalcellsareusuallyfibrocyticormyxoidinnature,althoughskeletalmuscle“differentiation”isnotuncommon.Approximately5%oftumorscontainfociofanaplasia (cellswithlarge,hyperchromatic,pleomorphicnucleiandabnormalmitoses)( Fig.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_908
TEXT:
Kidney. Upto50%ofSLEpatientshaveclinicallysignificantrenalinvolvement,andthekidneyvirtuallyalwaysshowsevidenceofabnormalityifexaminedbyelectronmicroscopyandimmunofluorescence.Renalinvolvementtakesanumberofforms,all Table 5.12 Clinical and Pathologic Manifestations of Systemic Lupus Erythematosus Arthritis,arthralgia,ormyalgia80–90 *Percentagesareapproximateandmayvarywithage,ethnicity,andotherfactors.TablecompiledwiththeassistanceofDr.MeenakshiJolly,RushMedicalCenter,Chicago. ofwhichareassociatedwiththedepositionofimmunecomplexeswithintheglomeruli.Accordingtothecurrentlyacceptedclassification,sixpatternsofglomerulardiseasearerecognized.Itshouldbenotedthatthereisoverlapwithintheseclassesandthatlesionsmayevolvefromoneclasstoanotherovertime.Thus,theexactpercentageofpatientswitheachofthesixclassesoflesionsisdifficulttodetermine.SufficeittosaythatclassIistheleastcommonandclassIVisthemostcommonpattern.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pathoma_Husain | CANDIDATES: 58
====================================================================================================

ID: Pathoma_Husain_6
TEXT:
A. Cellular injury occurs when a stress exceeds the cell's ability to adapt. B. The likelihood ofinjury depends on the type of stress, its severity, and the type of cell affected. 1. Neurons are highly susceptible to ischemic injury; whereas, skeletal muscle is relatively more resistant. 2. Slowly developing ischemia (e.g., renal artery atherosclerosis) results in atrophy; whereas, acute ischemia (e.g., renal artery embolus) results in injury. C. Common causes of cellular injury include inflammation, nutritional deficiency or excess, hypoxia, trauma, and genetic mutations. II. HYPOXIA A. Low oxygen delivery to tissue; important cause ofcellular injury 1. Oxygen is the final electron acceptor in the electron transport chain of oxidative phosphorylation. 2. Decreased oxygen impairs oxidative phosphorylation, resulting in decreased ATP production. 3. Lack of ATP (essential energy source) leads to cellular injury.
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_82
TEXT:
C. TTP is due to decreased ADAMTS13, an enzyme that normally cleaves vWF multimers into smaller monomers for eventual degradation. Fig. 4.1 Petechiae involving skin. Fig. 4.2 Schistocyte. 1. Large, uncleaved multimers lead to abnormal platelet adhesion, resulting in microthrombi. 2. Decreased ADAMTS13 is usually due to an acquired autoantibody; most commonly seen in adult females D. HUS is due to endothelial damage by drugs or infection. 1. Classically seen in children with E coli 0157:H? dysentery, which results from exposure to undercooked beef 2. E coli verotoxin damages endothelial cells resulting in platelet microthrombi. E. Clinical findings (HUS and TTP) include 1. 2. 3. 4. Renal insufficiency (more common in HUS)-Thrombi involve vessels of the kidney. 5. CNS abnormalities (more common in TTP)-Thrombi involve vessels of the CNS. F. Laboratory findings include 1. Thrombocytopenia with t bleeding time 2. Normal PT/PTT (coagulation cascade is not activated) 3.
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_320
TEXT:
C. Leads to cortical scarring with blunted calyces; scarring at upper and lower poles is characteristic of vesicoureteral reflux. D. Atrophic tubules containing eosinophilic proteinaceous material resemble thyroid follicles ('thyroidization' of the kidney, Fig. 12.17); waxy casts may be seen in urine. I. BASIC PRINCIPLES A. Precipitation of a urinary solute as a stone (Table 12.2) B. Risk factors include high concentration of solute in the urinary filtrate and low urine volume. C. Presents as colicky pain with hematuria and unilateral flank tenderness 1. Stone is usually passed within hours; if not, surgical intervention may be required. I. BASIC PRINCIPLES A. End-stage kidney failure 1. May result from glomerular, tubular, inflammatory, or vascular insults 2. Most common causes are diabetes mellitus, hypertension, and glomerular disease. B. Clinical features 1.
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_170
TEXT:

# 7.5 Clean and Prepare the Training Text

After identifying candidate nephrology content, we now prepare the selected text for use in supervised fine-tuning.

The objective is to retain useful medical knowledge while removing records that are unsuitable or likely to introduce noise into the training process.

### Cleaning steps

The preprocessing stage will examine the selected records for:

- missing or empty text;
- duplicate passages;
- extremely short or excessively long passages;
- malformed records;
- unnecessary formatting or metadata; and
- passages that do not contain meaningful educational content.

We will preserve the original educational meaning of the source material while applying only transformations necessary for training-data preparation.

### Why cleaning matters

Fine-tuning quality depends not only on the quantity of training data but also on the consistency and usefulness of the examples.

Removing duplicates and unusable records helps prevent the model from receiving repeated or low-information training examples.

At the same time, we avoid aggressive preprocessing that could remove medically meaningful terminology or context.

**Expected outcome:** a cleaned set of nephrology-focused educational passages suitable for conversion into instruction-response training examples.

In [13]:
# Basic cleaning and quality checks for the nephrology candidate corpus

import re
import pandas as pd

clean_df = nephro_df.copy()

# Normalize whitespace while preserving the original medical content
clean_df["content_clean"] = (
    clean_df["content"]
    .fillna("")
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# Basic text statistics
clean_df["char_count"] = clean_df["content_clean"].str.len()
clean_df["word_count"] = clean_df["content_clean"].str.split().str.len()

print("Initial nephrology candidates:", len(clean_df))

print("\nMissing / empty content:")
print(
    (clean_df["content_clean"].str.len() == 0).sum()
)

print("\nText length statistics:")
print(
    clean_df["word_count"].describe()
)

print("\nVery short passages (<50 words):")
print(
    (clean_df["word_count"] < 50).sum()
)

print("\nVery long passages (>1500 words):")
print(
    (clean_df["word_count"] > 1500).sum()
)

print("\nDuplicate passages:")
print(
    clean_df["content_clean"].duplicated().sum()
)

Initial nephrology candidates: 3148

Missing / empty content:
0

Text length statistics:
count    3148.000000
mean      110.871982
std        35.102878
min         1.000000
25%        90.000000
50%       121.000000
75%       138.000000
max       178.000000
Name: word_count, dtype: float64

Very short passages (<50 words):
236

Very long passages (>1500 words):
0

Duplicate passages:
0

inspect short passages

In [14]:
# Inspect short nephrology passages before deciding whether to exclude them

short_df = clean_df[
    clean_df["word_count"] < 50
].copy()

print("Short passages:", len(short_df))

print("\nShort passages by textbook:")
print(
    short_df["title"]
    .value_counts()
    .sort_index()
)

print("\nRepresentative short passages:")

for book in relevant_books:
    book_samples = short_df[
        short_df["title"] == book
    ]

    if len(book_samples) == 0:
        continue

    samples = book_samples.sample(
        n=min(5, len(book_samples)),
        random_state=42
    )

    print("\n" + "=" * 100)
    print(f"SOURCE: {book}")
    print("=" * 100)

    for _, row in samples.iterrows():
        print(f"\nID: {row['id']}")
        print(f"WORDS: {row['word_count']}")
        print(f"TEXT: {row['content_clean']}")
        print("-" * 100)

Short passages: 236

Short passages by textbook:
title
InternalMed_Harrison    126
Pathology_Robbins        78
Pharmacology_Katzung     16
Physiology_Levy          16
Name: count, dtype: int64

Representative short passages:

====================================================================================================
SOURCE: InternalMed_Harrison
====================================================================================================

ID: InternalMed_Harrison_21867
WORDS: 44
TEXT: The subject of lupus nephritis is presented under acute nephritic syndromes because of the aggressive and important proliferative lesions seen in class III–V renal disease. Class III describes focal lesions Note: Revised in 2004 by the International Society of Nephrology-Renal Pathology Society Study Group.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_10627
WORDS: 43
TEXT: supported these laboratory results, and antibiotics may increase by twentyfold the risk of hemolytic-uremic syndrome and renal failure during enterohemorrhagic E. coli infection. A clinical clue in the diagnosis of the latter infection is bloody diarrhea with low fever or none at all.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_28515
WORDS: 47
TEXT: Disorders of the Parathyroid Gland and Calcium Homeostasis The diagnosis is typically made by detecting an elevated immunoreactive PTH level in a patient with asymptomatic hypercalcemia (see “Differential Diagnosis: Special Tests,” below). Serum phosphate is usually low but may be normal, especially if renal failure has developed.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_21836
WORDS: 33
TEXT: necrosis, hypercalciuria, renal stones, cystic kidney diseases, or renal vascular injury. However, when red blood cell casts (see Fig. 62e-34) or dysmorphic red blood cells are found in the sediment, glomerulonephritis is likely.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_25035
WORDS: 20
TEXT: Renal Failure Arthritis Artherosclerosis Leukopenia EPIGENETIC CHANGES Pulm fibrosisCNS dz(DNA hypomethylation, 3.Autoantibodies Stroke miRNA) Clotting Etc. Etc. ?Infection Others EBV
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Physiology_Levy
====================================================================================================

ID: Physiology_Levy_79
WORDS: 8
TEXT: Glucoseistransportedbytheepithelialcellsthatlinethegastrointestinaltract(smallintestine),andbycellsthatformtheproximaltubulesofthekidneys.Inthegastrointestinaltract,theglucoseisabsorbedfromingestedfood.Inthekidney,theproximaltubulereabsorbstheglucosethatwasfilteredacrosstheglomerularcapillariesandtherebypreventsitfrombeinglostintheurine.Theuptakeofglucoseintotheepithelialcellfromthelumenofthesmallintestineandfromthelumenoftheproximaltubuleisasecondaryactiveprocessinvolvingthesodium-glucose–linkedtransportersSGLT-1andSGLT-2.SGLT-2transportsoneglucosemoleculewithoneNa+ ion,andtheenergyintheelectrochemicalgradientforNa+ (intothecell)drivesthesecondaryactiveuptakeofglucose.Accordingtothefollowingequation,forcalculatingtheelectrochemicalgradient,andifthemembranepotential(Vm)is−60mVandthereisa10-fold[Na+]gradientacrossthemembrane,anapproximate100-foldglucosegradientcouldbegeneratedbySGLT-2:[Glucose]i [Na+ ]o V 615. mV
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_177
WORDS: 7
TEXT: Thefunctionofclaudinscanberegulatedatseverallevels,includinggeneexpression,posttranslationalmodification,interactionswithcytoplasmicscaffoldingproteins,andinteractionswithotherclaudinsinthesamemembrane(cis-interaction),aswellaswithclaudinsofadjacentcells(trans-interaction).ThemineralocorticoidhormonealdosteronestimulatesNa+ reabsorptionbydistalsegmentsoftherenalnephron(see ).Inadditiontothehormone’seffectonNa+ transportersinthecell,aldosteronealsoupregulatesexpressionofclaudin8inthetightjunction.Theincreasedexpressionofclaudin8reducestheabilityofNa+ topermeatethetightjunction,whichthenreducesthebackwardsleakofNa+ fromtheinterstitiumintothetubulelumen,therebyallowingmoreefficientNa+ reabsorptionbytheepithelium.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_2305
WORDS: 6
TEXT: Fig.19.10 ,therefore,theequilibriumpointshiftsfromtheintersection(pointA)ofthenormalcurvestotheintersection(pointBorpointC)ofthenormalvascularfunctioncurve. Chronicheartfailuremayoccurinconditionssuchasessentialhypertensionorischemicheartdisease.Inchronicheartfailure,boththecardiacfunctionandvascularfunctioncurvesshift.Thevascularfunctioncurveshiftsbecauseofanincreaseinbloodvolumecausedinpartbyfluidretentionbythekidneys.ThefluidretentionisrelatedtotheconcomitantreductioninglomerularfiltrationrateandthedecreasedrenalexcretionofNaClandwater(seealso ).Theresultanthypervolemiaisreflectedbyarightwardshiftofthevascularfunctioncurve,asshownin Fig.19.10. Hence,withmoderatedegreesofheartfailure,Pviselevated,butcardiacoutputmaybenormal(pointD).Withmoreseveredegreesofheartfailure,Pvisstillelevated,butcardiacoutputissubnormal(pointE).
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_4145
WORDS: 11
TEXT: CYP11B1(expressedonlyinthezonafasciculata)andCYP11B2(expressedonlyinthezonaglomerulosa)arelocatedonchromosome8inhumans,display95%similarity,andareseparatedfromeachotherbyonlyabout50kilobases.Thisincreasesthepossibilityofunevencrossingoverduringgametogenesis,withtheformationofhybridgenes.Inonecasethepromoterregionand5′ endoftheCYP11B1 geneisfusedtothe3′ endoftheCYP11B2 gene.ThisarrangementleadstoaldosteronesynthasebeingexpressedinthezonaefasciculataandreticularisunderthecontrolofACTH.Becausealdosteroneisnolongerunderfeedbackcontrolbytherenin-angiotensinsystem(see ),aldosteronelevelsarehighandhypertensionensues.Thisformofprimaryaldosteronismiscalledglucocorticoid-remediable aldosteronism, anditisinheritedinanautosomaldominantmanner.Thisdiseasecanbeconfirmedbythepolymerasechainreactiontechniqueandbymeasurementof18-hydroxycortisoland18-oxicortisolina24-hoururinesample.Thediseaseistreatedbytheadministration of glucocorticoid, whichsuppressesACTHandthusexpressionofthehybridgene.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_4142
WORDS: 46
TEXT: The thin outermost zone of the adrenal, the zona glomerulosa, produces the mineralocorticoid aldosterone, which regulates salt and volume homeostasis (see ). The zona glomerulosa is minimally influenced by ACTH. Rather it is regulated primarily by the reninangiotensin system, plasma [K+], and atrial natriuretic peptide (ANP).
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pathology_Robbins
====================================================================================================

ID: Pathology_Robbins_3338
WORDS: 35
TEXT: By contrast, nephritic syndrome is characterized by the following: Proteinuria (usually in the subnephrotic range) with or without edema The nephritic syndrome usually has an acute onset and is caused by inflammatory lesions of glomeruli.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_592
WORDS: 15
TEXT: Subcutaneous edema canbediffusebutusuallyaccumulatespreferentiallyinpartsofthebodypositionedthegreatestdistancebelowtheheart,wherehydrostaticpressuresarehighest.Thus,edematypicallyismostpronouncedinthelegswithstandingandthesacrumwithrecumbency,arelationshiptermeddependent edema. Fingerpressureoveredematoussubcutaneoustissuedisplacestheinterstitialfluid,leavingafinger-shapeddepression;thisappearanceiscalledpitting edema. Edemaresultingfromrenal dysfunction ornephrotic syndrome oftenmanifestsfirstinlooseconnectivetissues(e.g.,theeyelids,causingperiorbitaledema).Withpulmonary edema, thelungsoftenaretwotothreetimestheirnormalweight,andsectioningshowsfrothy,sometimesblood-tingedfluidconsistingofamixtureofair,edemafluid,andextravasatedredcells.Brain edema (Chapter23)canbelocalized(e.g.,becauseofabscessortumor)orgeneralized,dependingonthenatureandextentofthepathologicprocessorinjury.Withgeneralizededema,thesulciarenarrowedasthegyriswellandbecomeflattenedagainsttheskull.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_3350
WORDS: 13
TEXT: Fig. 14.3 Antibody-mediatedglomerularinjury.Injurycanresulteitherfromthedepositionofcirculatingimmunecomplexesorfromantibody-bindingtoglomerularcomponentsfollowedbyformationofcomplexesinsitu.Depositionofcirculatingimmunecomplexesgivesagranularimmunofluorescencepattern.Anti-glomerularbasementmembrane(anti-GBM)antibodyglomerulonephritisischaracterizedbyalinearimmunofluorescencepattern;thereisnoimmunedepositformationinthisdisease. antigen is unknown, as in most cases of membranoproliferative GN.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_914
WORDS: 12
TEXT: Advanced sclerosing lupus nephritis (classVI)ischaracterizedbysclerosisofmorethan90%oftheglomeruli,andrepresentsend-stagerenaldisease. Changesintheinterstitium and tubules arefrequentlypresent.Rarely,tubulointerstitiallesionsmaybethedominantabnormality.Discreteimmunecomplexessimilartothoseinglomeruliarepresentinthetubularorperitubularcapillarybasementmembranesinmanylupusnephritispatients.Sometimes,therearewell-organizedB-cellfolliclesintheinterstitium,associatedwithplasmacellsthatmaybesourcesofautoantibodies. Skin. Characteristicerythemaaffectsthefacealongthebridgeofthenoseandcheeks(thebutterfly rash)inapproximately50%ofpatients,butasimilarrashalsomaybeseenontheextremitiesandtrunk.Urticaria,bullae,maculopapularlesions,andulcerationsalsooccur.Exposuretosunlightincitesoraccentuatestheerythema.Histologicallytheinvolvedareasshowvacuolardegenerationofthebasallayeroftheepidermis(
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_912
WORDS: 34
TEXT: Hospital, Boston, Massachusetts. D,Courtesy of Dr. Edwin Eigenbrodt, Department of Pathology, University of Texas, Southwestern Medical School, Dallas,Texas. E,Courtesy of Dr. Jean Olson, Department of Pathology, University of California, San Francisco, California.) http://ebooksmedicine.net nephritis,halformoreoftheglomeruliareaffected.Involvedglomerulishowproliferationofendothelial,mesangial,andepithelialcells(see
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pharmacology_Katzung
====================================================================================================

ID: Pharmacology_Katzung_372
WORDS: 33
TEXT: bound to plasma proteins and may not be readily filtered at the glomerulus. Consequently, most drugs would have a prolonged duration of action if termination of their action depended solely on renal excretion.
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_1032
WORDS: 28
TEXT: action. Potassium-sparing diuretics may produce hyperkalemia, particularly in patients with renal insufficiency and those taking ACE inhibitors or angiotensin receptor blockers; spironolactone (a steroid) is associated with gynecomastia.
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_1847
WORDS: 46
TEXT: are resistant hypertension, chronic renal disease, connective tissue disease, and subarachnoid hemorrhage. On the other hand, clinical trials of the drugs in the treatment of heart failure have been disappointing. Thus, at present, pulmonary arterial hypertension remains the only clinical condition approved for endothelin receptor antagonists.
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_6421
WORDS: 31
TEXT: vigorous hydration, and, in the case of acute renal failure, hemodialysis—is the mainstay of therapy. Currently available chelating agents have not been demonstrated to be of clinical value in arsine poisoning.
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_5532
WORDS: 38
TEXT: whereas rimantadine undergoes extensive metabolism by hydroxylation, conjugation, and glucuronidation before urinary excretion. Dose reductions are required for both agents in the elderly and in patients with renal insufficiency, and for rimantadine in patients with severe hepatic insufficiency.
----------------------------------------------------------------------------------------------------

remove obvious structural noise and duplicates

We'll first remove only clearly unusable records:

empty text;
extremely tiny fragments (<10 words);
obvious figure/table fragments;
duplicate text.

We will keep passages of 10+ words for now, even if they're short, because some contain dense nephrology knowledge.

In [15]:
# Apply conservative cleaning rules to the nephrology candidate corpus

before_count = len(clean_df)

# Remove empty passages
clean_df = clean_df[
    clean_df["content_clean"].str.len() > 0
].copy()

# Remove extremely short fragments
# We keep passages with >=10 words because some short passages
# contain dense nephrology concepts.
clean_df = clean_df[
    clean_df["word_count"] >= 10
].copy()

# Remove exact duplicate passages
clean_df = clean_df.drop_duplicates(
    subset=["content_clean"]
).copy()

# Reset index after filtering
clean_df.reset_index(drop=True, inplace=True)

after_count = len(clean_df)

print("Candidate passages before cleaning:", before_count)
print("Candidate passages after cleaning:", after_count)
print("Removed passages:", before_count - after_count)

print("\nRemaining passages by textbook:")
print(
    clean_df["title"]
    .value_counts()
    .sort_index()
)

print("\nRemaining word-count statistics:")
print(
    clean_df["word_count"].describe()
)

Candidate passages before cleaning: 3148
Candidate passages after cleaning: 3113
Removed passages: 35

Remaining passages by textbook:
title
Anatomy_Gray              42
InternalMed_Harrison    2021
Pathology_Robbins        282
Pathoma_Husain            58
Pharmacology_Katzung     431
Physiology_Levy          279
Name: count, dtype: int64

Remaining word-count statistics:
count    3113.000000
mean      112.058786
std        33.455656
min        10.000000
25%        91.000000
50%       121.000000
75%       138.000000
max       178.000000
Name: word_count, dtype: float64

# 7.6 Convert Theory into Instruction-Response Examples

The cleaned nephrology passages are still raw educational text. We now transform them into structured **instruction-response examples** suitable for supervised fine-tuning.

The objective is to teach Llama 3.2 3B Instruct to use nephrology knowledge when responding to educational prompts rather than simply memorizing isolated text passages.

### Example structure

Each training example will follow a simple instruction-response format:

```text
Instruction:
Explain the role of the glomerulus in renal filtration.

Response:
The glomerulus is a network of specialized capillaries...

**Why are we converting to Instruction response format ?**

Because Llama 3.2 3B Instruct is an instruction-tuned model, and our goal is not simply to make it memorize textbook passages. We want QLoRA to improve its ability to answer nephrology questions and explain nephrology concepts.

There are two different training approaches:
| Approach                         | What the model sees                  | What it teaches                                                 |
| -------------------------------- | ------------------------------------ | --------------------------------------------------------------- |
| Raw text / continued pretraining | `"The glomerulus filters plasma..."` | More exposure to nephrology language/knowledge                  |
| Instruction-response SFT         | **Question → Answer**                | How to use nephrology knowledge to answer educational questions |

**Identify Passages Suitable for Instruction Generation**

Before generating instruction-response pairs, let's first identify passages that contain enough coherent nephrology information to support an educational question and answer.

For this step, we'll use simple heuristics, not an LLM. This keeps the selection reproducible and avoids introducing synthetic judgments too early.

In [16]:
# Identify cleaned passages that are suitable candidates
# for instruction-response generation.

instruction_candidates = clean_df.copy()

# Basic suitability signals
instruction_candidates["has_explanatory_language"] = (
    instruction_candidates["content_clean"]
    .str.contains(
        r"\b(is|are|refers to|defined|causes|results in|leads to|"
        r"associated with|characterized by|regulates|inhibits|"
        r"stimulates|reabsorbs|excretes|increases|decreases)\b",
        case=False,
        regex=True,
        na=False
    )
)

instruction_candidates["has_nephro_term"] = (
    instruction_candidates["content_clean"]
    .str.contains(
        r"\b(kidney|renal|nephron|nephritic|nephrotic|"
        r"glomerul|dialysis|glomerular|tubular|"
        r"ureter|urine|creatinine|GFR|"
        r"aldosterone|renin|electrolyte|acid-base)\b",
        case=False,
        regex=True,
        na=False
    )
)

# Keep passages that contain enough text and at least
# one explanatory or nephrology-specific signal.
instruction_candidates = instruction_candidates[
    (instruction_candidates["word_count"] >= 20) &
    (
        instruction_candidates["has_explanatory_language"] |
        instruction_candidates["has_nephro_term"]
    )
].copy()

print("Cleaned passages:", len(clean_df))
print("Instruction-generation candidates:", len(instruction_candidates))
print(
    "Candidate retention:",
    f"{len(instruction_candidates) / len(clean_df) * 100:.1f}%"
)

print("\nCandidates by textbook:")
print(
    instruction_candidates["title"]
    .value_counts()
    .sort_index()
)

# Remove helper columns before continuing
instruction_candidates.drop(
    columns=[
        "has_explanatory_language",
        "has_nephro_term"
    ],
    inplace=True
)

Cleaned passages: 3113
Instruction-generation candidates: 3024
Candidate retention: 97.1%

Candidates by textbook:
title
Anatomy_Gray              41
InternalMed_Harrison    1981
Pathology_Robbins        246
Pathoma_Husain            58
Pharmacology_Katzung     427
Physiology_Levy          271
Name: count, dtype: int64

/tmp/ipykernel_58/2330636703.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(
/tmp/ipykernel_58/2330636703.py:21: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(


3,024 of 3,113 passages (97.1%) pass the basic suitability heuristic. That tells us the heuristic is intentionally permissive—which is good here. We don't want to discard potentially useful medical content before we have actually transformed it.

**Define the Instruction-Response Format**

The selected theory passages now need to be transformed into supervised fine-tuning examples.

Rather than generating arbitrary questions, we will use a small set of controlled educational instruction types.

### Instruction types

Depending on the information available in a passage, an example may ask the model to:

- **Explain a concept** — explain a nephrology concept or mechanism.
- **Describe a process** — describe how a renal physiological or pathological process works.
- **Explain a clinical concept** — explain a disease, syndrome, finding, or complication.
- **Explain a relationship** — explain how two nephrology concepts are related.
- **Compare concepts** — compare two concepts when the source passage explicitly supports the comparison.

Not every passage needs to support every instruction type.

### Example

For a passage describing glomerular filtration:

```text
Instruction:
Explain the role of the glomerulus in renal filtration.

Response:
The glomerulus is a specialized network of capillaries that filters
plasma to form the initial tubular fluid...

**Create a Pilot Instruction-Response Dataset**

In [17]:
# Create a small pilot dataset from the selected nephrology passages.
# The pilot will be inspected before generating the full training set.

pilot_size = min(50, len(instruction_candidates))

pilot_df = instruction_candidates.sample(
    n=pilot_size,
    random_state=42
).copy()

# Define the instruction-response dataset schema.
# The response will be generated in the next step.
pilot_df["instruction"] = ""
pilot_df["response"] = ""

# Keep source information for traceability.
pilot_training_df = pilot_df[
    [
        "id",
        "title",
        "content_clean",
        "instruction",
        "response"
    ]
].copy()

print("Pilot passages:", len(pilot_training_df))

print("\nDataset columns:")
print(pilot_training_df.columns.tolist())

print("\nSample source passages:")
for _, row in pilot_training_df.head(5).iterrows():
    print("\n" + "=" * 80)
    print(f"Source: {row['title']}")
    print(f"ID: {row['id']}")
    print(f"Text: {row['content_clean']}")

Pilot passages: 50

Dataset columns:
['id', 'title', 'content_clean', 'instruction', 'response']

Sample source passages:

================================================================================
Source: Physiology_Levy
ID: Physiology_Levy_4128
Text: Actions of Cortisol on the Kidney Cortisol inhibits the secretion and action of antidiuretic hormone (ADH), and thus it is an ADH antagonist. In the absence of cortisol, the action of ADH is potentiated, which makes it difficult to increase free water clearance in response to a water load and increases the likelihood of water intoxication. Although cortisol binds to the mineralocorticoid receptor with high affinity, this action is normally blocked by inactivation of cortisol to cortisone by the enzyme 11βHSD2. However, the mineralocorticoid activity (i.e., renal Na+ and H2O retention, K+ and H+ excretion) of cortisol depends on the relative amount of cortisol (or synthetic glucocorticoids) and the activity of 11β-HSD2. Certain agents (e.g., compounds in black licorice) inhibit 11βHSD2 and thereby increase the mineralocorticoid activity of cortisol. Cortisol increases the glomerular filtration rate by both increasing cardiac output and acting directly on the kidney.

================================================================================
Source: InternalMed_Harrison
ID: InternalMed_Harrison_3651
Text: The diagnosis in this case is classic hypokalemic dRTA from Sjögren’s syndrome. This patient presented with a non-AG metabolic acidosis. The urine AG was positive, indicating an abnormally low excretion of ammonium in the face of systemic acidosis. The urine pH was inappropriately alkaline, yet there was no evidence of hypercalciuria, nephrocalcinosis, or bone disease. The patient was subsequently shown to exhibit hyperglobulinemia. These findings, taken together, indicate that the cause of this patient’s hypokalemia and non-AG metabolic acidosis was a renal tubular abnormality. The hypokalemia and abnormally low excretion of ammonium, as estimated by the urine AG, in the absence of glycosuria, phosphaturia, or aminoaciduria (Fanconi’s syndrome), defines the entity of classic distal renal tubular acidosis (dRTA), also known as type 1 RTA. Because of the hyperglobulinemia, additional serology was obtained, providing evidence for the diagnosis of primary Sjögren’s syndrome. Furthermore,

================================================================================
Source: InternalMed_Harrison
ID: InternalMed_Harrison_26834
Text: Disorders of the Thyroid Gland 2300 low, normal, or high in these patients. In the early stage of HIV infection, T3 and T4 levels rise, even if there is weight loss. T3 levels fall with progression to AIDS, but TSH usually remains normal. Renal disease is often accompanied by low T3 concentrations, but with normal rather than increased rT3 levels, due to an unknown factor that increases uptake of rT3 into the liver. The diagnosis of SES is challenging. Historic information may be limited, and patients often have multiple metabolic derangements. Useful features to consider include previous history of thyroid disease and thyroid function tests, evaluation of the severity and time course of the patient’s acute illness, documentation of medications that may affect thyroid function or thyroid hormone levels, and measurements of rT3 together with unbound thyroid hormones and TSH. The diagnosis of SES is frequently presumptive, given the clinical context and pattern of laboratory values;

================================================================================
Source: InternalMed_Harrison
ID: InternalMed_Harrison_25457
Text: lenses; corneal transplantation Glandular manifestations Extraglandular manifestations Parotid gland enlargement Dry mouth Dry eyes Arthritis Cold protection: gloves Raynaud’s phenomenon Bicarbonate replacement Renal tubular acidosis CHOP + anti-CD20 Vasculitis Standard treatment Lymphoma Hydroxychloroquine (200–400 mg/d) or Methotrexate (0.2–0.3 mg/kg body weight weekly) plus Prednisolone (<10 mg daily orally)

================================================================================
Source: InternalMed_Harrison
ID: InternalMed_Harrison_21563
Text: BUN and creatinine are functional biomarkers of glomerular filtration rather than tissue injury biomarkers and, therefore, may be suboptimal for the diagnosis of actual parenchymal kidney damage. BUN and creatinine are also relatively slow to rise after kidney injury. Several novel kidney injury biomarkers have been investigated and show promise for earlier and accurate diagnosis of AKI. Kidney injury molecule-1 (KIM-1) is a type 1 transmembrane protein that is abundantly expressed in proximal tubular cells injured by ischemia or nephrotoxins such as cisplatin. KIM-1 is not expressed in appreciable quantities in the absence of tubular injury or in extrarenal tissues. KIM-1’s functional role may be to confer phagocytic properties to tubular cells, enabling them to clear debris from the tubular lumen after kidney injury. KIM-1 can be detected shortly after ischemic or nephrotoxic injury in the urine and, therefore, may be an easily tested biomarker in the clinical setting. Neutrophil

The pilot reveals exactly why we did this check. The passages are not all equally suitable for SFT generation.

For example:

The cortisol/kidney passage is coherent and can support several educational questions.
The dRTA passage is also rich enough for an educational example.
The BUN/creatinine passage is strong.
But the thyroid passage contains an incidental renal reference.
The Sjögren's passage is essentially a table/summary fragment, not a good standalone teaching passage.

So before generating synthetic instructions, **we should add one more quality-control layer.**

In [19]:
# Identify passages that are likely to be structurally noisy,
# such as table fragments, figure labels, or broken text.

quality_df = instruction_candidates.copy()

text = quality_df["content_clean"]

# Signals of potentially noisy textbook extraction
quality_df["has_table_signal"] = text.str.contains(
    r"\b(Table|TABLE|Fig\.|Figure|FIGURE)\b",
    regex=True,
    na=False
)

quality_df["has_fragment_signal"] = (
    text.str.match(r"^[a-z]", na=False) |
    text.str.contains(r"\.{2,}|:{2,}", regex=True, na=False)
)

quality_df["has_many_short_tokens"] = (
    text.str.split().apply(
        lambda words: (
            len(words) > 0 and
            sum(len(w) <= 2 for w in words) / len(words) > 0.25
        )
    )
)

# Count passages with each signal
print("Instruction candidates:", len(quality_df))

print("\nPotential table/figure passages:")
print(quality_df["has_table_signal"].sum())

print("\nPotential fragmented passages:")
print(quality_df["has_fragment_signal"].sum())

print("\nPassages with many very short tokens:")
print(quality_df["has_many_short_tokens"].sum())

# Show examples flagged by the structural checks
flagged_df = quality_df[
    quality_df["has_table_signal"] |
    quality_df["has_fragment_signal"] |
    quality_df["has_many_short_tokens"]
].copy()

print("\nTotal flagged for review:", len(flagged_df))

for _, row in flagged_df.head(15).iterrows():
    print("\n" + "=" * 100)
    print(f"SOURCE: {row['title']}")
    print(f"ID: {row['id']}")
    print(f"TEXT:\n{row['content_clean']}")

Instruction candidates: 3024

Potential table/figure passages:
304

Potential fragmented passages:
592

Passages with many very short tokens:
168

Total flagged for review: 996

====================================================================================================
SOURCE: Anatomy_Gray
ID: Anatomy_Gray_777
TEXT:
Anterior to the abdominal aorta, as it descends, are the pancreas and splenic vein, the left renal vein, and the inferior part of the duodenum. Several left lumbar veins cross it posteriorly as they pass to the inferior vena cava. On its right side are the cisterna chyli, thoracic duct, azygos vein, right crus of the diaphragm, and the inferior vena cava. On its left side is the left crus of the diaphragm. Branches of the abdominal aorta (Table 4.3) can be classified as: visceral branches supplying organs, posterior branches supplying the diaphragm or body wall, or terminal branches. The visceral branches are either unpaired or paired vessels. The three unpaired visceral branches that arise from the anterior surface of the abdominal aorta (Fig. 4.164) are: the celiac trunk, which supplies the abdominal foregut, the superior mesenteric artery, which supplies the abdominal midgut, and the inferior mesenteric artery, which supplies the abdominal hindgut.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_355
TEXT:
In a typical 70-kg human, plasma volume is ∼3 L, blood volume is ∼5.5 L, and extracellular water outside the vasculature is ∼20 L. The volume of distribution of drugs extensively bound to plasma proteins but not to tissue components approaches plasma volume; warfarin is one such example. By contrast, for drugs highly bound to tissues, the volume of distribution can be far greater than any physiologic space. For example, the volume of distribution of digoxin and tricyclic antidepressants is hundreds of liters, obviously exceeding total-body volume. Such drugs are not readily removed by dialysis, an important consideration in overdose. Initiation of therapy Change of chronic therapy ChangedosingDose = D * 10th dose Dose = 2•D Dose = 2•D Dose = 0.5•D Discontinue drug Loading dose + dose = D Concentration

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_418
TEXT:
Amiodarone Inhibitor of many CYPs and of P-glycoprotein Gemfibrozil (and other fibrates) CYP3A inhibition Quinidine P-glycoprotein inhibition Amiodarone Verapamil Cyclosporine Itraconazole Erythromycin Phenylbutazone Inhibition of renal tubular transport Probenecid Salicylates erythromycin and some other macrolide antibiotics (clarithromycin but not azithromycin), ketoconazole and other azole antifungals, the antiretroviral agent ritonavir, and high concentrations of grapefruit juice (Table 5-3). The consequences of such interactions will depend on the drug whose elimination is being inhibited (see “The Concept of High-Risk Pharmacokinetics,” above). Examples include CYP3A inhibitors increasing the risk of cyclosporine toxicity or of rhabdomyolysis with some HMG-CoA reductase inhibitors (lovastatin, simvastatin, atorvastatin, but not pravastatin), and P-glycoprotein inhibitors increasing the risk of toxicity with digoxin therapy or of bleeding with the thrombin inhibitor dabigatran.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_551
TEXT:
abnormalities of cerebral circulatory autoregulation, which increase the risk of stroke at mildly and moderately elevated blood pressures. Risk factors for the development of preeclampsia include nulliparity, diabetes mellitus, a history of renal disease or chronic hypertension, a prior history of preeclampsia, extremes of maternal age (>35 years or <15 years), obesity, antiphospholipid antibody syndrome, and multiple gestation. Low-dose aspirin (81 mg daily, initiated at the end of the first trimester) may reduce the risk of preeclampsia in pregnant women at high risk of developing the disease.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_560
TEXT:
a prepregnancy serum creatinine level <133 μmol/L (<1.5 mg/dL) is associated with a favorable prognosis. When renal disease worsens during pregnancy, close collaboration between the internist and the maternal-fetal medicine specialist is essential so that decisions regarding delivery can be weighed to balance the sequelae of prematurity for the neonate versus long-term sequelae for the mother with respect to future renal function.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_598
TEXT:
esterase strips is indicated for high-risk women, such as those with sickle cell trait or a history of urinary tract infections. All women with positive screens should be treated. Pregnant women who develop pyelonephritis need careful monitoring, including inpatient IV antibiotic administration due to the elevated risk of urosepsis and acute respiratory distress syndrome in pregnancy.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_726
TEXT:
of terminally ill patients have major depression. Depression is not limited to cancer patients but found in patients with end-stage renal disease, Parkinson’s disease, multiple sclerosis, and other terminal conditions.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_853
TEXT:
not be detectable with the usual clinical tests. Formulas for estimating glomerular filtration rate in older patients are available, whereas the estimation of changes in hepatic excretion remains a challenge.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_899
TEXT:
follow-up by the health care provider, possibly in the presence of a caregiver. Chlorpropamide has a prolonged half-life, particularly in older adults, and should be avoided because it is associated with a high risk of hypoglycemia. Metformin should be used with caution and only in patients free of severe renal insufficiency. Renal insufficiency should be assessed by a calculated glomerular filtration rate or, in very old patients who have reduced muscle mass, by a direct measure of creatinine clearance from a 24-h urine collection. Lifestyle changes in diet and exercise and a little weight loss can prevent or delay diabetes in high-risk individuals and are substantially more effective than metformin treatment. The risk of type 2 diabetes decreased by 58% in a study of diet and exercise, and this effect was similar at all ages and in all ethnic groups. The risk reduction with standard care plus metformin was 31%.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_944
TEXT:
support, whereas that fraction increased to approximately two-thirds with decision support; moreover, with such support, patients with renal insufficiency were discharged from the hospital half a day earlier. As of 2009, only ~15% of U.S. hospitals had implemented CPOE, but many plan to do so and will receive major financial incentives for achieving this goal.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_1266
TEXT:
the risks of aspirin and NSAIDs. In addition to the well-known gastrointestinal toxicity of NSAIDs, nephrotoxicity is a significant problem for patients using these drugs on a chronic basis. Patients at risk for renal insufficiency, particularly those with significant contraction of their intravascular volume as occurs with chronic diuretic use or

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_1370
TEXT:
of patients who have non-ACS cardiopulmonary conditions than with previous, less sensitive assays. This evolution in testing for myocardial necrosis has rendered other aspects of the clinical evaluation critical to the practitioner’s determination of the probability that the symptoms represent ACS. In addition, observation of a change in cardiac troponin concentration between serial samples is useful in discriminating acute causes of myocardial injury from chronic elevation due to underlying structural heart disease, end-stage renal disease, or interfering antibodies. The diagnosis of MI is reserved for acute myocardial injury that is marked by a rising and/or falling pattern—with at least one value exceeding the 99th percentile reference limit—and that is caused by ischemia. Other non-ischemic insults, such as myocarditis, may result in myocardial injury but should not be labeled MI.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_2309
TEXT:
rarely. It is important to biopsy an arterial segment of at least 3 cm and to examine a sufficient number of tissue sections prepared from the specimen. Posterior Ischemic Optic Neuropathy This is an uncommon cause of acute visual loss, induced by the combination of severe anemia and hypotension. Cases have been reported after major blood loss during surgery (especially in patients undergoing cardiac or lumbar spine operations), exsanguinating trauma, gastrointestinal bleeding, and renal dialysis. The fundus usually appears normal, although optic disc swelling develops if the process extends anteriorly far enough to reach the globe. Vision can be salvaged in some patients by prompt blood transfusion and reversal of hypotension.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_2437
TEXT:
activity of the mitral/tufted cells is modulated by the periglomerular cells, secondary dendrites from other mitral/tufted cells, and granule cells, the most numerous cells of the bulb. The latter cells, which are largely GABAergic, receive inputs from central brain structures and modulate the output of the mitral/tufted cells. Interestingly, like the olfactory receptor cells, some cells within the bulb undergo replacement. Thus, neuroblasts formed within the anterior subventricular zone of the brain migrate along the rostral migratory stream, ultimately becoming granule and periglomerular cells.

====================================================================================================
SOURCE: InternalMed_Harrison
ID: InternalMed_Harrison_2469
TEXT:
and other toxic agents, and medical interventions is also informative. A determination of all the medications that the patient was taking before and at the time of symptom onset is important, because many can cause chemosensory disturbances. Comorbid medical conditions associated with smell impairment, such as renal failure, liver disease, hypothyroidism, diabetes, or dementia, should be assessed. Delayed puberty in association with anosmia (with or without midline craniofacial abnormalities, deafness, and renal anomalies) suggests the possibility of Kallmann’s syndrome. Recollection of epistaxis, discharge (clear, purulent, or bloody), nasal obstruction, allergies, and somatic symptoms, including headache or irritation, may have localizing value. Questions related to memory, parkinsonian signs, and seizure activity (e.g., automatisms, blackouts,

/tmp/ipykernel_58/1116769080.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  quality_df["has_table_signal"] = text.str.contains(

This confirms the structural filter is too broad to use as an automatic exclusion rule.

We have 996 flagged passages, but several are actually useful. For example, a passage can contain a legitimate renal concept while also mentioning a figure/table. Conversely, some flagged passages are clearly incidental—for example, renal disease appearing only as one risk factor or comorbidity.

The purpose of the generation prompt should therefore be simply:

**Take an already-selected nephrology passage and create one instruction-response example grounded in that passage.**

In [41]:
def create_teacher_training_example_prompt(passage):
    return f"""Create ONE high-quality educational Q&A from this
nephrology-focused textbook passage.

SOURCE PASSAGE:
{passage}

IMPORTANT SELECTION RULE:

The Q&A must teach the CENTRAL renal/nephrology concept of the
passage.

Do NOT create a Q&A merely because the passage mentions:
- renal impairment,
- kidney function,
- renal drug clearance,
- dose adjustment in renal disease,
- a kidney-related complication of another disease, or
- an electrolyte abnormality in a primarily non-renal context.

Prefer passages whose central teaching point concerns:
- renal physiology,
- glomerular or tubular function,
- kidney disease,
- renal pathology,
- electrolyte or acid-base physiology when the renal mechanism
  is central,
- acute or chronic kidney disease,
- dialysis,
- transplantation,
- renal diagnostic findings, or
- renal treatment principles.

If the central teaching point is primarily another medical specialty,
output exactly:

SKIP

If the passage supports a strong nephrology teaching example:

1. Write ONE clear educational question.
2. Answer it using ONLY information explicitly stated in the passage.
3. Do not add outside medical knowledge.
4. Do not infer facts that are not stated.
5. Keep the answer concise.
6. Do not provide patient-specific medical advice.

Output ONLY:

INSTRUCTION: <actual educational question>
RESPONSE: <actual answer>

OR:

SKIP
"""

**Generate 10 Pilot Instruction-Response Examples**

In [44]:
# Generate a small pilot of instruction-response examples

import torch
import pandas as pd

pilot_results = []

# Use 10 passages from our existing 50-passage pilot
generation_pilot = pilot_training_df.head(10)

model.eval()

for _, row in generation_pilot.iterrows():

    prompt = create_training_example_prompt(
        row["content_clean"]
    )

    messages = [
        {
            "role": "user",
            "content": prompt
        }
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt"
    ).to(model.device)

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_tokens = outputs[0][
        inputs["input_ids"].shape[1]:
    ]

    generated_text = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

    pilot_results.append({
        "source_id": row["id"],
        "source_title": row["title"],
        "source_text": row["content_clean"],
        "generated_example": generated_text
    })

# Store the results without modifying the original dataset
generated_pilot_df = pd.DataFrame(pilot_results)

print("Generated examples:", len(generated_pilot_df))

for _, row in generated_pilot_df.iterrows():
    print("\n" + "=" * 90)
    print("SOURCE ID:", row["source_id"])
    print("SOURCE:", row["source_title"])
    print("\nGENERATED EXAMPLE:")
    print(row["generated_example"])

Generated examples: 10

==========================================================================================
SOURCE ID: Physiology_Levy_4128
SOURCE: Physiology_Levy

GENERATED EXAMPLE:
INSTRUCTION: What is the effect of cortisol on the action of antidiuretic hormone (ADH) in the kidney?
RESPONSE: Cortisol inhibits the secretion and action of ADH, making it an ADH antagonist.

==========================================================================================
SOURCE ID: InternalMed_Harrison_3651
SOURCE: InternalMed_Harrison

GENERATED EXAMPLE:
INSTRUCTION: What is the primary renal tubular abnormality in a patient with classic distal renal tubular acidosis (dRTA)?

RESPONSE: A renal tubular abnormality that causes abnormally low excretion of ammonium in the face of systemic acidosis.

==========================================================================================
SOURCE ID: InternalMed_Harrison_26834
SOURCE: InternalMed_Harrison

GENERATED EXAMPLE:
INSTRUCTION: What is the effect of renal disease on T3 levels in patients with HIV infection?
RESPONSE: T3 levels fall with progression to AIDS.

==========================================================================================
SOURCE ID: InternalMed_Harrison_25457
SOURCE: InternalMed_Harrison

GENERATED EXAMPLE:
INSTRUCTION: What is the standard treatment for lymphoma in the context of renal tubular acidosis?
RESPONSE: Hydroxychloroquine (200–400 mg/d) or Methotrexate (0.2–0.3 mg/kg body weight weekly) plus Prednisolone (<10 mg daily orally).

==========================================================================================
SOURCE ID: InternalMed_Harrison_21563
SOURCE: InternalMed_Harrison

GENERATED EXAMPLE:
INSTRUCTION: What is the primary function of BUN and creatinine in relation to kidney injury?
RESPONSE: BUN and creatinine are functional biomarkers of glomerular filtration rather than tissue injury biomarkers.

==========================================================================================
SOURCE ID: InternalMed_Harrison_21846
SOURCE: InternalMed_Harrison

GENERATED EXAMPLE:
INSTRUCTION: What type of information can a renal biopsy provide about the type of glomerular injury?
RESPONSE: A renal biopsy can identify the type of glomerular injury.

==========================================================================================
SOURCE ID: InternalMed_Harrison_477
SOURCE: InternalMed_Harrison

GENERATED EXAMPLE:
INSTRUCTION: What is the primary cause of hypertension in women over 60 years old?
RESPONSE: Isolated systolic hypertension.

==========================================================================================
SOURCE ID: Pathology_Robbins_3423
SOURCE: Pathology_Robbins

GENERATED EXAMPLE:
INSTRUCTION: What is the primary cause of papillary necrosis in the kidney?

RESPONSE: Diabetes, urinary tract obstruction, and sickle cell anemia.

==========================================================================================
SOURCE ID: InternalMed_Harrison_22035
SOURCE: InternalMed_Harrison

GENERATED EXAMPLE:
INSTRUCTION: What is the primary cause of karyomegalic tubulointerstitial nephritis?
RESPONSE: The inheritance of two mutant copies of the FAN1 gene.

==========================================================================================
SOURCE ID: InternalMed_Harrison_8948
SOURCE: InternalMed_Harrison

GENERATED EXAMPLE:
INSTRUCTION: What is the typical laboratory finding in patients with amyloidosis who have glomerular kidney involvement?

RESPONSE: The erythrocyte sedimentation rate is frequently elevated.

The problem we're seeing isn't that the passages are bad. It's that Llama 3.2 3B is being asked to perform a fairly demanding data-curation task: understand the passage, determine the central concept, decide whether it is nephrology-specific, and then generate a grounded Q&A. The pilot shows it sometimes fails at that.

Better architecture

Instead of:

Textbook passage
      ↓
Llama 3.2 3B
      ↓
Q&A


use:

Textbook passage
      ↓
Stronger instruction model Qwen2.5 7B Instruct
      ↓
High-quality Q&A dataset
      ↓
Llama 3.2 3B + QLoRA
      ↓
NephroLLM

**7.6 Load the Teacher Model for Synthetic Dataset Construction**

The initial pilot showed that Llama 3.2 3B can generate correctly formatted Q&A examples, but it sometimes focuses on a secondary or incidental medical concept rather than the main nephrology concept in the source passage.

To improve the quality of the supervised fine-tuning dataset, we introduce a separate **teacher model** for synthetic instruction-response generation.

We will use **Qwen2.5-7B-Instruct** as the teacher model and retain **Llama 3.2 3B-Instruct** as the target model that will ultimately be fine-tuned.

The roles are therefore separated:

```text
Independent medical textbook corpus
            ↓
Qwen2.5-7B-Instruct
     Teacher / data generator
            ↓
High-quality nephrology Q&A
            ↓
Llama 3.2 3B-Instruct
     Target model + QLoRA

In [20]:

# Load Qwen2.5-7B-Instruct as the teacher model
# for synthetic nephrology training-data generation.

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

teacher_model_name = "Qwen/Qwen2.5-7B-Instruct"

# 4-bit quantization for the Kaggle T4 GPU
teacher_bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

# Load tokenizer
teacher_tokenizer = AutoTokenizer.from_pretrained(
    teacher_model_name,
    token=hf_token,
)

# Load quantized teacher model
teacher_model = AutoModelForCausalLM.from_pretrained(
    teacher_model_name,
    quantization_config=teacher_bnb_config,
    device_map="auto",
    token=hf_token,
)

teacher_model.eval()

print("Teacher model loaded successfully.")
print("Model:", teacher_model_name)
print("Device:", teacher_model.device)
print("Dtype:", teacher_model.dtype)
print("4-bit quantization: enabled")

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Teacher model loaded successfully.
Model: Qwen/Qwen2.5-7B-Instruct
Device: cuda:0
Dtype: torch.bfloat16
4-bit quantization: enabled

**7.6.1 Verify Teacher-Model Inference**

Before using the teacher model to construct the synthetic training dataset, we verify that Qwen2.5-7B-Instruct can generate responses correctly using its native chat template.

This is a technical sanity check only. The teacher model is not yet being used to generate the training corpus.

We use a simple nephrology question to confirm:

- the tokenizer and chat template work correctly;
- the quantized model can generate on the available GPU;
- the output is coherent; and
- the teacher model is ready for the dataset-generation pilot.

**Expected outcome:** a coherent educational nephrology response from Qwen2.5-7B-Instruct.

In [21]:
# Verify Qwen teacher-model inference

def ask_teacher(question, max_new_tokens=128):
    messages = [
        {
            "role": "system",
            "content": (
                "You are an educational assistant specializing in nephrology. "
                "Provide clear, factual, educational explanations. "
                "Do not provide diagnosis or personalized medical advice."
            ),
        },
        {
            "role": "user",
            "content": question,
        },
    ]

    prompt = teacher_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = teacher_tokenizer(
        prompt,
        return_tensors="pt",
    ).to(teacher_model.device)

    with torch.no_grad():
        outputs = teacher_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=teacher_tokenizer.eos_token_id,
        )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    answer = teacher_tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True,
    )

    return answer.strip()


teacher_test_question = (
    "What is the primary function of the glomerulus in the kidney?"
)

teacher_test_answer = ask_teacher(
    teacher_test_question,
    max_new_tokens=128,
)

print("Question:")
print(teacher_test_question)

print("\nTeacher response:")
print(teacher_test_answer)

Question:
What is the primary function of the glomerulus in the kidney?

Teacher response:
The primary function of the glomerulus in the kidney is to filter blood and remove waste products and excess substances from the bloodstream. This process is a crucial part of the renal filtration system, which helps maintain the body's fluid balance and regulate blood pressure.

Here’s a more detailed explanation:

1. **Filtration**: The glomerulus is a network of tiny blood vessels (capillaries) within the kidney. Blood enters the glomerulus through the afferent arteriole and leaves through the efferent arteriole. As blood passes through the glomerulus, water and small molecules such as ions, glucose

**7.6.2 Pilot Synthetic Q&A Generation with the Teacher Model**

The teacher model has passed the inference sanity check. We now test its ability to construct supervised training examples from the same 10 passages previously evaluated with Llama 3.2 3B.

Using the same source passages allows us to compare the two generation approaches without changing the underlying data.

At this stage, the teacher model is instructed to:

- create exactly one educational question per usable passage;
- focus on the main nephrology concept present in the passage;
- ground the answer strictly in the supplied passage;
- avoid introducing outside medical information; and
- return `SKIP` only when the selected passage cannot support a coherent nephrology teaching example.

The raw teacher outputs will be retained for inspection before we scale generation to the full candidate corpus.

**Expected outcome:** the teacher model should produce more consistently focused nephrology questions and answers than the initial 3B-model pilot.

**7.6.3 Parse and Validate Teacher-Generated Examples**

The teacher model has generated a 50-example pilot dataset.

We now convert the raw teacher outputs into structured instruction-response records.

This step performs **structural validation only**. It does not attempt to determine medical correctness automatically.

A record is considered structurally valid when it contains:

- an `INSTRUCTION:` field;
- a `RESPONSE:` field;
- non-empty instruction and response text;
- no explicit `SKIP`; and
- no obvious meta-instruction in place of the actual question.

The original teacher output is retained for auditability.

**Expected outcome:** quantify how many pilot examples are structurally usable before scaling the generation process.

In [25]:
# Parse and structurally validate the completed Qwen pilot.

import re
import pandas as pd


def parse_teacher_output(text):
    text = str(text).strip()

    # Explicitly skipped by the teacher
    if text.upper() == "SKIP":
        return {
            "status": "SKIP",
            "instruction_parsed": "",
            "response_parsed": "",
        }

    # Extract the instruction and response fields
    match = re.search(
        r"INSTRUCTION:\s*(.*?)\s*RESPONSE:\s*(.*)",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    if not match:
        return {
            "status": "INVALID",
            "instruction_parsed": "",
            "response_parsed": "",
        }

    instruction = match.group(1).strip()
    response = match.group(2).strip()

    # Reject empty fields
    if not instruction or not response:
        return {
            "status": "INVALID",
            "instruction_parsed": instruction,
            "response_parsed": response,
        }

    # Reject obvious meta-instructions
    meta_patterns = [
        r"^create (one|a|an) ",
        r"^write (one|a|an) ",
        r"^generate ",
        r"^answer the question",
        r"^provide ",
    ]

    is_meta_instruction = any(
        re.search(pattern, instruction, flags=re.IGNORECASE)
        for pattern in meta_patterns
    )

    if is_meta_instruction:
        return {
            "status": "INVALID",
            "instruction_parsed": instruction,
            "response_parsed": response,
        }

    return {
        "status": "VALID",
        "instruction_parsed": instruction,
        "response_parsed": response,
    }


parsed_records = []

for _, row in teacher_pilot_df.iterrows():

    parsed = parse_teacher_output(
        row["teacher_output"]
    )

    parsed_records.append({
        "id": row["id"],
        "title": row["title"],
        "teacher_output": row["teacher_output"],
        **parsed,
    })


teacher_pilot_parsed_df = pd.DataFrame(parsed_records)


print("Pilot examples:", len(teacher_pilot_parsed_df))

print("\nStatus distribution:")
print(
    teacher_pilot_parsed_df["status"]
    .value_counts()
)

print("\nStructurally valid examples:")
print(
    teacher_pilot_parsed_df[
        teacher_pilot_parsed_df["status"] == "VALID"
    ][
        ["id", "title", "instruction_parsed", "response_parsed"]
    ].to_string(index=False)
)

Pilot examples: 50

Status distribution:
status
INVALID    36
VALID      12
SKIP        2
Name: count, dtype: int64

Structurally valid examples:
                        id                title                                                                                                       instruction_parsed                                                                                                                                                                                                               response_parsed
      Physiology_Levy_4128      Physiology_Levy                                              What effect does cortisol have on the action of antidiuretic hormone (ADH)?                                                                                                                        Cortisol inhibits the secretion and action of antidiuretic hormone (ADH), making it an ADH antagonist.
 InternalMed_Harrison_3651 InternalMed_Harrison                                               What does a positive urine anion gap (AG) indicate in this patient's case?                                                                                                           A positive urine anion gap (AG) indicates an abnormally low excretion of ammonium in the face of systemic acidosis.
InternalMed_Harrison_26834 InternalMed_Harrison      What is the typical change in T3 levels in patients with renal disease compared to those without renal involvement?                                                                                                                                                                  Renal disease is often accompanied by low T3 concentrations.
InternalMed_Harrison_21846 InternalMed_Harrison                                What stains are used in light microscopy to process a renal biopsy in glomerulonephritis?                                                                                                         Hematoxylin and eosin (H&E), periodic acid–Schiff (PAS), Jones-methenamine silver, Congo red, and Masson’s trichrome.
  InternalMed_Harrison_477 InternalMed_Harrison                                 What is the female preponderance associated with among secondary causes of hypertension?                                                                                                                                                                                         Renal artery fibromuscular dysplasia.
    Pathology_Robbins_3423    Pathology_Robbins                                                       What are the three predisposing conditions for papillary necrosis?                                                                                                                                                                  Diabetes, urinary tract obstruction, and sickle cell anemia.
InternalMed_Harrison_22035 InternalMed_Harrison What genetic condition is associated with karyomegalic tubulointerstitial nephritis, and how does it affect individuals? Karyomegalic tubulointerstitial nephritis is a recessive disorder caused by inheritance of two mutant copies of the FAN1 gene. Individuals with two mutant FAN1 genes are genetically sensitized to the effect of DNA damage.
 InternalMed_Harrison_8948 InternalMed_Harrison                              What is a common finding in patients with glomerular kidney involvement due to amyloidosis?                                                                                                                         Patients with glomerular kidney involvement generally have proteinuria, often in the nephrotic range.
      Physiology_Levy_3281      Physiology_Levy                                                     How much sodium and water are reabsorbed daily by the renal tubules?                                                                                                                               Approximately 25,000 mEq/day of Na+ and 179 L/day of water are reabsorbed by the renal tubules.
InternalMed_Harrison_21725 InternalMed_Harrison                                                             What is the "fistula first" initiative and what is its goal?                                                                                                            The "fistula first" initiative encourages the creation of arteriovenous fistulas in a larger fraction of patients.
InternalMed_Harrison_21590 InternalMed_Harrison                                What is a potential risk of delaying dialysis in patients with acute kidney injury (AKI)?                                                                                                            Late initiation of dialysis carries the risk of avoidable volume, electrolyte, and metabolic complications of AKI.
 InternalMed_Harrison_3459 InternalMed_Harrison                   What type of hyponatremia is associated with secondary adrenal insufficiency due to pituitary disease?                                                                                                                                                                                                       Euvolemic hyponatremia.

In [28]:
# Reset the teacher pilot cleanly without running model inference.

teacher_pilot_df = pilot_df.sample(
    n=min(10, len(pilot_df)),
    random_state=42
).copy()

teacher_pilot_df["teacher_output"] = ""

print("Fresh pilot passages:", len(teacher_pilot_df))
print("Teacher outputs initialized:", teacher_pilot_df["teacher_output"].eq("").sum())

Fresh pilot passages: 10
Teacher outputs initialized: 10

**7.6.4 Generate the Optimized Teacher Pilot**

We now run a small optimized pilot using Qwen2.5-7B-Instruct.

The pilot uses only 10 passages so that the generation quality can be evaluated before scaling to the full training corpus.

Compared with the earlier pilot, the generation budget is reduced because the desired output is intentionally concise:

```text
INSTRUCTION: <one educational question>
RESPONSE: <one grounded answer>

**7.6.5 Batch Teacher-Model Generation**

Sequential generation is relatively slow because each passage requires a separate model-generation call.

We now test batched generation, where multiple source passages are tokenized and processed together in a single model call.

Batching should improve GPU utilization and reduce the overhead of repeatedly invoking the teacher model.

The pilot remains intentionally small so that we can verify:

- batched tokenization works correctly;
- Qwen handles multiple prompts in one generation call;
- each generated response remains associated with the correct source passage; and
- the improved nephrology-focused prompt produces usable examples.

We continue to use deterministic generation and a maximum output length of 96 tokens.

**Expected outcome:** generate the 10 pilot examples more efficiently while preserving one output per source passage.

In [38]:
# Configure left-padding for batched generation with Qwen.

teacher_tokenizer.padding_side = "left"

# Qwen may not have a dedicated padding token.
# Use EOS as the padding token for generation.
if teacher_tokenizer.pad_token is None:
    teacher_tokenizer.pad_token = teacher_tokenizer.eos_token

print("Padding side:", teacher_tokenizer.padding_side)
print("Pad token:", teacher_tokenizer.pad_token)
print("Pad token ID:", teacher_tokenizer.pad_token_id)

Padding side: left
Pad token: <|endoftext|>
Pad token ID: 151643

In [39]:
# Corrected batched Qwen teacher generation.

import torch


# Build prompts
pilot_prompts = [
    create_teacher_training_example_prompt(passage)
    for passage in teacher_pilot_df["content_clean"]
]


# Apply Qwen's native chat template
formatted_prompts = []

for prompt in pilot_prompts:
    messages = [
        {
            "role": "system",
            "content": (
                "You generate high-quality, concise, grounded "
                "nephrology educational training examples."
            ),
        },
        {
            "role": "user",
            "content": prompt,
        },
    ]

    formatted_prompts.append(
        teacher_tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
    )


# Tokenize as a left-padded batch
inputs = teacher_tokenizer(
    formatted_prompts,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=2048,
).to(teacher_model.device)


print("Batch size:", len(formatted_prompts))
print("Input tensor shape:", inputs["input_ids"].shape)


# Generate
with torch.inference_mode():
    outputs = teacher_model.generate(
        **inputs,
        max_new_tokens=96,
        do_sample=False,
        pad_token_id=teacher_tokenizer.pad_token_id,
    )


# Decode only the newly generated tokens.
# Because padding is on the LEFT, every row has the same
# input tensor width, so we remove that common width.
input_width = inputs["input_ids"].shape[1]

teacher_outputs = []

for i in range(len(formatted_prompts)):
    generated_tokens = outputs[i][input_width:]

    response = teacher_tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True,
    ).strip()

    teacher_outputs.append(response)


# Store results
teacher_pilot_df["teacher_output"] = teacher_outputs


print("\nGenerated examples:", len(teacher_pilot_df))

for _, row in teacher_pilot_df.iterrows():
    print("\n" + "=" * 100)
    print(f"SOURCE ID: {row['id']}")
    print(f"SOURCE: {row['title']}")
    print("\nTEACHER OUTPUT:")
    print(row["teacher_output"])

Batch size: 10
Input tensor shape: torch.Size([10, 585])

Generated examples: 10

====================================================================================================
SOURCE ID: InternalMed_Harrison_3459
SOURCE: InternalMed_Harrison

TEACHER OUTPUT:
INSTRUCTION: What effect do glucocorticoids have on antidiuretic hormone (ADH) release, and how does this relate to euvolemic hyponatremia in secondary adrenal insufficiency?
RESPONSE: Glucocorticoids exert a negative feedback on ADH release by the posterior pituitary. In patients with secondary adrenal insufficiency, hydrocortisone replacement reduces circulating ADH, thereby normalizing the ADH response to

====================================================================================================
SOURCE ID: InternalMed_Harrison_22081
SOURCE: InternalMed_Harrison

TEACHER OUTPUT:
INSTRUCTION: What characteristic imaging finding is associated with analgesic nephropathy?
RESPONSE: Small, scarred kidneys with papillary calcifications best appreciated by computed tomography.

====================================================================================================
SOURCE ID: InternalMed_Harrison_11987
SOURCE: InternalMed_Harrison

TEACHER OUTPUT:
INSTRUCTION: What is the recommended antimicrobial regimen for treating L. monocytogenes infections in a patient with renal insufficiency?
RESPONSE: Ampicillin should be administered at high doses (2 g every 6 h), and the dosage must be reduced for patients with renal insufficiency. Gentamicin can be added for synergy, but its necessity is uncertain due to inconclusive evidence. Alternative options include TMP-SMX (15–20 mg of

====================================================================================================
SOURCE ID: Pharmacology_Katzung_1490
SOURCE: Pharmacology_Katzung

TEACHER OUTPUT:
INSTRUCTION: What has led to the acute kidney injury in this patient?
RESPONSE: The acute kidney injury (AKI) in this patient is likely due to volume depletion from diuretic-induced hypovolemia, as evidenced by the significant weight loss (15 kg in 2 weeks) and the marked decrease in blood pressure (from 176/92 mm Hg to 91/58 mm Hg).

====================================================================================================
SOURCE ID: InternalMed_Harrison_21808
SOURCE: InternalMed_Harrison

TEACHER OUTPUT:
INSTRUCTION: What role do ACE inhibitors play in managing chronic renal transplant dysfunction?
RESPONSE: ACE inhibitors are thought to have a beneficial influence on the rate of progression of chronic renal transplant dysfunction by controlling systemic and intrarenal hypertension.

====================================================================================================
SOURCE ID: InternalMed_Harrison_4478
SOURCE: InternalMed_Harrison

TEACHER OUTPUT:
INSTRUCTION: How can the anemia associated with acute or chronic inflammation be distinguished from other types of hypoproliferative anemia based on laboratory findings?
RESPONSE: The anemia associated with acute or chronic inflammation shows a distinctive pattern of low serum iron, normal or low total iron-binding capacity (TIBC), low percent transferrin saturation, and normal or high serum ferritin.

====================================================================================================
SOURCE ID: InternalMed_Harrison_22090
SOURCE: InternalMed_Harrison

TEACHER OUTPUT:
INSTRUCTION: How should lithium levels be managed in patients with renal impairment?
RESPONSE: Lithium levels should be monitored frequently and adjusted to avoid toxic levels (preferably <1 meq/L), especially since lithium is cleared less effectively as renal function declines.

====================================================================================================
SOURCE ID: Physiology_Levy_3517
SOURCE: Physiology_Levy

TEACHER OUTPUT:
INSTRUCTION: How does dietary sodium intake affect the restoration of extracellular fluid volume (ECFV) after a contraction?
RESPONSE: Dietary sodium intake can accelerate the restoration of euvolemia.

====================================================================================================
SOURCE ID: InternalMed_Harrison_1983
SOURCE: InternalMed_Harrison

TEACHER OUTPUT:
INSTRUCTION: What are some metabolic conditions listed in the passage that can cause delirium?
RESPONSE: Electrolyte disturbances such as hypoglycemia, hyperglycemia, hyponatremia, hypernatremia, hypercalcemia, hypocalcemia, and hypomagnesemia can cause delirium.

====================================================================================================
SOURCE ID: InternalMed_Harrison_3373
SOURCE: InternalMed_Harrison

TEACHER OUTPUT:
INSTRUCTION: What serologic and hematologic tests are mentioned in the passage for evaluating renal diseases?
RESPONSE: Blood cultures, anti-GBM antibody, ANCA, complement levels, cryoglobulins, hepatitis B and C serologies, VDRL, HIV, and ASLO.

**7.6.6 Prepare the Full Teacher-Generation Dataset**

The teacher-model pilot established that Qwen2.5-7B-Instruct can generate coherent nephrology educational examples when used with left-padded batched inference.

We now prepare the full set of cleaned nephrology passages for synthetic instruction-response generation.

Each source passage will produce at most one training example. Passages for which the teacher determines that a strong nephrology teaching example cannot be constructed will be marked `SKIP`.

The generation process will be performed in small batches and saved incrementally. This protects the experiment from losing already-generated examples if the Kaggle session is interrupted.

The raw teacher output will be retained together with the source identifier so that every generated example remains traceable to its originating passage.

**Expected outcome:** create a clean generation queue containing the selected nephrology passages that will be processed by the Qwen teacher model.

In [43]:
# Prepare the full teacher-generation queue.

teacher_generation_df = clean_df[
    [
        "id",
        "title",
        "content_clean",
    ]
].copy()

# Reset row numbering for deterministic batching.
teacher_generation_df.reset_index(drop=True, inplace=True)

# Add fields that will be populated during generation.
teacher_generation_df["teacher_output"] = ""
teacher_generation_df["generation_status"] = "PENDING"

print("Teacher-generation queue:", len(teacher_generation_df))

print("\nSource distribution:")
print(
    teacher_generation_df["title"]
    .value_counts()
    .sort_index()
)

print("\nGeneration status:")
print(
    teacher_generation_df["generation_status"]
    .value_counts()
)

Teacher-generation queue: 3113

Source distribution:
title
Anatomy_Gray              42
InternalMed_Harrison    2021
Pathology_Robbins        282
Pathoma_Husain            58
Pharmacology_Katzung     431
Physiology_Levy          279
Name: count, dtype: int64

Generation status:
generation_status
PENDING    3113
Name: count, dtype: int64

**7.6.7 Generate Synthetic Q&A with the Qwen Teacher**

We now generate the synthetic instruction-response dataset using
Qwen2.5-7B-Instruct.

The generation is performed in small batches rather than one passage
at a time. This improves GPU utilization while keeping memory usage
manageable on the Kaggle T4 GPU.

Each batch is saved immediately after generation. This creates a
checkpointed generation process so that completed examples are not
lost if the notebook session is interrupted.

For each source passage, the teacher produces either:

- one `INSTRUCTION` / `RESPONSE` pair; or
- `SKIP` when the passage does not support a sufficiently focused
  nephrology teaching example.

The raw teacher output is retained for later parsing and quality
validation.

### Generation configuration

- Teacher model: Qwen2.5-7B-Instruct
- Quantization: 4-bit NF4
- Generation: deterministic (`do_sample=False`)
- Batch size: 16
- Maximum generated tokens: 128
- Incremental checkpointing: enabled

**Expected outcome:** progressively generate and save the synthetic
nephrology training corpus while preserving intermediate checkpoints.

In [ ]:
# Generate the full synthetic training corpus in checkpointed batches.

import os
import torch
import pandas as pd

BATCH_SIZE = 16
MAX_NEW_TOKENS = 128

checkpoint_dir = "/kaggle/working/nephrollm_teacher_batches"
os.makedirs(checkpoint_dir, exist_ok=True)

total_rows = len(teacher_generation_df)

print("Total passages:", total_rows)
print("Batch size:", BATCH_SIZE)
print("Expected batches:", (total_rows + BATCH_SIZE - 1) // BATCH_SIZE)
print("Checkpoint directory:", checkpoint_dir)


def generate_teacher_batch(passages):
    """Generate one teacher response for each passage in a batch."""

    formatted_prompts = []

    for passage in passages:

        prompt = create_teacher_training_example_prompt(
            passage
        )

        messages = [
            {
                "role": "system",
                "content": (
                    "You generate high-quality, concise, grounded "
                    "nephrology educational training examples."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ]

        formatted_prompts.append(
            teacher_tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
            )
        )

    # Tokenize as a left-padded batch
    inputs = teacher_tokenizer(
        formatted_prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=2048,
    ).to(teacher_model.device)

    with torch.inference_mode():
        outputs = teacher_model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            pad_token_id=teacher_tokenizer.pad_token_id,
        )

    # Because the tokenizer uses left padding, all rows have
    # the same input width.
    input_width = inputs["input_ids"].shape[1]

    responses = []

    for i in range(len(passages)):

        generated_tokens = outputs[i][input_width:]

        response = teacher_tokenizer.decode(
            generated_tokens,
            skip_special_tokens=True,
        ).strip()

        responses.append(response)

    return responses


# Process batches sequentially.
for start_idx in range(0, total_rows, BATCH_SIZE):

    end_idx = min(
        start_idx + BATCH_SIZE,
        total_rows,
    )

    batch_number = start_idx // BATCH_SIZE + 1

    checkpoint_path = os.path.join(
        checkpoint_dir,
        f"teacher_batch_{batch_number:04d}.csv",
    )

    # Skip an already completed checkpoint.
    if os.path.exists(checkpoint_path):
        print(
            f"Batch {batch_number}: checkpoint already exists — skipping."
        )
        continue

    batch_df = teacher_generation_df.iloc[
        start_idx:end_idx
    ].copy()

    print(
        f"\nGenerating batch {batch_number} "
        f"({start_idx + 1}-{end_idx} of {total_rows})..."
    )

    try:

        batch_df["teacher_output"] = generate_teacher_batch(
            batch_df["content_clean"].tolist()
        )

        batch_df["generation_status"] = "GENERATED"

        batch_df.to_csv(
            checkpoint_path,
            index=False,
        )

        print(
            f"Batch {batch_number} saved: "
            f"{checkpoint_path}"
        )

    except Exception as e:

        print(
            f"Batch {batch_number} failed: {type(e).__name__}: {e}"
        )

        raise

print("\nTeacher generation completed for all batches.")

Total passages: 3113
Batch size: 16
Expected batches: 195
Checkpoint directory: /kaggle/working/nephrollm_teacher_batches

Generating batch 1 (1-16 of 3113)...
Batch 1 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0001.csv

Generating batch 2 (17-32 of 3113)...
Batch 2 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0002.csv

Generating batch 3 (33-48 of 3113)...
Batch 3 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0003.csv

Generating batch 4 (49-64 of 3113)...
Batch 4 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0004.csv

Generating batch 5 (65-80 of 3113)...
Batch 5 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0005.csv

Generating batch 6 (81-96 of 3113)...
Batch 6 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0006.csv

Generating batch 7 (97-112 of 3113)...
Batch 7 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0007.csv

Generating batch 8 (113-128 of 3113)...
Batch 8 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0008.csv

Generating batch 9 (129-144 of 3113)...
Batch 9 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0009.csv

Generating batch 10 (145-160 of 3113)...
Batch 10 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0010.csv

Generating batch 11 (161-176 of 3113)...
Batch 11 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0011.csv

Generating batch 12 (177-192 of 3113)...
Batch 12 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0012.csv

Generating batch 13 (193-208 of 3113)...
Batch 13 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0013.csv

Generating batch 14 (209-224 of 3113)...
Batch 14 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0014.csv

Generating batch 15 (225-240 of 3113)...
Batch 15 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0015.csv

Generating batch 16 (241-256 of 3113)...
Batch 16 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0016.csv

Generating batch 17 (257-272 of 3113)...
Batch 17 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0017.csv

Generating batch 18 (273-288 of 3113)...
Batch 18 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0018.csv

Generating batch 19 (289-304 of 3113)...
Batch 19 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0019.csv

Generating batch 20 (305-320 of 3113)...
Batch 20 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0020.csv

Generating batch 21 (321-336 of 3113)...
Batch 21 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0021.csv

Generating batch 22 (337-352 of 3113)...
Batch 22 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0022.csv

Generating batch 23 (353-368 of 3113)...
Batch 23 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0023.csv

Generating batch 24 (369-384 of 3113)...
Batch 24 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0024.csv

Generating batch 25 (385-400 of 3113)...
Batch 25 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0025.csv

Generating batch 26 (401-416 of 3113)...
Batch 26 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0026.csv

Generating batch 27 (417-432 of 3113)...
Batch 27 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0027.csv

Generating batch 28 (433-448 of 3113)...
Batch 28 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0028.csv

Generating batch 29 (449-464 of 3113)...
Batch 29 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0029.csv

Generating batch 30 (465-480 of 3113)...
Batch 30 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0030.csv

Generating batch 31 (481-496 of 3113)...
Batch 31 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0031.csv

Generating batch 32 (497-512 of 3113)...
Batch 32 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0032.csv

Generating batch 33 (513-528 of 3113)...
Batch 33 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0033.csv

Generating batch 34 (529-544 of 3113)...
Batch 34 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0034.csv

Generating batch 35 (545-560 of 3113)...
Batch 35 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0035.csv

Generating batch 36 (561-576 of 3113)...
Batch 36 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0036.csv

Generating batch 37 (577-592 of 3113)...
Batch 37 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0037.csv

Generating batch 38 (593-608 of 3113)...
Batch 38 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0038.csv

Generating batch 39 (609-624 of 3113)...
Batch 39 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0039.csv

Generating batch 40 (625-640 of 3113)...
Batch 40 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0040.csv

Generating batch 41 (641-656 of 3113)...
Batch 41 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0041.csv

Generating batch 42 (657-672 of 3113)...
Batch 42 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0042.csv

Generating batch 43 (673-688 of 3113)...
Batch 43 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0043.csv

Generating batch 44 (689-704 of 3113)...
Batch 44 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0044.csv

Generating batch 45 (705-720 of 3113)...
Batch 45 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0045.csv

Generating batch 46 (721-736 of 3113)...
Batch 46 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0046.csv

Generating batch 47 (737-752 of 3113)...
Batch 47 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0047.csv

Generating batch 48 (753-768 of 3113)...
Batch 48 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0048.csv

Generating batch 49 (769-784 of 3113)...
Batch 49 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0049.csv

Generating batch 50 (785-800 of 3113)...
Batch 50 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0050.csv

Generating batch 51 (801-816 of 3113)...
Batch 51 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0051.csv

Generating batch 52 (817-832 of 3113)...
Batch 52 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0052.csv

Generating batch 53 (833-848 of 3113)...
Batch 53 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0053.csv

Generating batch 54 (849-864 of 3113)...
Batch 54 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0054.csv

Generating batch 55 (865-880 of 3113)...
Batch 55 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0055.csv

Generating batch 56 (881-896 of 3113)...
Batch 56 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0056.csv

Generating batch 57 (897-912 of 3113)...
Batch 57 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0057.csv

Generating batch 58 (913-928 of 3113)...
Batch 58 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0058.csv

Generating batch 59 (929-944 of 3113)...
Batch 59 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0059.csv

Generating batch 60 (945-960 of 3113)...
Batch 60 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0060.csv

Generating batch 61 (961-976 of 3113)...
Batch 61 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0061.csv

Generating batch 62 (977-992 of 3113)...
Batch 62 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0062.csv

Generating batch 63 (993-1008 of 3113)...
Batch 63 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0063.csv

Generating batch 64 (1009-1024 of 3113)...
Batch 64 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0064.csv

Generating batch 65 (1025-1040 of 3113)...
Batch 65 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0065.csv

Generating batch 66 (1041-1056 of 3113)...
Batch 66 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0066.csv

Generating batch 67 (1057-1072 of 3113)...
Batch 67 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0067.csv

Generating batch 68 (1073-1088 of 3113)...
Batch 68 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0068.csv

Generating batch 69 (1089-1104 of 3113)...
Batch 69 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0069.csv

Generating batch 70 (1105-1120 of 3113)...
Batch 70 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0070.csv

Generating batch 71 (1121-1136 of 3113)...
Batch 71 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0071.csv

Generating batch 72 (1137-1152 of 3113)...
Batch 72 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0072.csv

Generating batch 73 (1153-1168 of 3113)...
Batch 73 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0073.csv

Generating batch 74 (1169-1184 of 3113)...
Batch 74 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0074.csv

Generating batch 75 (1185-1200 of 3113)...
Batch 75 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0075.csv

Generating batch 76 (1201-1216 of 3113)...
Batch 76 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0076.csv

Generating batch 77 (1217-1232 of 3113)...
Batch 77 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0077.csv

Generating batch 78 (1233-1248 of 3113)...
Batch 78 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0078.csv

Generating batch 79 (1249-1264 of 3113)...
Batch 79 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0079.csv

Generating batch 80 (1265-1280 of 3113)...
Batch 80 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0080.csv

Generating batch 81 (1281-1296 of 3113)...
Batch 81 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0081.csv

Generating batch 82 (1297-1312 of 3113)...
Batch 82 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0082.csv

Generating batch 83 (1313-1328 of 3113)...
Batch 83 saved: /kaggle/working/nephrollm_teacher_batches/teacher_batch_0083.csv

Generating batch 84 (1329-1344 of 3113)...

# 7.7 Check for Evaluation Leakage

Before finalizing the training dataset, we perform an explicit leakage check against the NephroLLM evaluation benchmark.

The evaluation benchmark contains:

- **636 primary-evaluation questions**
- **160 held-out questions**

None of these evaluation records should be intentionally present in the QLoRA training data.

### Leakage checks

We will compare the candidate training examples against the evaluation benchmark using available identifying information and normalized text.

The check will look for:

- exact question matches;
- exact answer or explanation matches where applicable;
- duplicated or near-duplicated question text; and
- obvious overlap between source-derived training examples and evaluation items.

### Why this matters

A fine-tuned model could appear to improve simply because it has been exposed to evaluation questions or their answers during training.

That would make the before-versus-after comparison difficult to interpret.

The leakage check therefore acts as a quality-control step before the final training dataset is created.

### Evaluation boundary

```text
Training corpus
      │
      ├── Allowed → independent nephrology educational content
      │
      └── Excluded → evaluation benchmark content

Evaluation benchmark
      │
      ├── 636 primary questions
      └── 160 held-out questions

**7.7.1 validate all 195 checkpoints before parsing anything.**

In [45]:
### Validate all teacher-generation checkpoints

import os
import glob
import pandas as pd

checkpoint_dir = "/kaggle/working/nephrollm_teacher_batches"

files = sorted(
    glob.glob(
        os.path.join(
            checkpoint_dir,
            "teacher_batch_*.csv"
        )
    )
)

# Extract batch numbers
batch_numbers = sorted(
    int(
        os.path.basename(f)
        .split("_")[-1]
        .replace(".csv", "")
    )
    for f in files
)

expected_batches = set(range(1, 196))
existing_batches = set(batch_numbers)

missing_batches = sorted(
    expected_batches - existing_batches
)

unexpected_batches = sorted(
    existing_batches - expected_batches
)

print("Teacher checkpoint validation")
print("=" * 60)

print(f"Checkpoint files found : {len(files)}")
print(f"Expected checkpoint files: 195")
print(f"First batch            : {batch_numbers[0] if batch_numbers else 'None'}")
print(f"Last batch             : {batch_numbers[-1] if batch_numbers else 'None'}")

print("\nMissing batches:")
print(missing_batches if missing_batches else "None")

print("\nUnexpected batches:")
print(unexpected_batches if unexpected_batches else "None")


# Validate rows and statuses
total_rows = 0
all_ids = []
status_counts = {}

for file_path in files:
    df = pd.read_csv(file_path)

    total_rows += len(df)

    all_ids.extend(df["id"].astype(str).tolist())

    for status, count in df["generation_status"].value_counts().items():
        status_counts[status] = (
            status_counts.get(status, 0) + count
        )


duplicate_ids = (
    pd.Series(all_ids)
    .value_counts()
)

duplicate_ids = duplicate_ids[
    duplicate_ids > 1
]


print("\nRow validation")
print("=" * 60)

print(f"Total rows              : {total_rows}")
print(f"Expected rows           : 3113")

print("\nGeneration status:")
print(status_counts)

print(f"\nUnique source IDs       : {len(set(all_ids))}")
print(f"Duplicate source IDs    : {len(duplicate_ids)}")

if not duplicate_ids.empty:
    print("\nDuplicate IDs:")
    print(duplicate_ids.head(20))


# Final validation summary
validation_passed = (
    len(files) == 195
    and not missing_batches
    and not unexpected_batches
    and total_rows == 3113
    and len(set(all_ids)) == 3113
    and not duplicate_ids.size
)

print("\n" + "=" * 60)

if validation_passed:
    print("✅ CHECKPOINT VALIDATION PASSED")
    print("All 195 batches and 3,113 source passages are accounted for.")
else:
    print("⚠️ CHECKPOINT VALIDATION REQUIRES REVIEW")

Teacher checkpoint validation
============================================================
Checkpoint files found : 195
Expected checkpoint files: 195
First batch            : 1
Last batch             : 195

Missing batches:
None

Unexpected batches:
None

Row validation
============================================================
Total rows              : 3113
Expected rows           : 3113

Generation status:
{'GENERATED': 3113}

Unique source IDs       : 3113
Duplicate source IDs    : 0

============================================================
✅ CHECKPOINT VALIDATION PASSED
All 195 batches and 3,113 source passages are accounted for.

**7.7.2 Combine Teacher-Generated Checkpoints**

The teacher-generation stage produced 195 checkpoint files covering all 3,113 selected nephrology passages.

The checkpoint validation confirmed that every expected batch is present and that each source passage appears exactly once.

We now combine these checkpoints into a single dataframe for downstream processing.

The original teacher output will be preserved unchanged at this stage. Parsing, quality filtering, deduplication, and evaluation-leakage checks will be performed on derived columns so that the raw generated output remains available for auditability.

**Expected outcome:** one master dataframe containing all 3,113 teacher-generated records with their source metadata and raw Qwen outputs.

In [46]:
### Combine all validated teacher-generation checkpoints

checkpoint_files = sorted(
    glob.glob(
        os.path.join(
            checkpoint_dir,
            "teacher_batch_*.csv"
        )
    )
)

teacher_generated_df = pd.concat(
    [
        pd.read_csv(file_path)
        for file_path in checkpoint_files
    ],
    ignore_index=True
)

print("Combined teacher-generation dataset")
print("=" * 60)

print("Rows:", len(teacher_generated_df))
print("Columns:", teacher_generated_df.columns.tolist())

print("\nSource distribution:")
print(
    teacher_generated_df["title"]
    .value_counts()
    .sort_index()
)

print("\nGeneration status:")
print(
    teacher_generated_df["generation_status"]
    .value_counts()
)

print("\nSample raw teacher output:")
print(
    teacher_generated_df[
        ["id", "title", "teacher_output"]
    ].head(3).to_string(index=False)
)

Combined teacher-generation dataset
============================================================
Rows: 3113
Columns: ['id', 'title', 'content_clean', 'teacher_output', 'generation_status']

Source distribution:
title
Anatomy_Gray              42
InternalMed_Harrison    2021
Pathology_Robbins        282
Pathoma_Husain            58
Pharmacology_Katzung     431
Physiology_Levy          279
Name: count, dtype: int64

Generation status:
generation_status
GENERATED    3113
Name: count, dtype: int64

Sample raw teacher output:
              id        title                                                                                                                                                                                                                                                                                teacher_output
Anatomy_Gray_347 Anatomy_Gray                                                                                                                                                                                                                                                                                          SKIP
Anatomy_Gray_460 Anatomy_Gray INSTRUCTION: Where does the hemiazygos vein typically arise and how does it connect to other veins?\nRESPONSE: The hemiazygos vein typically arises at the junction between the left ascending lumbar vein and the left subcostal vein, and it often has a connection to the left renal vein.
Anatomy_Gray_526 Anatomy_Gray                    INSTRUCTION: What is the role of FDG PET in imaging, and what does it detect?\nRESPONSE: In FDG PET, a gamma radiation emitter is attached to a glucose molecule. It detects areas of high metabolic activity, such as tumors, by excessive uptake of the labeled glucose.

**7.7.3 Parse Teacher-Generated Q&A**

The 3,113 teacher-generated records have now been combined into a single dataframe.

Each `teacher_output` contains either:

- a structured `INSTRUCTION` / `RESPONSE` pair; or
- `SKIP` when the teacher determined that the source passage was not suitable for a strong nephrology example.

We now parse these outputs into separate structured columns.

This step is intentionally limited to **format parsing**. We will not yet judge the medical quality or nephrology relevance of the generated examples.

The original `teacher_output` column will be retained unchanged so that every generated example remains auditable against the raw teacher response.

**Expected outcome:** classify every generated record as `VALID`, `SKIP`, or `INVALID` and extract the instruction and response where available.

In [47]:
### Parse teacher-generated outputs

import re

parsed_df = teacher_generated_df.copy()

parsed_df["instruction"] = ""
parsed_df["response"] = ""
parsed_df["parse_status"] = "INVALID"


def parse_teacher_output(output):
    """
    Parse the expected teacher format:

    INSTRUCTION: <question>
    RESPONSE: <answer>

    or:

    SKIP
    """

    if pd.isna(output):
        return "", "", "INVALID"

    text = str(output).strip()

    # Exact SKIP output
    if text.upper() == "SKIP":
        return "", "", "SKIP"

    # Extract instruction and response
    match = re.search(
        r"INSTRUCTION:\s*(.*?)\s*RESPONSE:\s*(.*)",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    if not match:
        return "", "", "INVALID"

    instruction = match.group(1).strip()
    response = match.group(2).strip()

    if not instruction or not response:
        return "", "", "INVALID"

    return instruction, response, "VALID"


parsed_results = parsed_df["teacher_output"].apply(
    parse_teacher_output
)

parsed_df[
    ["instruction", "response", "parse_status"]
] = pd.DataFrame(
    parsed_results.tolist(),
    index=parsed_df.index,
)

print("Teacher-output parsing")
print("=" * 60)

print("\nParse status:")
print(
    parsed_df["parse_status"]
    .value_counts()
)

print("\nTotal records:", len(parsed_df))

print("\nSample parsed records:")
print(
    parsed_df[
        [
            "id",
            "parse_status",
            "instruction",
            "response",
        ]
    ].head(10).to_string(index=False)
)

Teacher-output parsing
============================================================

Parse status:
parse_status
VALID    2888
SKIP      225
Name: count, dtype: int64

Total records: 3113

Sample parsed records:
              id parse_status                                                                                  instruction                                                                                                                                                                                                     response
Anatomy_Gray_347         SKIP
Anatomy_Gray_460        VALID       Where does the hemiazygos vein typically arise and how does it connect to other veins?                               The hemiazygos vein typically arises at the junction between the left ascending lumbar vein and the left subcostal vein, and it often has a connection to the left renal vein.
Anatomy_Gray_526        VALID                             What is the role of FDG PET in imaging, and what does it detect?                            In FDG PET, a gamma radiation emitter is attached to a glucose molecule. It detects areas of high metabolic activity, such as tumors, by excessive uptake of the labeled glucose.
Anatomy_Gray_527        VALID    How does the pain associated with pericarditis differ from that of myocardial infarction?                                                                                                   The pain from pericarditis may be relieved by sitting forward, unlike the pain from myocardial infarction.
Anatomy_Gray_544         SKIP
Anatomy_Gray_619        VALID                     Which major veins contribute to the formation of the inferior vena cava?                      The left renal vein and the left common iliac vein contribute to the formation of the inferior vena cava by crossing the midline and joining with their counterparts on the right side.
Anatomy_Gray_715         SKIP
Anatomy_Gray_769        VALID     Where do the left and right renal arteries typically arise from, and how do they differ?                                                        The left renal artery usually arises a little higher than the right. The right renal artery is longer and passes posterior to the inferior vena cava.
Anatomy_Gray_770        VALID What anatomical feature makes the left renal vein susceptible to compression by an aneurysm? The left renal vein crosses the midline anterior to the abdominal aorta and posterior to the superior mesenteric artery, making it susceptible to compression by an aneurysm in either of these two vessels.
Anatomy_Gray_771        VALID                  At which three points along their course do the ureters become constricted?                                    The ureters become constricted at the ureteropelvic junction, where they cross the common iliac vessels at the pelvic brim, and where they enter the wall of the bladder.

**7.7.4 Inspect Generated Q&A Quality by Source**

The parser identified 2,888 structurally valid instruction-response pairs.

A structurally valid pair is not necessarily suitable for the final nephrology training set. The teacher may generate a well-formed question from a passage whose central topic is actually outside nephrology.

We therefore first inspect the generated examples by their source textbook.

This diagnostic helps us understand where the generated Q&A is concentrated and whether certain source categories produce more peripheral examples.

No examples are removed in this step.

**Expected outcome:** quantify the valid training candidates by source and inspect representative examples before applying quality filters.

In [48]:
### Inspect valid teacher-generated examples by source

valid_teacher_df = parsed_df[
    parsed_df["parse_status"] == "VALID"
].copy()

print("Valid teacher-generated examples:", len(valid_teacher_df))

print("\nValid examples by source:")
print(
    valid_teacher_df["title"]
    .value_counts()
    .sort_index()
)

# Show a small random sample from each source
sample_per_source = 5

for source in sorted(valid_teacher_df["title"].unique()):

    source_df = valid_teacher_df[
        valid_teacher_df["title"] == source
    ]

    sample = source_df.sample(
        n=min(sample_per_source, len(source_df)),
        random_state=42
    )

    print("\n" + "=" * 100)
    print(f"SOURCE: {source}")
    print("=" * 100)

    for _, row in sample.iterrows():
        print(f"\nID: {row['id']}")
        print(f"INSTRUCTION: {row['instruction']}")
        print(f"RESPONSE: {row['response']}")
        print("-" * 100)

Valid teacher-generated examples: 2888

Valid examples by source:
title
Anatomy_Gray              29
InternalMed_Harrison    1891
Pathology_Robbins        268
Pathoma_Husain            47
Pharmacology_Katzung     391
Physiology_Levy          262
Name: count, dtype: int64

====================================================================================================
SOURCE: Anatomy_Gray
====================================================================================================

ID: Anatomy_Gray_2003
INSTRUCTION: What surgical procedure is used to create a high-flow system for dialysis?
RESPONSE: The radial artery is anastomosed to the cephalic vein at the wrist, or the brachial artery is anastomosed to the cephalic vein at the elbow.
----------------------------------------------------------------------------------------------------

ID: Anatomy_Gray_925
INSTRUCTION: What unique characteristic of renal cell tumors makes them distinct from other types of tumors?
RESPONSE: Renal cell tumors grow outward from the kidney, invading the fat and fascia, and spread into the renal vein, which is rare for other types of tumors.
----------------------------------------------------------------------------------------------------

ID: Anatomy_Gray_840
INSTRUCTION: At which vertebral level is the approximate origin of the renal artery located?
RESPONSE: At the LI (Lumbar I) vertebral level.
----------------------------------------------------------------------------------------------------

ID: Anatomy_Gray_979
INSTRUCTION: What anatomical changes can be associated with a large renal cell carcinoma?
RESPONSE: Large renal cell carcinomas have the propensity to grow into the renal vein, the inferior vena cava, and the right atrium and may extend through the heart into the pulmonary artery.
----------------------------------------------------------------------------------------------------

ID: Anatomy_Gray_775
INSTRUCTION: How does the suprarenal vein differ between the right and left sides?
RESPONSE: On the right side, the right suprarenal vein is short and almost immediately enters the inferior vena cava, while on the left side, the left suprarenal vein passes inferiorly to enter the left renal vein.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: InternalMed_Harrison
====================================================================================================

ID: InternalMed_Harrison_29446
INSTRUCTION: What is the recommended action by the American College of Radiology regarding gadolinium-based MR contrast agents in certain patients?
RESPONSE: A glomerular filtration rate (GFR) assessment should be obtained within 6 weeks prior to elective gadolinium-based MR contrast agent administration in patients with a history of renal disease (including solitary kidney, renal transplant, renal tumor).
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_21758
INSTRUCTION: What was the ratio of deceased to living donors for kidney transplants in the United States in 2011?
RESPONSE: The ratio of deceased to living donors for kidney transplants in the United States in 2011 remained stable, but the specific ratio is not provided in the passage.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_3426
INSTRUCTION: How does angiotensin II affect sodium reabsorption in the kidneys?
RESPONSE: Angiotensin II activates proximal Na+-Cl– reabsorption.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_28573
INSTRUCTION: How does effective treatment of osteomalacia affect parathyroid hormone (PTH) secretion?
RESPONSE: Effective treatment of osteomalacia with calcium and vitamin D leads to reversal of the abnormal pattern of PTH secretion over weeks, accompanied by involution of parathyroid gland mass to normal.
----------------------------------------------------------------------------------------------------

ID: InternalMed_Harrison_22043
INSTRUCTION: What are some common presenting features of Acute Tubulointerstitial Nephritis (TIN)?
RESPONSE: Acute Tubulointerstitial Nephritis (TIN) most often presents with acute renal failure. Other common features include flank pain due to distention of the renal capsule, and an active urinary sediment with leukocytes and cellular casts.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pathology_Robbins
====================================================================================================

ID: Pathology_Robbins_3349
INSTRUCTION: What are the two main locations where immune complexes can deposit in glomerulopathies?
RESPONSE: Subepithelial and subendothelial.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_3485
INSTRUCTION: What are the two major types of cystic disease affecting the medulla mentioned in the passage?
RESPONSE: The two major types of cystic disease affecting the medulla mentioned in the passage are medullary sponge kidney and nephronophthisis-medullary cystic disease complex.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_888
INSTRUCTION: In systemic lupus erythematosus (SLE), what type of autoantibodies are often found and what is their significance?
RESPONSE: In systemic lupus erythematosus (SLE), "generic" anti-nuclear antibodies (ANAs) are often found. These autoantibodies are significant because they are involved in immune complex-mediated glomerulonephritis, which is typical of this disease.
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_3371
INSTRUCTION: What are the primary causes of nephrotic syndrome mentioned in the passage?
RESPONSE: The primary causes of nephrotic syndrome mentioned in the passage are ingestion of drugs (gold, penicillamine, "street heroin"), infections (malaria, syphilis, hepatitis B, HIV), malignancy (carcinoma, melanoma), and miscellaneous causes (bee sting allergy, hereditary nephritis).
----------------------------------------------------------------------------------------------------

ID: Pathology_Robbins_3351
INSTRUCTION: Where can electron-dense immune deposits be found in glomeruli?
RESPONSE: Electron-dense immune deposits can be found in one or more of three locations: between the endothelial cells and the GBM (subendothelial deposits), between the outer surface of the GBM and the podocytes (subepithelial deposits), or in the mesangium.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pathoma_Husain
====================================================================================================

ID: Pathoma_Husain_315
INSTRUCTION: What is the typical outcome for children with rapidly progressive glomerulonephritis?
RESPONSE: Children rarely (1%) progress to renal failure.
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_395
INSTRUCTION: What is the primary mechanism leading to secondary hyperparathyroidism in chronic renal failure?
RESPONSE: Renal insufficiency leads to decreased phosphate excretion, which causes serum phosphate to bind free calcium, stimulating all four parathyroid glands to produce excess PTH.
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_314
INSTRUCTION: What are the key clinical features of post-streptococcal glomerulonephritis?
RESPONSE: The key clinical features include hematuria (cola-colored urine), oliguria, hypertension, and periorbital edema, occurring 2-3 weeks after infection.
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_412
INSTRUCTION: What are the common causes of Addison disease?
RESPONSE: The common causes of Addison disease include autoimmune destruction (most common cause in the West), tuberculosis (most common cause in the developing world), and metastatic carcinoma.
----------------------------------------------------------------------------------------------------

ID: Pathoma_Husain_312
INSTRUCTION: What are the two types of dense deposit disease based on the location of immune complex deposits, and what are their associated conditions?
RESPONSE: Type I is subendothelial and associated with HBV and HCV, while Type II (dense deposit disease) is intramembranous and associated with C3 nephritic factor.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Pharmacology_Katzung
====================================================================================================

ID: Pharmacology_Katzung_369
INSTRUCTION: What is the significance of the reduced plasma bicarbonate level in this patient's condition?
RESPONSE: The reduced plasma bicarbonate level indicates metabolic acidosis, which may be related to the patient's reduced glomerular filtration rate and overall renal impairment.
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_1494
INSTRUCTION: What does the passage indicate about the relationship between the physiology of nephron segments and drug action?
RESPONSE: The physiology of each nephron segment is closely linked to the basic pharmacology of the drugs acting there.
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_1113
INSTRUCTION: Which class of antihypertensive drugs is particularly beneficial for patients with both diabetes and proteinuria?
RESPONSE: Drugs that inhibit the renin-angiotensin system are particularly useful in patients with diabetes or evidence of chronic kidney disease with proteinuria.
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_5534
INSTRUCTION: Which factors increase the risk of more serious side effects from amantadine?
RESPONSE: More serious side effects from amantadine are associated with high plasma concentrations, renal insufficiency, seizure disorders, and advanced age.
----------------------------------------------------------------------------------------------------

ID: Pharmacology_Katzung_6704
INSTRUCTION: What is a potential risk of applying gentamicin topically to large areas of denuded skin?
RESPONSE: Renal failure may permit the accumulation of gentamicin, leading to nephrotoxicity, neurotoxicity, and ototoxicity.
----------------------------------------------------------------------------------------------------

====================================================================================================
SOURCE: Physiology_Levy
====================================================================================================

ID: Physiology_Levy_4052
INSTRUCTION: What effect does thyroid hormone have on blood pressure and pulse pressure?
RESPONSE: Systolic blood pressure is modestly augmented and diastolic blood pressure is decreased, resulting in a widened pulse pressure.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3604
INSTRUCTION: How do thiazide diuretics affect urinary calcium excretion?
RESPONSE: Thiazide diuretics reduce urinary calcium excretion.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3525
INSTRUCTION: What are the hormones and factors that regulate plasma K+ levels?
RESPONSE: The hormones and factors that regulate plasma K+ levels include aldosterone, insulin, and the renin-angiotensin-aldosterone system (RAAS).
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3484
INSTRUCTION: How does the macula densa regulate renin secretion?
RESPONSE: When NaCl delivery to the macula densa is decreased, renin secretion is enhanced. Conversely, an increase in NaCl delivery inhibits renin secretion.
----------------------------------------------------------------------------------------------------

ID: Physiology_Levy_3217
INSTRUCTION: What is the clearance of a substance if it is present in plasma at a concentration of 1 mg/mL and in urine at a concentration of 100 mg/mL, with a urine flow rate of 1 mL/min?
RESPONSE: The clearance of the substance is 1 mL/min.
----------------------------------------------------------------------------------------------------

**7.7.5 Identify Potentially Peripheral Training Examples**

The generated Q&A inspection shows that some structurally valid examples are strongly nephrology-focused, while others are only indirectly related to renal medicine.

We therefore introduce a conservative quality-screening step.

The screen will flag examples whose question and answer contain little or no explicit renal/nephrology terminology. It will be used for **diagnostic review first**, not automatic deletion.

This approach avoids discarding valid examples simply because they come from a broad medical textbook.

Examples that clearly teach renal physiology, kidney disease, renal pathology, electrolyte/acid-base mechanisms, dialysis, transplantation, or related renal concepts should remain eligible.

**Expected outcome:** identify potentially peripheral examples for review while preserving the complete parsed dataset.

In [49]:
### Flag potentially peripheral teacher-generated examples

nephro_terms = [
    "kidney",
    "renal",
    "nephro",
    "nephron",
    "glomerul",
    "glomerular",
    "glomerulonephritis",
    "nephritis",
    "nephrotic",
    "nephropathy",
    "tubular",
    "tubulointerstitial",
    "dialysis",
    "hemodialysis",
    "haemodialysis",
    "peritoneal dialysis",
    "transplant",
    "gfr",
    "glomerular filtration",
    "creatinine",
    "urea",
    "proteinuria",
    "hematuria",
    "haematuria",
    "oliguria",
    "anuria",
    "polyuria",
    "electrolyte",
    "hyperkalemia",
    "hypokalemia",
    "hyponatremia",
    "hypernatremia",
    "acid-base",
    "metabolic acidosis",
    "metabolic alkalosis",
    "renal artery",
    "renal vein",
    "renin",
    "aldosterone",
    "raas",
    "macula densa",
    "podocyte",
    "mesangial",
    "glomerulus",
    "glomeruli",
    "ureter",
    "urinary",
    "urine",
    "nephrolithiasis",
    "kidney stone",
    "renal stone",
    "polycystic kidney",
    "renal failure",
    "renal insufficiency",
    "chronic kidney disease",
    "acute kidney injury",
]

term_pattern = "|".join(
    re.escape(term)
    for term in nephro_terms
)

quality_df = valid_teacher_df.copy()

quality_df["qa_text"] = (
    quality_df["instruction"].fillna("")
    + " "
    + quality_df["response"].fillna("")
).str.lower()

quality_df["has_nephro_signal"] = quality_df[
    "qa_text"
].str.contains(
    term_pattern,
    regex=True,
    na=False
)

print("Quality-screening diagnostics")
print("=" * 60)

print("Total VALID examples:", len(quality_df))

print(
    "Examples with explicit nephrology/renal signal:",
    quality_df["has_nephro_signal"].sum()
)

print(
    "Potentially peripheral examples:",
    (~quality_df["has_nephro_signal"]).sum()
)

print("\nPotentially peripheral examples by source:")
print(
    quality_df.loc[
        ~quality_df["has_nephro_signal"],
        "title"
    ].value_counts().sort_index()
)

Quality-screening diagnostics
============================================================
Total VALID examples: 2888
Examples with explicit nephrology/renal signal: 2078
Potentially peripheral examples: 810

Potentially peripheral examples by source:
title
Anatomy_Gray              3
InternalMed_Harrison    537
Pathology_Robbins        48
Pathoma_Husain           18
Pharmacology_Katzung    148
Physiology_Levy          56
Name: count, dtype: int64

**7.7.5 Deduplicate Generated Q&A**

We'll keep all 2,888 structurally valid Q&A pairs and exclude only the 225 explicit SKIP records.

That gives us a clean, reproducible rule:

Training candidates = teacher outputs that successfully follow the required INSTRUCTION / RESPONSE format.

The potential topical noise is now a documented limitation rather than something we artificially optimize away.
*****************************

The teacher-generation stage produced 2,888 structurally valid instruction-response pairs.

We will now check for duplicate generated examples.

This is a data-integrity step rather than a medical-quality filter. We will retain every structurally valid example unless it is an exact duplicate of another generated question.

The original source passage and raw `teacher_output` will remain available for auditability.

**Expected outcome:** identify and remove only exact duplicate training questions, if any, before checking for overlap with the evaluation benchmark.

In [50]:
### Check and remove exact duplicate generated questions

training_candidates = valid_teacher_df.copy()

before_count = len(training_candidates)

# Normalize only for duplicate detection.
# The original instruction text remains unchanged.
training_candidates["instruction_normalized"] = (
    training_candidates["instruction"]
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

duplicate_mask = training_candidates[
    "instruction_normalized"
].duplicated(
    keep="first"
)

duplicate_count = duplicate_mask.sum()

training_candidates = training_candidates[
    ~duplicate_mask
].copy()

training_candidates.reset_index(drop=True, inplace=True)

print("Generated Q&A deduplication")
print("=" * 60)

print("Before deduplication:", before_count)
print("Exact duplicate questions:", duplicate_count)
print("After deduplication:", len(training_candidates))

print(
    "\nDuplicate examples removed:",
    duplicate_count
)

Generated Q&A deduplication
============================================================
Before deduplication: 2888
Exact duplicate questions: 3
After deduplication: 2885

Duplicate examples removed: 3

**7.7.6 Check for Exact Evaluation Leakage**

The final training candidates currently contain 2,885 generated instruction-response examples.

Before using them for QLoRA, we check whether any generated training instruction exactly matches a question in the NephroLLM evaluation benchmark.

The benchmark contains:

- 636 primary-evaluation questions; and
- 160 held-out questions.

For this leakage check, only the **question text** is used as the reference. Benchmark answers, solutions, and explanations remain evaluation-only and are not introduced into the training data.

We normalize text only for comparison by:

- converting to lowercase;
- normalizing whitespace; and
- removing insignificant leading/trailing whitespace.

This detects exact question reuse while allowing differences in capitalization or spacing.

**Expected outcome:** identify any training instructions that exactly reproduce an evaluation question.

In [51]:
### Exact-match evaluation leakage check

import re
import pandas as pd

# Load the official evaluation benchmark
primary_eval_path = (
    "/kaggle/input/datasets/shantanuss/"
    "nejm-ai-nephrology-benchmark/"
    "nephrollm_primary_eval.csv"
)

heldout_eval_path = (
    "/kaggle/input/datasets/shantanuss/"
    "nejm-ai-nephrology-benchmark/"
    "nephrollm_heldout_eval.csv"
)

primary_eval_df = pd.read_csv(primary_eval_path)
heldout_eval_df = pd.read_csv(heldout_eval_path)

evaluation_df = pd.concat(
    [
        primary_eval_df.assign(eval_split="primary_eval"),
        heldout_eval_df.assign(eval_split="held_out"),
    ],
    ignore_index=True
)


def normalize_question(text):
    """Normalize text for exact-match comparison."""
    if pd.isna(text):
        return ""

    text = str(text).lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()


# Normalize training instructions
training_candidates["instruction_normalized"] = (
    training_candidates["instruction"]
    .apply(normalize_question)
)

# Normalize benchmark questions
evaluation_df["question_normalized"] = (
    evaluation_df["Question"]
    .apply(normalize_question)
)

# Build lookup of evaluation questions
evaluation_question_lookup = dict(
    zip(
        evaluation_df["question_normalized"],
        evaluation_df["BenchmarkID"]
    )
)

# Identify exact matches
training_candidates["exact_eval_match"] = (
    training_candidates["instruction_normalized"]
    .isin(evaluation_question_lookup)
)

exact_matches = training_candidates[
    training_candidates["exact_eval_match"]
].copy()

print("Exact-match leakage check")
print("=" * 60)

print("Training candidates:", len(training_candidates))
print("Evaluation questions:", len(evaluation_df))

print(
    "\nExact evaluation-question matches:",
    len(exact_matches)
)

if len(exact_matches) > 0:

    exact_matches["matched_benchmark_id"] = (
        exact_matches["instruction_normalized"]
        .map(evaluation_question_lookup)
    )

    print("\nPotential leakage examples:")
    print(
        exact_matches[
            [
                "id",
                "instruction",
                "matched_benchmark_id"
            ]
        ].to_string(index=False)
    )

else:
    print(
        "✅ No training instruction exactly matches "
        "an evaluation question."
    )

Exact-match leakage check
============================================================
Training candidates: 2885
Evaluation questions: 796

Exact evaluation-question matches: 0
✅ No training instruction exactly matches an evaluation question.

**7.7.7 Check for Near-Duplicate Evaluation Leakage**

Exact matching found no training instruction that reproduced an evaluation question verbatim.

Because the teacher model can paraphrase source material, we now perform a near-duplicate similarity check between:

- the 2,885 training instructions; and
- the 796 evaluation questions.

The purpose is to identify training instructions that may express substantially the same question as an evaluation item despite differences in wording.

This is a screening step. High similarity does not automatically mean leakage because two questions can legitimately test the same nephrology concept.

Potential matches will therefore be inspected before any training example is removed.

**Expected outcome:** identify and review highly similar training/evaluation question pairs.

In [52]:
### Near-duplicate screening using TF-IDF cosine similarity

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

train_questions = (
    training_candidates["instruction"]
    .fillna("")
    .astype(str)
    .tolist()
)

eval_questions = (
    evaluation_df["Question"]
    .fillna("")
    .astype(str)
    .tolist()
)

# Fit one vectorizer across both collections so they share the
# same vocabulary and representation.
vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    min_df=1,
    strip_accents="unicode",
)

combined_text = train_questions + eval_questions

tfidf_matrix = vectorizer.fit_transform(combined_text)

train_matrix = tfidf_matrix[:len(train_questions)]
eval_matrix = tfidf_matrix[len(train_questions):]

# Compare every training question against every evaluation question.
similarity_matrix = cosine_similarity(
    train_matrix,
    eval_matrix
)

# Find the highest-similarity evaluation question for each
# training instruction.
best_eval_index = similarity_matrix.argmax(axis=1)
best_similarity = similarity_matrix.max(axis=1)

near_duplicate_screen = training_candidates[
    [
        "id",
        "instruction",
        "response",
    ]
].copy()

near_duplicate_screen["best_eval_similarity"] = best_similarity
near_duplicate_screen["best_eval_index"] = best_eval_index

near_duplicate_screen["matched_benchmark_id"] = [
    evaluation_df.iloc[idx]["BenchmarkID"]
    for idx in best_eval_index
]

near_duplicate_screen["matched_eval_question"] = [
    evaluation_df.iloc[idx]["Question"]
    for idx in best_eval_index
]

# Sort from most similar to least similar.
near_duplicate_screen = near_duplicate_screen.sort_values(
    "best_eval_similarity",
    ascending=False
).reset_index(drop=True)

print("Near-duplicate screening")
print("=" * 60)

print("Training instructions:", len(train_questions))
print("Evaluation questions:", len(eval_questions))

print(
    "\nHighest similarity:",
    round(
        near_duplicate_screen["best_eval_similarity"].iloc[0],
        4
    )
)

print("\nTop 20 candidate pairs:")
print(
    near_duplicate_screen[
        [
            "id",
            "best_eval_similarity",
            "matched_benchmark_id",
            "instruction",
            "matched_eval_question",
        ]
    ].head(20).to_string(index=False)
)

Near-duplicate screening
============================================================
Training instructions: 2885
Evaluation questions: 796

Highest similarity: 0.6496

Top 20 candidate pairs:
                        id  best_eval_similarity matched_benchmark_id                                                                                                                                  instruction                                                                                                      matched_eval_question
 InternalMed_Harrison_3664              0.649611     NEPHRO-EVAL-0265                                                                            What is the most likely cause of the hypokalemia in this patient?                                                               What is the most likely cause of this patient’s hypokalemia?
 InternalMed_Harrison_3561              0.648236     NEPHRO-EVAL-0270                                                                                  What is the most frequent underlying cause of hyperkalemia?                                                                  What is the most likely underlying cause of hyperkalemia?
InternalMed_Harrison_24118              0.605879     NEPHRO-EVAL-0137                                         Which of the following is an absolute contraindication for transplantation according to the passage?                                      Which of the following is an absolute contraindication for hyperbaric oxygen therapy?
InternalMed_Harrison_13936              0.478943     NEPHRO-EVAL-0604                                            Which of the following treatments is NOT recommended for the conditions mentioned in the passage?                Which ONE of the following treatments is NOT recommended for treatment of COVID-19 disease in this patient?
InternalMed_Harrison_21908              0.471069  NEPHRO-HOLDOUT-0139                                                                            What are the typical clinical features of minimal change disease?                                     Regarding the management of minimal change disease, which of the following is correct?
InternalMed_Harrison_19628              0.395964     NEPHRO-EVAL-0083 What percentage of patients considered for renal revascularization have chronic kidney disease (CKD) with a GFR below 60 mL/min per 1.73 m2?            Which of the following risk tools would be appropriate to use in a population with GFR > 60 ml/min per 1.73 m2?
      Physiology_Levy_3530              0.390989     NEPHRO-EVAL-0267                                                                     What are the most common causes of hypokalemia mentioned in the passage?                                                                              What is the most likely cause of hypokalemia?
InternalMed_Harrison_21625              0.390322  NEPHRO-HOLDOUT-0069                                              What factors contribute to the development of metabolic acidosis in patients with advanced CKD?                                   Which of the following is correct with regard to treatment of metabolic acidosis in CKD?
    Pathology_Robbins_3394              0.385119     NEPHRO-EVAL-0546                                                                                   What are the typical clinical features of IgA nephropathy?                                                  Which of the following is correct regarding treatment of IgA nephropathy?
InternalMed_Harrison_21649              0.381120     NEPHRO-EVAL-0317                                           What are the primary risk factors for cardiovascular morbidity and mortality in patients with CKD? When considering this patient’s risk factors for cardiovascular outcomes and mortality, which of the following is correct?
    Pathology_Robbins_3455              0.370788     NEPHRO-EVAL-0545                                                     What are the primary forms of thrombotic microangiopathy (TMA) mentioned in the passage?                          Which of the following is correct regarding complement-mediated thrombotic microangiopathy (TMA)?
InternalMed_Harrison_22120              0.369438     NEPHRO-EVAL-0545                                                          What is the recommended treatment for HIV-related thrombotic microangiopathy (TMA)?                          Which of the following is correct regarding complement-mediated thrombotic microangiopathy (TMA)?
InternalMed_Harrison_21714              0.366600     NEPHRO-EVAL-0083                                  What is the recommended approach to initiating dialysis in patients with a GFR of 10-14 mL/min per 1.73 m2?            Which of the following risk tools would be appropriate to use in a population with GFR > 60 ml/min per 1.73 m2?
 Pharmacology_Katzung_5064              0.355327  NEPHRO-HOLDOUT-0118                                                                                                  What is the dosing regimen for tigecycline?              Which ONE of the following is the MOST appropriate dosing regimen for intravenous magnesium for this patient?
    Pathology_Robbins_3365              0.353822     NEPHRO-EVAL-0069                                                What is the most common cause of the nephrotic syndrome in children according to the passage?                                                        What is the MOST likely cause of this patient’s nephrotic syndrome?
 InternalMed_Harrison_3546              0.353264     NEPHRO-EVAL-0494                                          What initial laboratory tests should be performed to evaluate a patient with suspected hypokalemia?                                                                 Which ONE of the following tests should be performed next?
InternalMed_Harrison_21874              0.352722     NEPHRO-EVAL-0531                                                        What is the defining characteristic of anti-GBM disease in terms of its pathogenesis?           Regarding the treatment and outcome of anti-GBM disease in this patient, which of the following is MOST correct?
InternalMed_Harrison_28861              0.349311     NEPHRO-EVAL-0427                                                                      What are the different types of osteopetrosis mentioned in the passage?                          Which ONE of the following should you tell him about the different types of arteriovenous access?
        Pathoma_Husain_317              0.348795     NEPHRO-EVAL-0546                                                                             What is the typical presentation of IgA nephropathy in children?                                                  Which of the following is correct regarding treatment of IgA nephropathy?
InternalMed_Harrison_14269              0.345223  NEPHRO-HOLDOUT-0118                                       What is the recommended dosing regimen for cidofovir, and what is the primary reason for this regimen?              Which ONE of the following is the MOST appropriate dosing regimen for intravenous magnesium for this patient?

**What the near-duplicate check tells us**

The highest similarity is only 0.6496, and the top pair is:

Training: “What is the most likely cause of the hypokalemia in this patient?”
Evaluation: “What is the most likely cause of this patient’s hypokalemia?”

That's clearly very similar wording, but this alone doesn't establish data leakage. The questions could independently be generated from the same general nephrology concept.

The second pair is similar for the same reason: both ask about the underlying cause of hyperkalemia.

Several other high-scoring pairs are actually not semantically the same question despite sharing terminology. For example, transplantation vs. hyperbaric oxygen, or minimal-change-disease clinical features vs. treatment. That shows why we shouldn't use a simple cosine threshold to automatically remove examples.

I would use a conservative rule

For this project, I'd document:

No exact question overlap was identified. TF-IDF screening produced no obvious near-duplicate evaluation questions; the highest lexical similarity was 0.65, with high-scoring pairs generally sharing clinical terminology but addressing different questions.

I would not remove the 2,885 training examples based on this result.

This is also consistent with our decision not to over-filter the synthetic dataset.

One important distinction

The two high-similarity pairs about hypokalemia are worth noting in the experiment log, because they are the closest matches:

InternalMed_Harrison_3664 ↔ NEPHRO-EVAL-0265: 0.6496
InternalMed_Harrison_3561 ↔ NEPHRO-EVAL-0270: 0.6482

But I would classify these as conceptual overlap, not demonstrated leakage, based on the evidence we have.

Therefore our training set remains

2,885 examples

with:

0 exact evaluation-question matches
no obvious near-duplicate leakage requiring removal
raw teacher outputs preserved
source passage retained
225 explicit SKIPs excluded
3 exact duplicate questions removed

We can now move to 7.8 — Prepare the Final QLoRA Dataset.

# 7.8 Prepare the Final QLoRA Dataset

The leakage checks are complete:

- no exact evaluation-question matches were found;
- no obvious near-duplicate evaluation leakage was identified;
- 2,885 structurally valid, deduplicated teacher-generated examples remain.

We now convert these examples into the conversational format expected by Llama 3.2 3B Instruct.

Each example will contain:

- a system instruction defining the educational nephrology role;
- the generated educational question as the user message; and
- the teacher-generated answer as the assistant response.

The original source passage, source textbook, and raw teacher output will remain available as metadata for traceability, but they will not be included as additional conversational turns.

This produces the dataset that will be passed to the QLoRA fine-tuning pipeline.

**Expected outcome:** a final supervised fine-tuning dataset containing 2,885 nephrology educational instruction-response examples in Llama-compatible chat format.

In [53]:
### Build the final Llama chat-format training dataset

final_training_df = training_candidates.copy()

SYSTEM_MESSAGE = (
    "You are an educational assistant specializing in nephrology. "
    "Provide clear, factual, educational explanations. "
    "Do not provide diagnosis or personalized medical advice."
)

def build_chat_messages(row):
    return [
        {
            "role": "system",
            "content": SYSTEM_MESSAGE,
        },
        {
            "role": "user",
            "content": row["instruction"],
        },
        {
            "role": "assistant",
            "content": row["response"],
        },
    ]


final_training_df["messages"] = final_training_df.apply(
    build_chat_messages,
    axis=1
)

print("Final QLoRA training dataset")
print("=" * 60)

print("Training examples:", len(final_training_df))

print("\nColumns:")
print(final_training_df.columns.tolist())

print("\nSample chat example:")
print(
    final_training_df.iloc[0]["messages"]
)

Final QLoRA training dataset
============================================================
Training examples: 2885

Columns:
['id', 'title', 'content_clean', 'teacher_output', 'generation_status', 'instruction', 'response', 'parse_status', 'instruction_normalized', 'exact_eval_match', 'messages']

Sample chat example:
[{'role': 'system', 'content': 'You are an educational assistant specializing in nephrology. Provide clear, factual, educational explanations. Do not provide diagnosis or personalized medical advice.'}, {'role': 'user', 'content': 'Where does the hemiazygos vein typically arise and how does it connect to other veins?'}, {'role': 'assistant', 'content': 'The hemiazygos vein typically arises at the junction between the left ascending lumbar vein and the left subcostal vein, and it often has a connection to the left renal vein.'}]

**7.8.1 Finalize the Training Dataset Schema**

The training examples are now represented in the Llama chat format.

Before creating the Hugging Face training dataset, we remove temporary columns that were created only for leakage and deduplication diagnostics.

We retain the source identifier, source textbook, original passage, raw teacher output, generated instruction, generated response, and final chat messages.

Keeping the raw source and teacher output preserves traceability for later auditing, while only the `messages` field will be used as the conversational training input.

**Expected outcome:** a clean final training dataframe with only the fields needed for training and auditability.

In [54]:
### Finalize training dataframe

final_training_df = final_training_df[
    [
        "id",
        "title",
        "content_clean",
        "teacher_output",
        "instruction",
        "response",
        "messages",
    ]
].copy()

final_training_df.reset_index(drop=True, inplace=True)

print("Final training dataframe")
print("=" * 60)

print("Rows:", len(final_training_df))
print("Columns:", final_training_df.columns.tolist())

print("\nMissing values:")
print(
    final_training_df[
        [
            "id",
            "title",
            "content_clean",
            "teacher_output",
            "instruction",
            "response",
            "messages",
        ]
    ].isna().sum()
)

print("\nSample:")
print(
    final_training_df.iloc[0][
        [
            "id",
            "title",
            "instruction",
            "response",
        ]
    ].to_string()
)

Final training dataframe
============================================================
Rows: 2885
Columns: ['id', 'title', 'content_clean', 'teacher_output', 'instruction', 'response', 'messages']

Missing values:
id                0
title             0
content_clean     0
teacher_output    0
instruction       0
response          0
messages          0
dtype: int64

Sample:
id                                              Anatomy_Gray_460
title                                               Anatomy_Gray
instruction    Where does the hemiazygos vein typically arise...
response       The hemiazygos vein typically arises at the ju...

**7.8.2 Save the Final Training Dataset**

The final training dataframe contains 2,885 deduplicated, leakage-checked instruction-response examples.

We now persist the dataset to the Kaggle working directory before proceeding to tokenization and QLoRA preparation.

Two representations will be saved:

- CSV: convenient for inspection and audit
- JSONL: preserves the nested `messages` structure used for conversational fine-tuning

The raw teacher output and source metadata are retained in both artifacts where applicable.

**Expected outcome:** durable training-data files are created in `/kaggle/working/`.

In [55]:
### Save the final training dataset

import json
import os

output_dir = "/kaggle/working/nephrollm_final_training_data"
os.makedirs(output_dir, exist_ok=True)

# 1. Save an audit-friendly CSV.
# Convert messages to JSON text so the nested structure is preserved.
csv_df = final_training_df.copy()

csv_df["messages"] = csv_df["messages"].apply(
    lambda x: json.dumps(x, ensure_ascii=False)
)

csv_path = os.path.join(
    output_dir,
    "nephrollm_final_training_dataset.csv"
)

csv_df.to_csv(
    csv_path,
    index=False
)

# 2. Save JSONL with the complete training/audit record.
jsonl_path = os.path.join(
    output_dir,
    "nephrollm_final_training_dataset.jsonl"
)

with open(jsonl_path, "w", encoding="utf-8") as f:
    for record in final_training_df.to_dict(
        orient="records"
    ):
        f.write(
            json.dumps(
                record,
                ensure_ascii=False
            )
            + "\n"
        )

print("Final training dataset saved")
print("=" * 60)

print("Examples:", len(final_training_df))

print("\nCSV:")
print(csv_path)

print("\nJSONL:")
print(jsonl_path)

print("\nCSV size (MB):", round(
    os.path.getsize(csv_path) / (1024 ** 2), 2
))

print("JSONL size (MB):", round(
    os.path.getsize(jsonl_path) / (1024 ** 2), 2
))

Final training dataset saved
============================================================
Examples: 2885

CSV:
/kaggle/working/nephrollm_final_training_data/nephrollm_final_training_dataset.csv

JSONL:
/kaggle/working/nephrollm_final_training_data/nephrollm_final_training_dataset.jsonl

CSV size (MB): 5.38
JSONL size (MB): 5.59

# 8. Fine-tune using QLoRA

# 8.1 Explain QLoRA configuration

# 8.2 Configure LoRA adapters

# 8.3 Configure training arguments

# 8.4 Train the model

# 8.5 Inspect training metrics

# 9. Save the LoRA adapter

# 9.1 Save adapter

# 9.2 Verify saved artifacts

# 9.3 Save tokenizer/configuration if required

# 10. Run the exact same evaluation on the fine-tuned model

# 10.1 Load the fine-tuned adapter

# 10.2 Reuse the same inference protocol

# 10.3 Reuse the same MCQ prompt

# 10.4 Reuse the same parser

# 10.5 Evaluate the same 636 questions

# 10.6 Aggregate results

# 11. Evaluate on held-out questions

# 11.1 Run inference on 160 held-out questions

# 11.2 Parse responses

# 11.3 Calculate held-out accuracy

# 11.4 Analyze unparsed responses

# 12. Compare base vs fine-tuned model

# 12.1 Overall accuracy comparison

# 12.2 Answered-only accuracy comparison

# 12.3 Unparsed-response comparison

# 12.4 Subject-level comparison

# 12.5 Error-pattern comparison

# 12.6 Held-out comparison

# 13. Document findings, limitations, and conclusions

# 13.1 Key findings

# 13.2 What improved

# 13.3 What did not improve

# 13.4 Limitations

# 13.5 Data leakage considerations

# 13.6 Conclusion